# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_bill',
            name='month',
            field=models.CharField(default=11, max_length=20),
        ),
    ]
