# Generated by Django 3.1.5 on 2023-02-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
