# Generated by Django 3.1.5 on 2024-04-21 17:16

import applications.central_mess.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_auto_20240421_1716'),
        ('central_mess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deregistration_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('deregistration_remark', models.CharField(default='NA', max_length=50)),
                ('end_date', models.DateField(default=None, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
        migrations.CreateModel(
            name='Reg_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=10)),
                ('current_mess_status', models.CharField(default='Deregistered', max_length=20)),
                ('balance', models.IntegerField(default=0)),
                ('mess_option', models.CharField(default='mess2', max_length=20)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
        migrations.CreateModel(
            name='Reg_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=None, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
        migrations.CreateModel(
            name='Registration_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Txn_no', models.CharField(max_length=20)),
                ('img', models.ImageField(default=None, upload_to='images/')),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('registration_remark', models.CharField(default='NA', max_length=50)),
                ('start_date', models.DateField(default=None, null=True)),
                ('payment_date', models.DateField(default=None, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
        migrations.CreateModel(
            name='Semdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='year',
            new_name='payment_year',
        ),
        migrations.RemoveField(
            model_name='monthly_bill',
            name='nonveg_total_bill',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_remark',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='monthly_bill',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_date',
            field=models.DateField(default=datetime.date(2024, 4, 21)),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_month',
            field=models.CharField(default=applications.central_mess.models.current_month, max_length=20),
        ),
        migrations.AddField(
            model_name='rebate',
            name='rebate_remark',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mess',
            field=models.CharField(choices=[('mess1', 'Mess1'), ('mess2', 'Mess2')], default='mess1', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mess_option',
            field=models.CharField(choices=[('mess1', 'Mess1'), ('mess2', 'Mess2')], default='mess2', max_length=20),
        ),
        migrations.AlterField(
            model_name='messinfo',
            name='mess_option',
            field=models.CharField(choices=[('mess1', 'Mess1'), ('mess2', 'Mess2')], default='mess2', max_length=20),
        ),
        migrations.AlterField(
            model_name='special_request',
            name='item1',
            field=models.CharField(choices=[('dal_chawal', 'Dal Chawal'), ('khicdi', 'Khicdi'), ('tomato_soup', 'Tomato Soup')], default='dal_chawal', max_length=50),
        ),
        migrations.AlterField(
            model_name='special_request',
            name='item2',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='breakfast', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='payments',
            unique_together={('student_id', 'payment_date')},
        ),
        migrations.DeleteModel(
            name='Nonveg_data',
        ),
        migrations.DeleteModel(
            name='Nonveg_menu',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='sem',
        ),
    ]
