# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-08 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
        ('central_mess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='menu_change_request',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='messinfo',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='monthly_bill',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='nonveg_data',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='rebate',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='special_request',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='vacation_food',
            old_name='student_id',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='messinfo',
            unique_together=set([('student', 'mess_option')]),
        ),
        migrations.AlterUniqueTogether(
            name='monthly_bill',
            unique_together=set([('student', 'month', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='payments',
            unique_together=set([('student', 'sem', 'year')]),
        ),
    ]
