# Generated by Django 3.1.5 on 2023-03-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly_bill',
            name='nonveg_total_bill',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mess',
            field=models.CharField(choices=[('mess1', 'Mess1'), ('mess2', 'Mess2')], default='mess1', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mess_option',
            field=models.CharField(choices=[('mess1', 'Mess1'), ('mess2', 'Mess2')], default='mess2', max_length=20),
        ),
        migrations.AlterField(
            model_name='messinfo',
            name='mess_option',
            field=models.CharField(choices=[('mess1', 'Mess1'), ('mess2', 'Mess2')], default='mess2', max_length=20),
        ),
        migrations.DeleteModel(
            name='Nonveg_data',
        ),
        migrations.DeleteModel(
            name='Nonveg_menu',
        ),
    ]
