# Generated by Django 3.1.5 on 2024-10-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0002_auto_20241017_0040'),
        ('central_mess', '0002_auto_20241016_1905'),
        ('central_mess', '0002_auto_20241012_1459'),
    ]

    operations = [
    ]
