# Generated by Django 3.1.5 on 2023-02-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0002_payments_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='status',
        ),
        migrations.AddField(
            model_name='monthly_bill',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
