# Generated by Django 3.1.5 on 2023-04-05 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0003_auto_20230331_1935'),
        ('central_mess', '0002_monthly_bill_paid'),
    ]

    operations = [
    ]
