# Generated by Django 3.1.5 on 2024-11-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0003_merge_20241023_1016'),
        ('central_mess', '0002_auto_20241018_0342'),
    ]

    operations = [
    ]
