# Generated by Django 3.1.5 on 2025-03-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0003_auto_20250209_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_request',
            name='img',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
