# Generated by Django 3.1.5 on 2025-01-21 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0003_merge_20241023_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
