# Generated by Django 3.1.5 on 2023-02-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0003_auto_20230210_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly_bill',
            name='status',
        ),
    ]
