# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-21 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0003_auto_20200123_2006'),
        ('central_mess', '0004_auto_20200303_1019'),
        ('central_mess', '0003_auto_20200203_0247'),
    ]

    operations = [
    ]
