# Generated by Django 3.1.5 on 2023-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0004_remove_monthly_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_bill',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
