# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0004_auto_20200214_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_bill',
            name='month',
            field=models.CharField(default=5, max_length=20),
        ),
    ]
