# Generated by Django 3.1.5 on 2024-03-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0004_merge_20230405_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_remark',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='rebate',
            name='rebate_remark',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
