# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0005_merge_20200521_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_bill',
            name='month',
            field=models.CharField(default=5, max_length=20),
        ),
    ]
