# Generated by Django 3.1.5 on 2024-11-16 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0004_merge_20241115_1610'),
        ('central_mess', '0003_merge_20241110_1253'),
        ('central_mess', '0005_auto_20241112_2009'),
    ]

    operations = [
    ]
