# Generated by Django 3.0.6 on 2020-05-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0004_auto_20200204_0102'),
        ('central_mess', '0006_auto_20200521_2351'),
    ]

    operations = [
    ]
