# Generated by Django 3.1.5 on 2024-11-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0007_merge_20241118_1914'),
        ('central_mess', '0007_merge_20241118_1545'),
    ]

    operations = [
    ]
