# Generated by Django 3.0.6 on 2020-05-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0007_merge_20200522_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_bill',
            name='month',
            field=models.CharField(default=5, max_length=20),
        ),
    ]
