# Generated by Django 3.0.6 on 2020-06-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0009_auto_20200601_1214'),
        ('central_mess', '0006_auto_20200601_2224'),
    ]

    operations = [
    ]
