# Generated by Django 3.0.6 on 2020-06-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0010_merge_20200603_0112'),
        ('central_mess', '0005_auto_20200520_1450'),
    ]

    operations = [
    ]
