# Generated by Django 3.0.6 on 2020-06-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0011_merge_20200605_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_bill',
            name='month',
            field=models.CharField(default=6, max_length=20),
        ),
    ]
