# Generated by Django 3.0.6 on 2020-06-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0012_auto_20200605_1951'),
        ('central_mess', '0004_auto_20200603_2137'),
    ]

    operations = [
    ]
