# Generated by Django 3.0.7 on 2020-06-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0013_merge_20200606_1159'),
        ('central_mess', '0009_auto_20200603_1315'),
    ]

    operations = [
    ]
