# Generated by Django 3.0.7 on 2020-06-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0006_auto_20200601_0325'),
        ('central_mess', '0014_merge_20200611_2326'),
    ]

    operations = [
    ]
