# Generated by Django 3.0.7 on 2020-06-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0015_merge_20200613_1940'),
        ('central_mess', '0015_merge_20200613_1305'),
    ]

    operations = [
    ]
