# Generated by Django 3.0.7 on 2020-07-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0015_merge_20200705_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_bill',
            name='month',
            field=models.CharField(default=7, max_length=20),
        ),
    ]
