# Generated by Django 3.0.7 on 2020-07-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0016_merge_20200615_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_bill',
            name='month',
            field=models.CharField(default=7, max_length=20),
        ),
    ]
