# Generated by Django 3.0.7 on 2020-07-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0017_auto_20200703_1804'),
        ('central_mess', '0016_auto_20200705_1726'),
    ]

    operations = [
    ]
