# Generated by Django 3.1.5 on 2021-02-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0018_merge_20210228_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_bill',
            name='month',
            field=models.CharField(default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='monthly_bill',
            name='year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='payments',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
