# Generated by Django 3.1.5 on 2021-03-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0019_auto_20210228_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_bill',
            name='month',
            field=models.CharField(default=3, max_length=20),
        ),
    ]
