# Generated by Django 3.1.5 on 2021-04-26 23:55

import applications.central_mess.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0020_auto_20210422_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_bill',
            name='month',
            field=models.CharField(default=applications.central_mess.models.current_month, max_length=20),
        ),
    ]
