# Generated by Django 3.1.5 on 2021-04-30 22:46

import applications.central_mess.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0021_auto_20210426_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_bill',
            name='year',
            field=models.IntegerField(default=applications.central_mess.models.current_year),
        ),
        migrations.AlterField(
            model_name='payments',
            name='year',
            field=models.IntegerField(default=applications.central_mess.models.current_year),
        ),
    ]
