# Generated by Django 3.1.5 on 2024-04-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_achievement',
            name='a_year',
            field=models.IntegerField(blank=True, choices=[(1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='emp_achievement',
            name='pf_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='k_year',
            field=models.IntegerField(blank=True, choices=[(1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='pf_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_consultancy_projects',
            name='pf_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_event_organized',
            name='pf_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_expert_lectures',
            name='l_year',
            field=models.IntegerField(blank=True, choices=[(1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='emp_expert_lectures',
            name='pf_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_keynote_address',
            name='k_year',
            field=models.IntegerField(blank=True, choices=[(1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='emp_keynote_address',
            name='pf_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_mtechphd_thesis',
            name='pf_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_mtechphd_thesis',
            name='s_year',
            field=models.IntegerField(blank=True, choices=[(1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='emp_patents',
            name='p_year',
            field=models.IntegerField(blank=True, choices=[(1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='emp_patents',
            name='pf_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_published_books',
            name='pf_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_published_books',
            name='pyear',
            field=models.IntegerField(blank=True, choices=[(1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='emp_research_papers',
            name='pf_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_research_papers',
            name='year',
            field=models.CharField(blank=True, choices=[(1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='emp_research_projects',
            name='pf_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_session_chair',
            name='pf_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_techtransfer',
            name='pf_no',
            field=models.CharField(max_length=20),
        ),
    ]
