# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-21 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0002_auto_20200203_0247'),
        ('eis', '0002_auto_20200123_2047'),
        ('eis', '0002_auto_20200123_2006'),
    ]

    operations = [
    ]
