# Generated by Django 3.0.6 on 2020-05-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0004_merge_20200522_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_research_papers',
            name='is_sci',
            field=models.CharField(blank=True, choices=[('SCI', 'SCI'), ('SCIE', 'SCIE')], max_length=6, null=True),
        ),
    ]
