# Generated by Django 3.1.5 on 2021-04-21 21:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eis', '0006_auto_20210303_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faculty_about',
            new_name='eis_faculty_about',
        ),
    ]
