# Generated by Django 3.1.5 on 2021-05-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0008_auto_20210511_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_research_papers',
            name='doi',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
