# Generated by Django 5.2.6 on 2026-02-05 10:17

import applications.vms.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globals', '0005_moduleaccess_patent_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(db_index=True, max_length=64)),
                ('reason', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blacklist Entry',
                'verbose_name_plural': 'Blacklist Entries',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200)),
                ('host_name', models.CharField(max_length=120)),
                ('host_department', models.CharField(max_length=120)),
                ('host_contact', models.CharField(blank=True, max_length=50)),
                ('expected_duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('id_verified', 'ID Verified'), ('pass_issued', 'Pass Issued'), ('inside', 'Inside'), ('exited', 'Exited'), ('denied', 'Denied')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('pass_issued_at', models.DateTimeField(blank=True, null=True)),
                ('entry_at', models.DateTimeField(blank=True, null=True)),
                ('exit_at', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.CharField(blank=True, max_length=200)),
                ('denial_remarks', models.TextField(blank=True)),
                ('is_vip', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('id_number', models.CharField(max_length=64, unique=True)),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driver_license', 'Driver License'), ('aadhaar', 'Aadhaar Card')], max_length=20)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('photo_reference', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('biometric', 'Biometric')], default='manual', max_length=20)),
                ('result', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vms_verifications', to='globals.extrainfo')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='vms.visit')),
            ],
        ),
        migrations.CreateModel(
            name='EntryExitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('gate_name', models.CharField(max_length=120)),
                ('items_declared', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vms_movements', to='globals.extrainfo')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_logs', to='vms.visit')),
            ],
        ),
        migrations.CreateModel(
            name='DenialLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=120)),
                ('remarks', models.TextField(blank=True)),
                ('escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denials', to='vms.visit')),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='vms.visitor'),
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('issue_type', models.CharField(choices=[('unauthorized_access', 'Unauthorized Access'), ('policy_violation', 'Policy Violation'), ('equipment_failure', 'Equipment Failure'), ('suspicious_behavior', 'Suspicious Behavior'), ('other', 'Other')], default='other', max_length=40)),
                ('description', models.TextField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vms_incidents', to='globals.extrainfo')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='vms.visit')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='vms.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_number', models.CharField(default=applications.vms.models._generate_pass_number, max_length=32, unique=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('authorized_zones', models.CharField(default='public', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('returned', 'Returned'), ('lost', 'Lost')], default='pending', max_length=20)),
                ('barcode_data', models.CharField(blank=True, max_length=128)),
                ('is_vip_pass', models.BooleanField(default=False)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_pass', to='vms.visit')),
            ],
        ),
    ]
