# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-27 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0009_auto_20191024_1252'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='register',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='register',
            name='curr_id',
        ),
        migrations.RemoveField(
            model_name='register',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
