# Generated by Django 3.1.5 on 2025-04-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('specifications', models.TextField()),
                ('approval_status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('NOT_APPROVED', 'NOT_APPROVED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20)),
            ],
        ),
    ]
