# Generated by Django 3.1.5 on 2021-03-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_information', '0005_auto_20200522_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselling_meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_date', models.DateField()),
                ('agenda', models.TextField()),
                ('venue', models.TextField()),
                ('meeting_time', models.CharField(choices=[('10', '10 a.m.'), ('11', '11 a.m.'), ('12', '12 p.m.'), ('13', '1 p.m.'), ('14', '2 p.m.'), ('15', '3 p.m.'), ('16', '4 p.m.'), ('17', '5 p.m.'), ('18', '6 p.m.'), ('19', '7 p.m.'), ('20', '8 p.m.'), ('21', '9 p.m.')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=400)),
                ('answer', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('category1', 'Academics'), ('category2', 'Personal'), ('category3', 'Others')], default='category1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_category', models.CharField(choices=[('category1', 'Academics'), ('category2', 'Personal'), ('category3', 'Others')], default='category1', max_length=20)),
                ('issue', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('status1', 'Unresolved'), ('status2', 'Resolved'), ('status3', 'InProgress')], default='status1', max_length=20)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
        migrations.CreateModel(
            name='Counselling_minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselling_minutes', models.FileField(upload_to='central_mess/')),
                ('meeting_date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='counselling_cell.counselling_meeting')),
            ],
        ),
        migrations.CreateModel(
            name='CounsellingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_position', models.CharField(choices=[('pos1', 'Student'), ('pos2', 'Student_Guide'), ('pos3', 'Student_Coordinator')], default='pos1', max_length=50)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'unique_together': {('student_id', 'student_position')},
            },
        ),
    ]
