# Generated by Django 3.1.5 on 2023-03-15 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_information', '0001_initial'),
        ('globals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingIssueCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=40, unique=True)),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CounsellingMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(default=datetime.date.today)),
                ('meeting_time', models.CharField(choices=[('10', '10 a.m.'), ('11', '11 a.m.'), ('12', '12 p.m.'), ('13', '1 p.m.'), ('14', '2 p.m.'), ('15', '3 p.m.'), ('16', '4 p.m.'), ('17', '5 p.m.'), ('18', '6 p.m.'), ('19', '7 p.m.'), ('20', '8 p.m.'), ('21', '9 p.m.')], max_length=20)),
                ('agenda', models.TextField()),
                ('venue', models.CharField(max_length=20)),
                ('student_invities', models.TextField(default=None, max_length=500)),
                ('meeting_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCounsellingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_position', models.CharField(choices=[('head_counsellor', 'Head Counsellor'), ('faculty_counsellor', 'Faculty Counsellor')], max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'faculty_position')},
            },
        ),
        migrations.CreateModel(
            name='StudentCounsellingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_position', models.CharField(choices=[('student_guide', 'Student Guide'), ('student_coordinator', 'Student Coordinator')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'unique_together': {('student_id', 'student_position')},
            },
        ),
        migrations.CreateModel(
            name='StudentMeetingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_time', models.DateTimeField()),
                ('description', models.TextField(max_length=1000)),
                ('requested_meeting_status', models.CharField(choices=[('status_accepted', 'Accepted'), ('status_pending', 'Pending')], default='status_pending', max_length=20)),
                ('recipient_reply', models.TextField(max_length=1000)),
                ('requested_faculty_invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counselling_cell.facultycounsellingteam')),
                ('requested_student_invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counselling_cell.studentcounsellingteam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCounsellingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
                ('student_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling_cell.studentcounsellingteam')),
            ],
        ),
        migrations.CreateModel(
            name='CounsellingMinutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselling_minutes', models.FileField(upload_to='counselling_cell/')),
                ('counselling_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling_cell.counsellingmeeting')),
            ],
        ),
        migrations.CreateModel(
            name='CounsellingIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_raised_date', models.DateTimeField(default=datetime.datetime.now)),
                ('issue', models.TextField(max_length=500)),
                ('issue_status', models.CharField(choices=[('status_unresolved', 'Unresolved'), ('status_resolved', 'Resolved'), ('status_inprogress', 'InProgress')], default='status_unresolved', max_length=20)),
                ('response_remark', models.TextField(max_length=500, null=True)),
                ('issue_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling_cell.counsellingissuecategory')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
        migrations.CreateModel(
            name='CounsellingFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselling_question', models.TextField(max_length=1000)),
                ('counselling_answer', models.TextField(max_length=5000)),
                ('counselling_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling_cell.counsellingissuecategory')),
            ],
        ),
    ]
