# Generated by Django 3.1.5 on 2021-05-11 18:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0008_auto_20210511_0944'),
        ('counselling_cell', '0002_auto_20210501_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcounsellinginfo',
            name='faculty_counsellor',
        ),
        migrations.AddField(
            model_name='counsellingissue',
            name='issue_raised_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='counsellingissue',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo'),
        ),
        migrations.AddField(
            model_name='counsellingissue',
            name='response_remark',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
