# Generated by Django 3.1.5 on 2021-05-17 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling_cell', '0003_auto_20210511_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellingmeeting',
            name='faculty_invities',
        ),
        migrations.AddField(
            model_name='counsellingmeeting',
            name='meeting_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='counsellingmeeting',
            name='meeting_time',
            field=models.CharField(choices=[('10', '10 a.m.'), ('11', '11 a.m.'), ('12', '12 p.m.'), ('13', '1 p.m.'), ('14', '2 p.m.'), ('15', '3 p.m.'), ('16', '4 p.m.'), ('17', '5 p.m.'), ('18', '6 p.m.'), ('19', '7 p.m.'), ('20', '8 p.m.'), ('21', '9 p.m.')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='counsellingmeeting',
            name='student_invities',
        ),
        migrations.AddField(
            model_name='counsellingmeeting',
            name='student_invities',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
