# Generated by Django 3.1.5 on 2023-03-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='u_type',
            field=models.CharField(choices=[('ug', 'ug'), ('pg', 'pg'), ('faculty', 'faculty'), ('staff', 'staff')], default='ug', max_length=20),
            preserve_default=False,
        ),
    ]
