# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 05:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holdsdesignation',
            unique_together=set([('user', 'designation'), ('working', 'designation')]),
        ),
    ]
