# Generated by Django 3.1.5 on 2023-04-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20230323_2222'),
        ('globals', '0002_auto_20230127_1451'),
    ]

    operations = [
    ]
