# Generated by Django 3.1.5 on 2025-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20241007_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_reset', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='moduleaccess',
            name='inventory_management',
            field=models.BooleanField(default=False),
        ),
    ]
