# Generated by Django 3.1.5 on 2024-11-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20241007_2302'),
        ('globals', '0002_auto_20241119_0823'),
    ]

    operations = [
    ]
