# Generated by Django 3.1.5 on 2023-03-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_extrainfo_u_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='user_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('PRESENT', 'PRESENT')], default='PRESENT', max_length=50),
        ),
    ]
