# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20191024_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentinfo',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
