# Generated by Django 3.1.5 on 2025-05-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20250402_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designation',
            name='category',
            field=models.CharField(default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='designation',
            name='dept_if_not_basic_id',
            field=models.IntegerField(null=True),
        ),
    ]
