# Generated by Django 3.1.5 on 2025-03-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20250204_1555'),
        ('globals', '0002_auto_20241007_2302'),
    ]

    operations = [
    ]
