# Generated by Django 3.1.5 on 2023-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20230326_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='rem_casual_leave',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='rem_medical_leave',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='rem_special_leave',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='rem_vacational_leave',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='user_status',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('NEW', 'NEW')], default='PRESENT', max_length=50),
        ),
    ]
