# Generated by Django 3.1.5 on 2024-11-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20241016_1905'),
        ('globals', '0003_auto_20241017_0040'),
        ('globals', '0003_auto_20241018_0342'),
    ]

    operations = [
    ]
