# Generated by Django 3.1.5 on 2025-02-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_passwordresettracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='last_selected_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
