# Generated by Django 3.1.5 on 2021-04-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20191024_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='type',
            field=models.CharField(choices=[('academic', 'Academic Designation'), ('administrative', 'Administrative Designation'), ('HOD', 'Head of Department'), ('DeanRSPC', ' Research Dean')], default='academic', max_length=30),
        ),
    ]
