# Generated by Django 3.1.5 on 2024-11-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20241016_1905'),
        ('globals', '0003_auto_20241017_0040'),
    ]

    operations = [
    ]
