# Generated by Django 3.1.5 on 2021-04-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_auto_20210420_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='type',
            field=models.CharField(choices=[('academic', 'Academic Designation'), ('administrative', 'Administrative Designation')], default='academic', max_length=30),
        ),
    ]
