# Generated by Django 3.1.5 on 2024-11-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_merge_20241107_1924'),
        ('globals', '0003_auto_20241018_0342'),
    ]

    operations = [
    ]
