# Generated by Django 3.1.5 on 2023-04-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20230323_2222'),
        ('globals', '0004_auto_20230327_1101'),
    ]

    operations = [
    ]
