# Generated by Django 3.1.5 on 2024-02-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20240217_1949'),
        ('globals', '0004_auto_20240217_0054'),
    ]

    operations = [
    ]
