# Generated by Django 3.1.5 on 2024-11-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_merge_20241110_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='user_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('PRESENT', 'PRESENT')], default='PRESENT', max_length=50),
        ),
    ]
