# Generated by Django 3.1.5 on 2023-04-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0005_auto_20230409_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfo',
            name='rem_casual_leave',
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='rem_medical_leave',
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='rem_special_leave',
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='rem_vacational_leave',
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='user_status',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('NEW', 'NEW')], default='PRESENT', max_length=50),
        ),
    ]
