# Generated by Django 3.1.5 on 2024-02-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0006_auto_20240218_1336'),
        ('globals', '0002_auto_20240217_1949'),
    ]

    operations = [
    ]
