# Generated by Django 3.1.5 on 2023-04-06 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_auto_20230313_1733'),
        ('globals', '0006_auto_20230404_1139'),
    ]

    operations = [
    ]
