# Generated by Django 3.1.5 on 2026-07-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0006_auto_20260304_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleaccess',
            name='thesis_research',
            field=models.BooleanField(default=False),
        ),
    ]
