# Generated by Django 3.1.5 on 2024-11-16 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_merge_20241115_1610'),
        ('globals', '0005_auto_20241115_1710'),
        ('globals', '0006_auto_20241112_2009'),
    ]

    operations = [
    ]
