# Generated by Django 3.1.5 on 2024-11-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0007_merge_20241116_0248'),
        ('globals', '0006_merge_20241116_0233'),
        ('globals', '0006_merge_20241116_0303'),
    ]

    operations = [
    ]
