# Generated by Django 3.1.5 on 2023-04-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0007_merge_20230404_1537'),
        ('globals', '0002_auto_20230404_1430'),
    ]

    operations = [
    ]
