# Generated by Django 3.1.5 on 2024-11-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0007_merge_20241118_1914'),
        ('globals', '0008_merge_20241118_1545'),
    ]

    operations = [
    ]
