# Generated by Django 3.1.5 on 2024-02-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0008_auto_20240219_0205'),
        ('globals', '0007_merge_20240218_2205'),
    ]

    operations = [
    ]
