# Generated by Django 3.1.5 on 2024-02-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0009_auto_20240214_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='globals.departmentinfo'),
        ),
    ]
