# Generated by Django 3.1.5 on 2023-04-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_auto_20230327_1101'),
        ('globals', '0009_auto_20230203_2041'),
        ('globals', '0002_auto_20230323_2222'),
    ]

    operations = [
    ]
