# Generated by Django 3.1.5 on 2024-04-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0010_auto_20240411_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='user_status',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('NEW', 'NEW')], default='PRESENT', max_length=50),
        ),
    ]
