# Generated by Django 3.1.5 on 2026-08-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0010_acad_programme_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_programme',
            field=models.CharField(blank=True, choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'Doctoral')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='audience_type',
            field=models.CharField(choices=[('all', 'Everyone'), ('role', 'Specific Role'), ('programme', 'Specific Programme Level'), ('batch', 'Specific Batch'), ('department', 'Specific Department'), ('individual', 'Specific Individuals')], max_length=20),
        ),
    ]
