# Generated by Django 3.1.5 on 2023-04-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0010_merge_20230406_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='user_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('PRESENT', 'PRESENT')], default='PRESENT', max_length=50),
        ),
    ]
