# Generated by Django 3.1.5 on 2024-02-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0011_merge_20240220_1814'),
        ('globals', '0003_auto_20240218_1955'),
        ('globals', '0011_merge_20240219_1730'),
    ]

    operations = [
    ]
