# Generated by Django 3.1.5 on 2026-04-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0015_auto_20260403_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='user_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('PRESENT', 'PRESENT')], default='PRESENT', max_length=50),
        ),
    ]
