# Generated by Django 3.1.5 on 2024-03-14 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0014_auto_20240312_1930'),
        ('globals', '0014_auto_20240312_1902'),
        ('globals', '0015_auto_20240312_2326'),
    ]

    operations = [
    ]
