# Generated by Django 3.1.5 on 2024-03-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0017_auto_20240314_2252'),
        ('globals', '0016_merge_20240313_2253'),
    ]

    operations = [
    ]
