# Generated by Django 3.1.5 on 2024-03-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0015_auto_20240315_2100'),
        ('globals', '0018_merge_20240315_1500'),
    ]

    operations = [
    ]
