# Generated by Django 3.1.5 on 2024-03-19 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0020_auto_20240315_2158'),
        ('globals', '0018_auto_20240315_2157'),
    ]

    operations = [
    ]
