# Generated by Django 3.0.6 on 2020-07-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcomplain',
            name='comment',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
