# Generated by Django 3.1.5 on 2026-03-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcomplain',
            name='history',
            field=models.JSONField(blank=True, default=list, help_text='Track status changes and modifications'),
        ),
    ]
