# Generated by Django 3.1.5 on 2023-04-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0002_auto_20230321_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcomplain',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentcomplain',
            name='specific_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
