# Generated by Django 3.1.5 on 2024-03-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0002_auto_20240218_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='area',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='type',
            field=models.CharField(choices=[('Electricity', 'Electricity'), ('carpenter', 'carpenter'), ('plumber', 'plumber'), ('garbage', 'garbage'), ('dustbin', 'dustbin'), ('internet', 'internet'), ('other', 'other')], default='Electricity', max_length=30),
        ),
    ]
