# Generated by Django 3.1.5 on 2025-04-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20241007_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcomplain',
            name='upload_resolved',
            field=models.FileField(blank=True, null=True, upload_to='resolved_complaints/'),
        ),
    ]
