# Generated by Django 3.1.5 on 2026-03-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0002_studentcomplain_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcomplain',
            name='history',
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='escalated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='escalation_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='is_escalated',
            field=models.IntegerField(default=0),
        ),
    ]
