# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0002_remove_caretaker_myfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='myfeedback',
            field=models.CharField(default='this is my feedback', max_length=400),
        ),
    ]
