# Generated by Copilot on 2026-04-07

from django.db import migrations, models
import django.utils.timezone


def backfill_complaint_ref(apps, schema_editor):
    StudentComplain = apps.get_model('complaint_system', 'StudentComplain')
    for complaint in StudentComplain.objects.all().order_by('id'):
        if not complaint.complaint_ref:
            complaint.complaint_ref = f"CMP-LEGACY-{complaint.id:06d}"
            complaint.save(update_fields=['complaint_ref'])


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0003_auto_20260324_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcomplain',
            name='complaint_ref',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='priority',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Standard', 'Standard'), ('Low', 'Low')], default='Standard', max_length=20),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='assigned_complaints', to='complaint_system.workers'),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='verification_source',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='reopen_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='reopen_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='reopen_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentcomplain',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Resolved'), (3, 'Closed'), (4, 'Escalated'), (5, 'Reopened')], default=0),
        ),
        migrations.RunPython(backfill_complaint_ref, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentcomplain',
            name='complaint_ref',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='ComplaintEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('from_status', models.IntegerField(blank=True, null=True)),
                ('to_status', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=False, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to='globals.extrainfo')),
                ('complaint', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='events', to='complaint_system.studentcomplain')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
