# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0003_auto_20200303_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='designation_name',
        ),
        migrations.AddField(
            model_name='hall',
            name='designation_name',
            field=models.CharField(choices=[('hall1caretaker', 'hall1caretaker'), ('hall3caretaker', 'hall3caretaker'), ('hall4caretaker', 'hall4caretaker'), ('cc1convener', 'cc1convener'), ('CC2 convener', 'CC2 convener'), ('corelabcaretaker', 'corelabcaretaker')], default='hall3caretaker', max_length=20),
        ),
    ]
