# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-08 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0003_caretaker_myfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcomplain',
            name='upload_complaint',
        ),
    ]
