# Generated by Copilot on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0005_complaint_team_and_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcomplain',
            name='estimated_resolution_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='progress_attachment',
            field=models.FileField(blank=True, upload_to='complaint/progress/'),
        ),
        migrations.AddField(
            model_name='studentcomplain',
            name='progress_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
