# Generated by Django 3.1.5 on 2021-04-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globals', '0003_auto_20191024_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('ipd_form', models.FileField(blank=True, upload_to='')),
                ('project_details', models.FileField(blank=True, upload_to='')),
                ('status', models.CharField(choices=[('Approve', 'Approve'), ('Disapprove', 'Disapprove'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo')),
            ],
        ),
    ]
