# Generated by Django 3.1.5 on 2024-07-16 15:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=500)),
                ('sub_category_name', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-category_id'],
            },
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=600)),
                ('project_type', models.CharField(max_length=500)),
                ('sponsored_agency', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('submission_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('years', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('project_info_file', models.FileField(blank=True, null=True, upload_to='')),
                ('financial_outlay_status', models.IntegerField(default=0)),
                ('co_project_investigator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copi_id', to=settings.AUTH_USER_MODEL)),
                ('project_investigator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-project_id'],
            },
        ),
        migrations.CreateModel(
            name='staff_allocations',
            fields=[
                ('staff_allocation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=500)),
                ('qualification', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('stipend', models.IntegerField()),
                ('staff_type', models.CharField(default='research', max_length=100)),
                ('start_date', models.DateField(default=datetime.date(2024, 7, 16))),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-staff_allocation_id'],
            },
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=500)),
                ('approval_status', models.IntegerField(default=0)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
                ('project_investigator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rj_pi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_id'],
            },
        ),
        migrations.CreateModel(
            name='financial_outlay',
            fields=[
                ('financial_outlay_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=500)),
                ('sub_category', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('staff_limit', models.IntegerField(default=0)),
                ('utilized_amount', models.IntegerField(default=0, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
            ],
            options={
                'ordering': ['-financial_outlay_id'],
            },
        ),
        migrations.CreateModel(
            name='co_project_investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_pi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
            ],
            options={
                'ordering': ['-co_pi_id'],
            },
        ),
        migrations.CreateModel(
            name='co_pis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
            ],
            options={
                'ordering': ['-project_id'],
            },
        ),
    ]
