# Generated by Django 3.1.5 on 2025-03-30 02:40

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=600)),
                ('pi_id', models.CharField(max_length=150)),
                ('pi_name', models.CharField(max_length=150)),
                ('access', models.CharField(choices=[('Co', 'Only PI'), ('noCo', 'Either PI or Co-PI(s)')], default='Co', max_length=10)),
                ('type', models.CharField(choices=[('Research', 'Research'), ('Consultancy', 'Consultancy')], max_length=50)),
                ('dept', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('SM', 'Smart Manufacturing'), ('Design', 'Design'), ('NS', 'Natural Sciences'), ('Liberal Arts', 'Liberal Arts'), ('none', 'None Of The Above')], max_length=50)),
                ('category', models.CharField(choices=[('Government', 'Governement'), ('Private', 'Private Entity'), ('IIITDMJ', 'Institute'), ('Other', 'Other')], max_length=50)),
                ('sponsored_agency', models.CharField(max_length=500)),
                ('scheme', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('submission_date', models.DateField(default=datetime.date(2025, 3, 30))),
                ('total_budget', models.IntegerField(default=0)),
                ('sanction_date', models.DateField(blank=True, null=True)),
                ('sanctioned_amount', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('initial_amount', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='RSPC/')),
                ('registration_form', models.FileField(blank=True, null=True, upload_to='RSPC/')),
                ('status', models.CharField(choices=[('OnGoing', 'OnGoing'), ('Submitted', 'Submitted'), ('Registered', 'Registered'), ('RSPC Approval', 'RSPC Approval'), ('HoD Forward', 'HoD Forward'), ('Completed', 'Completed')], max_length=50)),
                ('end_report', models.FileField(blank=True, null=True, upload_to='RSPC/')),
                ('end_approval', models.CharField(blank=True, choices=[('OnGoing', 'OnGoing'), ('Submitted', 'Submitted'), ('Registered', 'Registered'), ('RSPC Approval', 'RSPC Approval'), ('HoD Forward', 'HoD Forward'), ('Completed', 'Completed')], max_length=50, null=True)),
            ],
            options={
                'ordering': ['-pid'],
            },
        ),
        migrations.CreateModel(
            name='staff_positions',
            fields=[
                ('spid', models.AutoField(primary_key=True, serialize=False)),
                ('positions', models.JSONField()),
                ('incumbents', models.JSONField()),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('person', models.CharField(blank=True, max_length=300, null=True)),
                ('uname', models.CharField(blank=True, max_length=150, null=True)),
                ('biodata_number', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Research Associate', 'Research Associate'), ('Senior Research Fellow', 'Senior Research Fellow'), ('Junior Research Fellow', 'Junior Research Fellow'), ('Supporting Staff', 'Supporting Staff'), ('Project Trainee', 'Project Trainee')], default='Supporting Staff', max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_funds', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10)),
                ('post_on_website', models.FileField(blank=True, null=True, upload_to='RSPC/')),
                ('submission_date', models.DateField(default=datetime.date(2025, 3, 30))),
                ('interview_date', models.DateField(default=datetime.date(2025, 3, 30))),
                ('test_date', models.DateField(default=datetime.date(2025, 3, 30))),
                ('test_mode', models.CharField(default='Written', max_length=100)),
                ('interview_place', models.CharField(default='IIITDM Jabalpur', max_length=100)),
                ('selection_committee', models.JSONField(default={})),
                ('candidates_applied', models.IntegerField(blank=True, null=True)),
                ('candidates_called', models.IntegerField(blank=True, null=True)),
                ('candidates_interviewed', models.IntegerField(blank=True, null=True)),
                ('final_selection', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None)),
                ('waiting_list', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None)),
                ('biodata_final', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None)),
                ('biodata_waiting', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None)),
                ('ad_file', models.FileField(blank=True, null=True, upload_to='RSPC/')),
                ('comparative_file', models.FileField(blank=True, null=True, upload_to='RSPC/')),
                ('approval', models.CharField(choices=[('Approved', 'Approved'), ('RSPC Approval', 'RSPC Approval'), ('HoD Forward', 'HoD Forward'), ('Hiring', 'Hiring'), ('Pending', 'Pending'), ('Committee Approval', 'Committee Approval')], max_length=50)),
                ('gave_verdict', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, size=None)),
                ('current_approver', models.CharField(blank=True, max_length=150, null=True)),
                ('joining_report', models.FileField(blank=True, null=True, upload_to='RSPC/')),
                ('doc_approval', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('RSPC Approval', 'RSPC Approval'), ('HoD Forward', 'HoD Forward'), ('Hiring', 'Hiring'), ('Pending', 'Pending'), ('Committee Approval', 'Committee Approval')], max_length=50, null=True)),
                ('salary_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('id_card', models.FileField(blank=True, null=True, upload_to='RSPC/')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
            ],
        ),
        migrations.CreateModel(
            name='project_access',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('copi_id', models.CharField(max_length=150)),
                ('affiliation', models.CharField(blank=True, max_length=300, null=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_pis', to='research_procedures.projects')),
            ],
            options={
                'ordering': ['-pid'],
            },
        ),
        migrations.CreateModel(
            name='expenditure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.IntegerField(default=0)),
                ('exptype', models.CharField(choices=[('Tangible', 'Physical Item'), ('Non-tangible', 'Non-tangible Resource')], max_length=50)),
                ('item', models.CharField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lastdate', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(max_length=50)),
                ('inventory', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('approval', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=50)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
            ],
        ),
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manpower', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('travel', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('contingency', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('consumables', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('equipments', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('overhead', models.IntegerField(default=0)),
                ('current_funds', models.IntegerField(blank=True, default=0, null=True)),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='research_procedures.projects')),
            ],
        ),
    ]
