# Generated by Django 3.1.5 on 2024-02-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('sponsored_agency', models.CharField(max_length=500)),
            ],
        ),
    ]
