# Generated by Django 3.1.5 on 2021-04-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='file1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='file2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='ipd_form',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patent',
            name='project_details',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patent',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
