# Generated by Django 3.1.5 on 2024-03-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pr_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
