# Generated by Django 3.1.5 on 2024-10-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='pi_id',
            field=models.CharField(max_length=150),
        ),
    ]
