# Generated by Django 3.1.5 on 2024-04-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_allocations',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_allocations',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial_outlay',
            name='utilized_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
