# Generated by Django 3.1.5 on 2024-10-23 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0002_auto_20241010_1836'),
        ('research_procedures', '0002_auto_20241021_2042'),
        ('research_procedures', '0002_auto_20241015_1451'),
    ]

    operations = [
    ]
