# Generated by Django 3.1.5 on 2024-10-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0002_auto_20241021_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='approval',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='exptype',
            field=models.CharField(choices=[('Tangible', 'Physical Item'), ('Non-tangible', 'Non-tangible Resource')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('Government', 'Governement'), ('Private', 'Private Entity'), ('IIITDMJ', 'Institute'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('OnGoing', 'OnGoing'), ('Terminated', 'Terminated'), ('Completed', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('Research', 'Research'), ('Product', 'Product'), ('Consultancy', 'Consultancy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='approval',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('Co-Project Investigator', 'Co-Project Investigator'), ('Research Scholar', 'Research Scholar'), ('Research Assistant', 'Research Assistant'), ('Supporting Staff', 'Supporting Staff'), ('Student Intern', 'Student Intern')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qualification',
            field=models.CharField(choices=[('MTech', 'MTech Student'), ('Phd', 'PhD Student'), ('Professor', 'Teaching Faculty'), ('Other', 'Other Supporting Staff')], max_length=50),
        ),
    ]
