# Generated by Django 3.1.5 on 2024-11-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0002_auto_20241016_1905'),
        ('research_procedures', '0002_auto_20241012_1459'),
        ('research_procedures', '0002_auto_20241017_0040'),
        ('research_procedures', '0002_auto_20241018_0342'),
    ]

    operations = [
    ]
