# Generated by Django 3.1.5 on 2024-02-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0002_ad_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchgroup',
            name='faculty_under_group',
        ),
        migrations.RemoveField(
            model_name='researchgroup',
            name='students_under_group',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='techtransfer',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConsultancyProject',
        ),
        migrations.DeleteModel(
            name='ResearchGroup',
        ),
        migrations.DeleteModel(
            name='ResearchProject',
        ),
        migrations.DeleteModel(
            name='TechTransfer',
        ),
    ]
