# Generated by Django 3.1.5 on 2024-11-16 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0003_merge_20241110_1253'),
        ('research_procedures', '0003_merge_20241115_1509'),
    ]

    operations = [
    ]
