# Generated by Django 3.1.5 on 2024-11-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0002_auto_20241018_0342'),
        ('research_procedures', '0003_merge_20241107_1924'),
    ]

    operations = [
    ]
