# Generated by Django 3.1.5 on 2024-10-22 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0003_auto_20241021_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects'),
        ),
        migrations.CreateModel(
            name='project_access',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lead_id', models.CharField(max_length=150)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
            ],
            options={
                'ordering': ['-lead_id'],
            },
        ),
    ]
