# Generated by Django 3.1.5 on 2024-04-25 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0003_auto_20240424_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_allocations',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 4, 25)),
        ),
    ]
