# Generated by Django 3.1.5 on 2024-03-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0003_prudvi'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=500)),
                ('project_type', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('financial_outlay', models.IntegerField()),
                ('project_investigator_id', models.CharField(max_length=500)),
                ('rspc_admin_id', models.CharField(max_length=500)),
                ('co_project_investigator_id', models.CharField(max_length=500)),
                ('sponsored_agency', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('submission_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('request_type', models.CharField(max_length=500)),
                ('project_investigator_id', models.CharField(max_length=400)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='prudvi',
        ),
    ]
