# Generated by Django 3.1.5 on 2024-03-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0004_auto_20240303_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_staff_info',
            fields=[
                ('staff_id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('project_investigator_id', models.CharField(max_length=500)),
                ('project_id', models.IntegerField()),
                ('staff_name', models.CharField(max_length=400)),
                ('status', models.IntegerField()),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='rspc_inventory',
            fields=[
                ('inventory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField()),
                ('project_investigator_id', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('description', models.CharField(max_length=400)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='patent',
            name='faculty_id',
        ),
        migrations.DeleteModel(
            name='pr_test',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='id',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='id',
        ),
        migrations.AddField(
            model_name='requests',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requests',
            name='description',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requests',
            name='project_investigator_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requests',
            name='request_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Patent',
        ),
    ]
