# Generated by Django 3.1.5 on 2024-02-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0004_auto_20240218_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('request_type', models.CharField(max_length=500)),
                ('project_investigator_id', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='rspc',
            new_name='rspc_admin_id',
        ),
    ]
