# Generated by Django 3.1.5 on 2024-11-12 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0004_merge_20241112_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_allocations',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
