# Generated by Django 3.1.5 on 2024-02-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0005_auto_20240218_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='project_investigator_id',
            field=models.CharField(max_length=400),
        ),
    ]
