# Generated by Django 3.1.5 on 2024-10-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0005_auto_20241023_0556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='requests',
        ),
    ]
