# Generated by Django 3.1.5 on 2024-03-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0005_auto_20240303_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-project_id']},
        ),
        migrations.RemoveField(
            model_name='projects',
            name='rspc_admin_id',
        ),
        migrations.AlterField(
            model_name='project_staff_info',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rspc_inventory',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
