# Generated by Django 3.1.5 on 2024-03-03 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research_procedures', '0006_auto_20240303_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_staff_info',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_pji', to='research_procedures.projects'),
        ),
        migrations.AlterField(
            model_name='project_staff_info',
            name='project_investigator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projects',
            name='co_project_investigator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jn_copi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_investigator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jn_pid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requests',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='project_investigator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rj_pi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rspc_inventory',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects'),
        ),
        migrations.AlterField(
            model_name='rspc_inventory',
            name='project_investigator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rin_pi', to=settings.AUTH_USER_MODEL),
        ),
    ]
