# Generated by Django 3.1.5 on 2024-10-23 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0006_delete_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.IntegerField()),
                ('request_type', models.CharField(choices=[('Expenditure', 'Expenditure'), ('Staff', 'Staff')], max_length=50)),
                ('rid', models.IntegerField()),
                ('subject', models.CharField(max_length=300)),
                ('requestor', models.CharField(max_length=150)),
                ('holder', models.CharField(max_length=150)),
                ('approval', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=50)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
