# Generated by Django 3.1.5 on 2024-02-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0006_auto_20240218_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('project_investigator_id', models.CharField(max_length=400)),
                ('status', models.IntegerField()),
                ('description', models.CharField(max_length=400)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='requests',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requests',
            name='description',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
