# Generated by Django 3.1.5 on 2024-03-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0007_auto_20240303_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'ordering': ['-request_id']},
        ),
        migrations.DeleteModel(
            name='project_staff_info',
        ),
    ]
