# Generated by Django 3.1.5 on 2024-02-19 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0007_auto_20240219_2309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inventory',
            new_name='rspc_inventory',
        ),
    ]
