# Generated by Django 3.1.5 on 2024-10-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0007_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uname',
            field=models.CharField(max_length=150),
        ),
    ]
