# Generated by Django 3.1.5 on 2024-10-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0008_auto_20241023_0653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='requests',
        ),
    ]
