# Generated by Django 3.1.5 on 2024-02-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0008_auto_20240219_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rspc_inventory',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
