# Generated by Django 3.1.5 on 2024-03-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0008_auto_20240306_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='project_investigator_id',
        ),
        migrations.RemoveField(
            model_name='rspc_inventory',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='rspc_inventory',
            name='project_investigator_id',
        ),
        migrations.DeleteModel(
            name='projects',
        ),
        migrations.DeleteModel(
            name='requests',
        ),
        migrations.DeleteModel(
            name='rspc_inventory',
        ),
    ]
