# Generated by Django 3.1.5 on 2024-02-20 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research_procedures', '0009_auto_20240220_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='id',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rspc_inventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requests',
            name='request_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rspc_inventory',
            name='inventory_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rspc_inventory',
            name='project_investigator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='project_staff_info',
            fields=[
                ('project_investigator_id', models.CharField(max_length=400)),
                ('staff_name', models.CharField(max_length=400)),
                ('staff_id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research_procedures.projects')),
            ],
            options={
                'unique_together': {('project_id', 'staff_id')},
            },
        ),
    ]
