# Generated by Django 3.1.5 on 2024-03-06 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research_procedures', '0009_auto_20240306_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=500)),
                ('project_type', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('sponsored_agency', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('submission_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('years', models.IntegerField()),
                ('co_project_investigator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copi_id', to=settings.AUTH_USER_MODEL)),
                ('project_investigator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-project_id'],
            },
        ),
    ]
