# Generated by Django 3.1.5 on 2024-10-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0009_delete_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='description',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='file_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='file_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
