# Generated by Django 3.1.5 on 2024-02-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0010_auto_20240220_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_staff_info',
            name='id',
            field=models.AutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='id',
            field=models.AutoField(auto_created=True, default=10, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='id',
            field=models.AutoField(auto_created=True, default=10, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rspc_inventory',
            name='id',
            field=models.AutoField(auto_created=True, default=10, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_staff_info',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='project_staff_info',
            name='project_id',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_staff_info',
            name='staff_id',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requests',
            name='request_id',
            field=models.IntegerField(verbose_name=True),
        ),
        migrations.AlterField(
            model_name='rspc_inventory',
            name='inventory_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rspc_inventory',
            name='project_investigator_id',
            field=models.CharField(default=10, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='project_staff_info',
            unique_together=set(),
        ),
    ]
