# Generated by Django 3.1.5 on 2024-11-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0010_auto_20241025_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='end_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
