# Generated by Django 3.1.5 on 2024-03-06 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research_procedures', '0010_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=500)),
                ('sub_category_name', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-category_id'],
            },
        ),
        migrations.AddField(
            model_name='projects',
            name='project_description',
            field=models.CharField(default='description', max_length=500),
        ),
        migrations.CreateModel(
            name='staff_allocations',
            fields=[
                ('staff_allocation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=500)),
                ('qualification', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('stipend', models.IntegerField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-staff_allocation_id'],
            },
        ),
        migrations.CreateModel(
            name='financial_outlay',
            fields=[
                ('financial_outlay_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=500)),
                ('sub_category', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('staff_limit', models.IntegerField(default=0)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
            ],
            options={
                'ordering': ['-financial_outlay_id'],
            },
        ),
    ]
