# Generated by Django 3.1.5 on 2024-02-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0011_auto_20240220_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_staff_info',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='id',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rspc_inventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='project_staff_info',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research_procedures.projects'),
        ),
        migrations.AlterField(
            model_name='project_staff_info',
            name='project_investigator_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project_staff_info',
            name='staff_id',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requests',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research_procedures.projects'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='project_investigator_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requests',
            name='request_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rspc_inventory',
            name='inventory_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rspc_inventory',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research_procedures.projects'),
        ),
        migrations.AlterField(
            model_name='rspc_inventory',
            name='project_investigator_id',
            field=models.CharField(max_length=500),
        ),
    ]
