# Generated by Django 3.1.5 on 2024-03-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0011_auto_20240306_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='financial_outlay_status',
            field=models.IntegerField(default=0),
        ),
    ]
