# Generated by Django 3.1.5 on 2024-11-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0011_projects_end_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
