# Generated by Django 3.1.5 on 2024-02-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0012_auto_20240220_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_staff_info',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requests',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rspc_inventory',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
