# Generated by Django 3.1.5 on 2025-03-11 00:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0012_auto_20241119_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_access',
            options={'ordering': ['-pid']},
        ),
        migrations.RenameField(
            model_name='project_access',
            old_name='id',
            new_name='aid',
        ),
        migrations.RenameField(
            model_name='project_access',
            old_name='lead_id',
            new_name='copi_id',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='deadline',
            new_name='submission_date',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='finish_date',
        ),
        migrations.AddField(
            model_name='project_access',
            name='affiliation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project_access',
            name='type',
            field=models.CharField(default='Internal', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='access',
            field=models.CharField(choices=[('Co', 'Only PI'), ('noCo', 'Either PI or Co-PI(s)')], default='noCo', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='duration',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='initial_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='scheme',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project_access',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_pis', to='research_procedures.projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('OnGoing', 'OnGoing'), ('Submitted', 'Submitted'), ('Completed', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('Research', 'Research'), ('Consultancy', 'Consultancy')], max_length=50),
        ),
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manpower', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('travel', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('contingency', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('consumables', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('equipments', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('overhead', models.IntegerField(default=0)),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='research_procedures.projects')),
            ],
        ),
    ]
