# Generated by Django 3.1.5 on 2025-03-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0013_auto_20250311_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='sanction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='sanctioned_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('OnGoing', 'OnGoing'), ('Submitted', 'Submitted'), ('Completed', 'Completed'), ('Sanctioned', 'Sanctioned')], max_length=50),
        ),
        migrations.CreateModel(
            name='staff_positions',
            fields=[
                ('spid', models.AutoField(primary_key=True, serialize=False)),
                ('positions', models.JSONField()),
                ('occupied', models.JSONField()),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='research_procedures.projects')),
            ],
        ),
    ]
