# Generated by Django 3.1.5 on 2025-03-12 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0014_auto_20250311_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='stipend',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='designation',
        ),
        migrations.AddField(
            model_name='staff',
            name='duration',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='has_funds',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='interview_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 1, 35, 37, 295144)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='post_on_website',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='selection_committee',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 1, 36, 30, 559867)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='test_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 1, 36, 38, 606111)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='test_mode',
            field=models.CharField(default='MCQ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='type',
            field=models.CharField(choices=[('Research Associate', 'Research Associate'), ('Senior Research Fellow', 'Senior Research Fellow'), ('Junior Research Fellow', 'Junior Research Fellow'), ('Supporting Staff', 'Supporting Staff'), ('Project Trainee', 'Project Trainee')], default='Research Associate', max_length=50),
            preserve_default=False,
        ),
    ]
