# Generated by Django 3.1.5 on 2025-03-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0015_auto_20250312_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_positions',
            old_name='occupied',
            new_name='incumbents',
        ),
        migrations.AddField(
            model_name='staff',
            name='interview_place',
            field=models.CharField(default='CC Hue', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='person',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
