# Generated by Django 3.1.5 on 2025-03-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0016_auto_20250312_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='id',
            new_name='sid',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='qualification',
        ),
        migrations.AddField(
            model_name='staff',
            name='biodata',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='uname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
