# Generated by Django 3.1.5 on 2025-03-13 21:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0017_auto_20250312_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='biodata',
            new_name='ad_file',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='file',
            new_name='comparative_file',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='lastdate',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='startdate',
        ),
        migrations.AddField(
            model_name='staff',
            name='biodata_final',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=''), default=list, size=None),
        ),
        migrations.AddField(
            model_name='staff',
            name='biodata_waiting',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=''), default=list, size=None),
        ),
        migrations.AddField(
            model_name='staff',
            name='candidates_applied',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='candidates_called',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='candidates_interviewed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='final_selection',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='staff',
            name='waiting_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
