# Generated by Django 3.1.5 on 2025-03-14 01:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0018_auto_20250313_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gave_verdict',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, size=None),
        ),
    ]
