# Generated by Django 3.1.5 on 2025-03-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0019_staff_gave_verdict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='rem_budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='current_funds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='end_approval',
            field=models.CharField(blank=True, choices=[('OnGoing', 'OnGoing'), ('Submitted', 'Submitted'), ('Registered', 'Registered'), ('RSPC Approval', 'RSPC Approval'), ('HoD Forward', 'HoD Forward'), ('Completed', 'Completed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='biodata_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='doc_approval',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('RSPC Approval', 'RSPC Approval'), ('HoD Forward', 'HoD Forward'), ('Hiring', 'Hiring'), ('Pending', 'Pending'), ('Committee Approval', 'Committee Approval')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='joining_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary_per_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='dept',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('SM', 'Smart Manufacturing'), ('Design', 'Design'), ('NS', 'Natural Sciences'), ('Liberal Arts', 'Liberal Arts'), ('none', 'None Of The Above')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('OnGoing', 'OnGoing'), ('Submitted', 'Submitted'), ('Registered', 'Registered'), ('RSPC Approval', 'RSPC Approval'), ('HoD Forward', 'HoD Forward'), ('Completed', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='approval',
            field=models.CharField(choices=[('Approved', 'Approved'), ('RSPC Approval', 'RSPC Approval'), ('HoD Forward', 'HoD Forward'), ('Hiring', 'Hiring'), ('Pending', 'Pending'), ('Committee Approval', 'Committee Approval')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='has_funds',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='post_on_website',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
