# Generated by Django 3.1.5 on 2025-03-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0020_auto_20250328_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='file_id',
        ),
        migrations.AddField(
            model_name='projects',
            name='registration_form',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
