# Generated by Django 3.1.5 on 2025-03-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0021_auto_20250329_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='current_approver',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='current_funds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_report',
            field=models.FileField(blank=True, null=True, upload_to='RSPC/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='RSPC/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='registration_form',
            field=models.FileField(blank=True, null=True, upload_to='RSPC/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ad_file',
            field=models.FileField(blank=True, null=True, upload_to='RSPC/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='comparative_file',
            field=models.FileField(blank=True, null=True, upload_to='RSPC/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='RSPC/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='joining_report',
            field=models.FileField(blank=True, null=True, upload_to='RSPC/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='post_on_website',
            field=models.FileField(blank=True, null=True, upload_to='RSPC/'),
        ),
    ]
