# Generated by Django 3.1.5 on 2025-03-29 13:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0022_auto_20250329_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='biodata_final',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='staff',
            name='biodata_waiting',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None),
        ),
    ]
