# Generated by Django 3.0.6 on 2020-05-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_guestroom_approval',
            name='hall_no',
            field=models.CharField(choices=[('HALL-1-BOYS', 'hall-1-boys'), ('HALL-1-GIRLS', 'hall-1-girls'), ('HALL-3', 'hall-3'), ('HALL-4', 'hall-4')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='project_closure',
            name='advances_dues',
            field=models.CharField(choices=[('Computer Graphics', 'Computer Graphics'), ('Machine Learning', 'Machine Learning'), ('Image Processing', 'Image Processing'), ('Data Structure', 'Data Structure')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project_closure',
            name='expenses_dues',
            field=models.CharField(choices=[('Computer Graphics', 'Computer Graphics'), ('Machine Learning', 'Machine Learning'), ('Image Processing', 'Image Processing'), ('Data Structure', 'Data Structure')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project_closure',
            name='others_dues',
            field=models.CharField(choices=[('Computer Graphics', 'Computer Graphics'), ('Machine Learning', 'Machine Learning'), ('Image Processing', 'Image Processing'), ('Data Structure', 'Data Structure')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project_closure',
            name='overhead_deducted',
            field=models.CharField(choices=[('Computer Graphics', 'Computer Graphics'), ('Machine Learning', 'Machine Learning'), ('Image Processing', 'Image Processing'), ('Data Structure', 'Data Structure')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project_closure',
            name='payment_dues',
            field=models.CharField(choices=[('Computer Graphics', 'Computer Graphics'), ('Machine Learning', 'Machine Learning'), ('Image Processing', 'Image Processing'), ('Data Structure', 'Data Structure')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project_closure',
            name='salary_dues',
            field=models.CharField(choices=[('Computer Graphics', 'Computer Graphics'), ('Machine Learning', 'Machine Learning'), ('Image Processing', 'Image Processing'), ('Data Structure', 'Data Structure')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project_registration',
            name='agreement',
            field=models.CharField(choices=[('Computer Graphics', 'Computer Graphics'), ('Machine Learning', 'Machine Learning'), ('Image Processing', 'Image Processing'), ('Data Structure', 'Data Structure')], default='NO', max_length=20),
        ),
    ]
