# Generated by Django 3.1.5 on 2021-04-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_module', '0002_auto_20200522_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_registration',
            name='project_type',
            field=models.CharField(choices=[('SRes', 'Sponsored Research'), ('Consultancy', 'Consultancy'), ('FIG', 'Faculty Initiation Grant'), ('Testing', 'Testing')], max_length=25),
        ),
    ]
