# Generated by Django 3.1.5 on 2026-04-17 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit_account', '0002_auto_20260413_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='anomaly_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='approval_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='budget_head',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='budget_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='request',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='current_approver_role',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='document_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='request',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='rejection_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='request',
            name='validation_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FINANCE_VALIDATED', 'Finance Validated'), ('ESCALATED', 'Escalated'), ('HOD_APPROVED', 'HoD Approved'), ('DEAN_APPROVED', 'Dean Approved'), ('DIRECTOR_APPROVED', 'Director Approved'), ('APPROVED', 'Approved'), ('PROCESSED', 'Processed'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30),
        ),
        migrations.CreateModel(
            name='TravelAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('travel_from', models.CharField(max_length=120)),
                ('travel_to', models.CharField(max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('document_names', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=30)),
                ('finance_remarks', models.TextField(blank=True)),
                ('approval_remarks', models.TextField(blank=True)),
                ('rejection_remarks', models.TextField(blank=True)),
                ('high_value', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ta_forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_workflow', models.CharField(choices=[('EXPENSE', 'Expense / Voucher'), ('TA', 'Travel Allowance'), ('AUDIT_OBSERVATION', 'Audit Observation')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True)),
                ('response_document_names', models.JSONField(blank=True, default=list)),
                ('closure_remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_observations', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_observations', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='audit_account.request')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_observation_responses', to=settings.AUTH_USER_MODEL)),
                ('travel_allowance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='audit_account.travelallowance')),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(choices=[('EXPENSE', 'Expense / Voucher'), ('TA', 'Travel Allowance'), ('AUDIT_OBSERVATION', 'Audit Observation')], max_length=30)),
                ('actor_role', models.CharField(blank=True, max_length=80)),
                ('decision', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('VALIDATED', 'Validated'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed'), ('UPDATED', 'Updated')], max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='audit_account.auditobservation')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='audit_account.request')),
                ('travel_allowance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='audit_account.travelallowance')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
