# Generated by Django 3.1.5 on 2026-04-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_account', '0003_auto_20260417_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FINANCE_VALIDATED', 'Finance Validated'), ('ESCALATED', 'Escalated'), ('VALIDATED', 'Validated'), ('HOD_APPROVED', 'HoD Approved'), ('DEAN_APPROVED', 'Dean Approved'), ('DIRECTOR_APPROVED', 'Director Approved'), ('APPROVED', 'Approved'), ('PROCESSED', 'Processed'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30),
        ),
    ]
