# Generated by Django 3.1.5 on 2026-04-18 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import applications.audit_account.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit_account", "0004_auto_20260417_2332"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentBudget",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("department", models.CharField(max_length=100)),
                ("budget_head", models.CharField(max_length=100)),
                ("allocated_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("remaining_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"unique_together": {("department", "budget_head")}},
        ),
        migrations.AddField(
            model_name="request",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="travelallowance",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="travelallowance",
            name="current_approver_role",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="travelallowance",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RequestAttachment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=applications.audit_account.models.request_attachment_path)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="audit_account.request")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="uploaded_audit_request_files", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="TravelAllowanceAttachment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=applications.audit_account.models.ta_attachment_path)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("travel_allowance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="audit_account.travelallowance")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="uploaded_audit_ta_files", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ObservationAttachment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=applications.audit_account.models.observation_attachment_path)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("attachment_kind", models.CharField(choices=[("OBSERVATION", "Observation"), ("RESPONSE", "Response")], default="OBSERVATION", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("observation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="audit_account.auditobservation")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="uploaded_audit_observation_files", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
