# Generated by Django 3.1.5 on 2026-02-17 16:19

import applications.patent_system.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=15)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patent_applicant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_applicant',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Reviewed by PCC Admin', 'Reviewed by PCC Admin'), ("Forwarded for Director's Review", "Forwarded for Director's Review"), ('Approved', 'Approved'), ('Needs Revision', 'Needs Revision'), ('Rejected', 'Rejected'), ('Resubmitted', 'Resubmitted'), ('Patentability Check Started', 'Patentability Check Started'), ('Patentability Check Completed', 'Patentability Check Completed'), ('Search Report Generated', 'Search Report Generated'), ('Patent Filed', 'Patent Filed'), ('Patent Published', 'Patent Published'), ('Patent Granted', 'Patent Granted'), ('Patent Refused', 'Patent Refused'), ('Withdrawn', 'Withdrawn'), ('Expired', 'Expired')], default='Draft', max_length=60)),
                ('decision_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Needs Revision', 'Needs Revision')], default='Pending', max_length=30)),
                ('token_no', models.CharField(blank=True, max_length=120, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('director_feedback', models.TextField(blank=True, default='')),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_pcc_date', models.DateTimeField(blank=True, null=True)),
                ('forwarded_to_director_date', models.DateTimeField(blank=True, null=True)),
                ('director_approval_date', models.DateTimeField(blank=True, null=True)),
                ('patentability_check_start_date', models.DateTimeField(blank=True, null=True)),
                ('patentability_check_completed_date', models.DateTimeField(blank=True, null=True)),
                ('search_report_generated_date', models.DateTimeField(blank=True, null=True)),
                ('patent_filed_date', models.DateTimeField(blank=True, null=True)),
                ('patent_published_date', models.DateTimeField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_date', models.DateTimeField(blank=True, null=True)),
                ('resubmission_deadline', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_patent_apps', to=settings.AUTH_USER_MODEL)),
                ('primary_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='patent_system.applicant')),
            ],
            options={
                'db_table': 'patent_system_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patent_system_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], max_length=10)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('external_party_name', models.CharField(blank=True, default='', max_length=255)),
                ('external_party_email', models.EmailField(blank=True, default='', max_length=254)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=applications.patent_system.models.communication_attachment_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='patent_system.application')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcc_comm_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_communication_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filing_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attorney_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('administrative_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('decision', models.CharField(choices=[('Pending', 'Pending'), ('Approved by PCC', 'Approved by PCC'), ('Escalated to Director', 'Escalated to Director'), ('Approved by Director', 'Approved by Director'), ('Denied', 'Denied')], default='Pending', max_length=30)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='patent_system.application')),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_budget',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('previous_state', models.CharField(blank=True, default='', max_length=60)),
                ('new_state', models.CharField(blank=True, default='', max_length=60)),
                ('details', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='patent_system.application')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationSectionIII',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=15)),
                ('development_stage', models.CharField(choices=[('Embryonic', 'Embryonic'), ('Partially developed', 'Partially developed'), ('Off-the-shelf', 'Off-the-shelf')], max_length=30)),
                ('form_iii', models.FileField(blank=True, null=True, upload_to=applications.patent_system.models.form_iii_upload_path)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_iii', to='patent_system.application')),
            ],
            options={
                'db_table': 'patent_system_application_section_iii',
            },
        ),
        migrations.CreateModel(
            name='ApplicationSectionII',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funding_details', models.TextField()),
                ('funding_source', models.TextField()),
                ('source_agreement', models.FileField(blank=True, null=True, upload_to=applications.patent_system.models.source_agreement_upload_path)),
                ('publication_details', models.TextField()),
                ('mou_details', models.TextField()),
                ('mou_file', models.FileField(blank=True, null=True, upload_to=applications.patent_system.models.mou_file_upload_path)),
                ('research_details', models.TextField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_ii', to='patent_system.application')),
            ],
            options={
                'db_table': 'patent_system_application_section_ii',
            },
        ),
        migrations.CreateModel(
            name='ApplicationSectionI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_ip', models.CharField(choices=[('Patent', 'Patent'), ('Copyright', 'Copyright'), ('Trademark', 'Trademark'), ('Industrial Design', 'Industrial Design'), ('Trade Secret', 'Trade Secret'), ('Geographical Indication', 'Geographical Indication')], default='Patent', max_length=50)),
                ('area', models.TextField()),
                ('problem', models.TextField()),
                ('objective', models.TextField()),
                ('novelty', models.TextField()),
                ('advantages', models.TextField()),
                ('is_tested', models.BooleanField(default=False)),
                ('poc_details', models.FileField(blank=True, null=True, upload_to=applications.patent_system.models.poc_file_upload_path)),
                ('applications', models.TextField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_i', to='patent_system.application')),
            ],
            options={
                'db_table': 'patent_system_application_section_i',
            },
        ),
        migrations.CreateModel(
            name='Inventor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventions', to='patent_system.applicant')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventors', to='patent_system.application')),
            ],
            options={
                'db_table': 'patent_system_inventor',
                'unique_together': {('applicant', 'application')},
            },
        ),
    ]
