# Generated by Django 3.1.5 on 2025-04-15 16:56

import applications.patent_system.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_applicant',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('token_no', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Reviewed by PCC Admin', 'Reviewed by PCC Admin'), ("Forwarded for Director's Review", "Forwarded for Director's Review"), ("Director's Approval Received", "Director's Approval Received"), ('Patentability Check Started', 'Patentability Check Started'), ('Patentability Check Completed', 'Patentability Check Completed'), ('Patentability Search Report Generated', 'Patentability Search Report Generated'), ('Patent Filed', 'Patent Filed'), ('Patent Published', 'Patent Published'), ('Patent Granted', 'Patent Granted'), ('Patent Refused', 'Patent Refused')], default='Draft', max_length=50)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('reviewed_by_pcc_date', models.DateField(blank=True, null=True)),
                ('forwarded_to_director_date', models.DateField(blank=True, null=True)),
                ('director_approval_date', models.DateField(blank=True, null=True)),
                ('patentability_check_start_date', models.DateField(blank=True, null=True)),
                ('patentability_check_completed_date', models.DateField(blank=True, null=True)),
                ('search_report_generated_date', models.DateField(blank=True, null=True)),
                ('patent_filed_date', models.DateField(blank=True, null=True)),
                ('patent_published_date', models.DateField(blank=True, null=True)),
                ('final_decision_date', models.DateField(blank=True, null=True)),
                ('decision_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patent_system_application',
            },
        ),
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('firm_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'patent_system_attorney',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssociatedWith',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patent_system.applicant')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patent_system.application')),
            ],
            options={
                'db_table': 'patent_system_associatedWith',
            },
        ),
        migrations.CreateModel(
            name='ApplicationSectionIII',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=15)),
                ('development_stage', models.CharField(choices=[('Embryonic', 'Embryonic'), ('Partially developed', 'Partially developed'), ('Off-the-shelf', 'Off-the-shelf')], max_length=30)),
                ('form_iii', models.FileField(upload_to=applications.patent_system.models.generate_form_iii_file_path)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_iii', to='patent_system.application')),
            ],
            options={
                'db_table': 'patent_system_application_section_iii',
            },
        ),
        migrations.CreateModel(
            name='ApplicationSectionII',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funding_details', models.TextField()),
                ('funding_source', models.TextField()),
                ('source_agreement', models.FileField(blank=True, null=True, upload_to=applications.patent_system.models.generate_source_agreement_file_path)),
                ('publication_details', models.TextField()),
                ('mou_details', models.TextField()),
                ('mou_file', models.FileField(blank=True, null=True, upload_to=applications.patent_system.models.generate_mou_file_path)),
                ('research_details', models.TextField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_ii', to='patent_system.application')),
            ],
            options={
                'db_table': 'patent_system_application_section_ii',
            },
        ),
        migrations.CreateModel(
            name='ApplicationSectionI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_ip', models.CharField(choices=[('Patent', 'Patent'), ('Copyright', 'Copyright'), ('Trademark', 'Trademark'), ('Industrial Design', 'Industrial Design'), ('Trade Secret', 'Trade Secret'), ('Geographical Indication', 'Geographical Indication')], default='Patent', max_length=255)),
                ('area', models.TextField()),
                ('problem', models.TextField()),
                ('objective', models.TextField()),
                ('novelty', models.TextField()),
                ('advantages', models.TextField()),
                ('is_tested', models.BooleanField(default=False)),
                ('poc_details', models.FileField(blank=True, null=True, upload_to=applications.patent_system.models.poc_file_upload_path)),
                ('applications', models.TextField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_i', to='patent_system.application')),
            ],
            options={
                'db_table': 'patent_system_application_section_i',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='attorney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='patent_system.attorney'),
        ),
        migrations.AddField(
            model_name='application',
            name='primary_applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='patent_system.applicant'),
        ),
    ]
