# Generated by Django 3.1.5 on 2025-04-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patent_system', '0001_initial'),
    ]

    operations = [
    ]
