# Generated by Django 3.1.5 on 2026-02-21 17:08

import applications.patent_system.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patent_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='confidentiality_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal', 'Internal'), ('Confidential', 'Confidential'), ('Attorney-Client Privileged', 'Attorney-Client Privileged')], default='Internal', help_text='BR-PMS-019: Confidentiality marking for legal communications.', max_length=30),
        ),
        migrations.CreateModel(
            name='PatentabilityAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assessed_by_attorney', models.CharField(blank=True, default='', help_text='Name of the external attorney who performed the assessment.', max_length=255)),
                ('novelty_score', models.DecimalField(decimal_places=2, default=0, help_text="Novelty score (0-100) as per attorney's evaluation.", max_digits=5)),
                ('non_obviousness_score', models.DecimalField(decimal_places=2, default=0, help_text='Non-obviousness score (0-100).', max_digits=5)),
                ('utility_score', models.DecimalField(decimal_places=2, default=0, help_text='Utility / industrial applicability score (0-100).', max_digits=5)),
                ('search_completeness', models.DecimalField(decimal_places=2, default=0, help_text='Prior-art search completeness percentage (0-100).', max_digits=5)),
                ('recommendation', models.CharField(choices=[('File Patent', 'File Patent'), ('Do Not File', 'Do Not File'), ('Needs Amendment', 'Needs Amendment')], default='File Patent', max_length=30)),
                ('opinion_summary', models.TextField(blank=True, default='', help_text="Summary of the attorney's patentability opinion.")),
                ('prior_art_references', models.TextField(blank=True, default='', help_text='Prior art references identified during the search.')),
                ('attorney_report', models.FileField(blank=True, help_text='Full attorney report / opinion document.', null=True, upload_to=applications.patent_system.models.assessment_report_upload_path)),
                ('assessment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patentability_assessment', to='patent_system.application')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_patentability_assessment',
            },
        ),
        migrations.CreateModel(
            name='FilingRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filing_office', models.CharField(default='Indian Patent Office', help_text='Name of the patent office where filed.', max_length=255)),
                ('jurisdiction', models.CharField(blank=True, default='India', help_text='Filing jurisdiction (e.g. India, US, PCT).', max_length=100)),
                ('external_filing_id', models.CharField(blank=True, default='', help_text='Official filing/application number from the patent office.', max_length=255)),
                ('filing_date', models.DateTimeField(blank=True, help_text='Official date of filing as recorded by the patent office.', null=True)),
                ('confirmation_proof', models.FileField(blank=True, help_text='Upload filing receipt, confirmation email screenshot, etc.', null=True, upload_to=applications.patent_system.models.filing_confirmation_upload_path)),
                ('international_filing_justification', models.TextField(blank=True, default='', help_text='BR-PMS-017: Required justification if filing outside Indian Patent Office.')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filing_record', to='patent_system.application')),
                ('filed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_patents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_filing_record',
            },
        ),
        migrations.CreateModel(
            name='AttorneyAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attorney_name', models.CharField(max_length=255)),
                ('attorney_email', models.EmailField(blank=True, default='', max_length=254)),
                ('attorney_phone', models.CharField(blank=True, default='', max_length=20)),
                ('attorney_firm', models.CharField(blank=True, default='', max_length=255)),
                ('specialization', models.CharField(blank=True, default='', help_text='Domain expertise of the attorney relevant to this application.', max_length=255)),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('engagement_proof', models.FileField(blank=True, help_text='Upload engagement letter, email screenshot, or other proof of assignment.', null=True, upload_to=applications.patent_system.models.communication_attachment_path)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attorney_assignment', to='patent_system.application')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attorney_assignments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_attorney_assignment',
            },
        ),
    ]
