# Generated by Django 3.1.5 on 2026-03-25 03:14

import applications.patent_system.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patent_system', '0002_auto_20260221_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='appeal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='appeal_decision',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='application',
            name='appeal_decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='appeal_decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='appeal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inventor',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventor',
            name='has_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Reviewed by PCC Admin', 'Reviewed by PCC Admin'), ("Forwarded for Director's Review", "Forwarded for Director's Review"), ('Approved', 'Approved'), ('Needs Revision', 'Needs Revision'), ('Rejected', 'Rejected'), ('Resubmitted', 'Resubmitted'), ('Appeal', 'Appeal'), ('Appeal Under Review', 'Appeal Under Review'), ('Appeal Approved', 'Appeal Approved'), ('Appeal Rejected', 'Appeal Rejected'), ('Patentability Check Started', 'Patentability Check Started'), ('Patentability Check Completed', 'Patentability Check Completed'), ('Search Report Generated', 'Search Report Generated'), ('Patent Filed', 'Patent Filed'), ('Patent Published', 'Patent Published'), ('Patent Granted', 'Patent Granted'), ('Patent Refused', 'Patent Refused'), ('Withdrawn', 'Withdrawn'), ('Expired', 'Expired')], default='Draft', max_length=60),
        ),
        migrations.CreateModel(
            name='PatentNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('Deadline Approaching', 'Deadline Approaching'), ('Deadline Expired', 'Deadline Expired'), ('Status Change', 'Status Change'), ('Action Required', 'Action Required'), ('Appeal Update', 'Appeal Update'), ('Consent Required', 'Consent Required'), ('Revision Requested', 'Revision Requested'), ('Application Approved', 'Application Approved'), ('Application Rejected', 'Application Rejected')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patent_system.application')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(help_text='Type of document (e.g., POC, MOU, Form III, Supporting Doc)', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=applications.patent_system.models.versioned_document_upload_path)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patent_system.application')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_application_document',
                'ordering': ['-version', '-created_at'],
                'unique_together': {('application', 'document_type', 'version')},
            },
        ),
    ]
