# Generated by Django 3.1.5 on 2026-04-18 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patent_system', '0003_auto_20260418_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=120)),
                ('action_reference', models.CharField(max_length=120)),
                ('action_summary', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patent_system_office_action',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='budget_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='budget_status',
            field=models.CharField(default='Not Initiated', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='external_filing_status',
            field=models.CharField(default='Not Initiated', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='is_revision_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='maintenance_tracking_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='priority_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='revised_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='revision_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='revision_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attorney',
            name='current_workload',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attorney',
            name='expertise_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attorney',
            name='is_panel_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patent_system.application'),
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Needs Revision', 'Needs Revision'), ('Revision Expired', 'Revision Expired'), ('Withdrawn', 'Withdrawn'), ('Reviewed by PCC Admin', 'Reviewed by PCC Admin'), ("Forwarded for Director's Review", "Forwarded for Director's Review"), ("Director's Approval Received", "Director's Approval Received"), ('Patentability Check Started', 'Patentability Check Started'), ('Patentability Check Completed', 'Patentability Check Completed'), ('Patentability Search Report Generated', 'Patentability Search Report Generated'), ('Patent Filed', 'Patent Filed'), ('Patent Published', 'Patent Published'), ('Patent Granted', 'Patent Granted'), ('Patent Refused', 'Patent Refused')], default='Draft', max_length=50),
        ),
        migrations.CreateModel(
            name='PriorArtReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(max_length=80)),
                ('citation', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prior_art_references', to='patent_system.application')),
            ],
            options={
                'db_table': 'patent_system_prior_art_reference',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeActionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('response_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='patent_system.officeaction')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_office_action_response',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='officeaction',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_actions', to='patent_system.application'),
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(blank=True, max_length=50, null=True)),
                ('event_type', models.CharField(default='General', max_length=30)),
                ('message', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_escalated', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patent_system.application')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_notification_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(default='Upcoming', max_length=20)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='patent_system.application')),
            ],
            options={
                'db_table': 'patent_system_maintenance_schedule',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='LicensingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=120)),
                ('requester_org', models.CharField(max_length=120)),
                ('request_details', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licensing_requests', to='patent_system.application')),
            ],
            options={
                'db_table': 'patent_system_licensing_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.CharField(max_length=30)),
                ('prior_art_summary', models.TextField()),
                ('recommended_action', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_assessments', to='patent_system.application')),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_assessments', to='patent_system.attorney')),
            ],
            options={
                'db_table': 'patent_system_legal_assessment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalAdviceMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_memos', to='patent_system.application')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_legal_advice_memo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventorConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_given', models.BooleanField(default=False)),
                ('agreement_reference', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patent_system.applicant')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventor_consents', to='patent_system.application')),
            ],
            options={
                'db_table': 'patent_system_inventor_consent',
            },
        ),
        migrations.CreateModel(
            name='ExternalFilingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_office', models.CharField(max_length=120)),
                ('filing_reference', models.CharField(max_length=120)),
                ('communication_notes', models.TextField(blank=True, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_filings', to='patent_system.application')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_filing_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_external_filing_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConflictDeclaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(max_length=120)),
                ('declaration_status', models.CharField(default='Declared', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_declarations', to='patent_system.application')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_conflict_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_conflict_declaration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_approvals', to='patent_system.application')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_decisions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_budget_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='patent_system.application')),
            ],
            options={
                'db_table': 'patent_system_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppealRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appellant', models.CharField(max_length=120)),
                ('grounds', models.TextField()),
                ('status', models.CharField(default='Open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='patent_system.application')),
            ],
            options={
                'db_table': 'patent_system_appeal_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='patent_system.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_system_document_version',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
