# Generated by Django 3.1.5 on 2026-03-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_system', '0003_auto_20260325_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Inventor Consent', 'Pending Inventor Consent'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Reviewed by PCC Admin', 'Reviewed by PCC Admin'), ("Forwarded for Director's Review", "Forwarded for Director's Review"), ('Approved', 'Approved'), ('Needs Revision', 'Needs Revision'), ('Rejected', 'Rejected'), ('Resubmitted', 'Resubmitted'), ('Appeal', 'Appeal'), ('Appeal Under Review', 'Appeal Under Review'), ('Appeal Approved', 'Appeal Approved'), ('Appeal Rejected', 'Appeal Rejected'), ('Patentability Check Started', 'Patentability Check Started'), ('Patentability Check Completed', 'Patentability Check Completed'), ('Search Report Generated', 'Search Report Generated'), ('Patent Filed', 'Patent Filed'), ('Patent Published', 'Patent Published'), ('Patent Granted', 'Patent Granted'), ('Patent Refused', 'Patent Refused'), ('Withdrawn', 'Withdrawn'), ('Expired', 'Expired')], default='Draft', max_length=60),
        ),
    ]
