# Generated by Django 3.1.5 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_system', '0004_auto_20260418_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attorney_review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='attorney_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(
                choices=[
                    ('Draft', 'Draft'),
                    ('Submitted', 'Submitted'),
                    ('Needs Revision', 'Needs Revision'),
                    ('Revision Expired', 'Revision Expired'),
                    ('Withdrawn', 'Withdrawn'),
                    ('Reviewed by PCC Admin', 'Reviewed by PCC Admin'),
                    ("Forwarded for Director's Review", "Forwarded for Director's Review"),
                    ("Director's Approval Received", "Director's Approval Received"),
                    ('Attorney Assigned', 'Attorney Assigned'),
                    ('Attorney Reviewed', 'Attorney Reviewed'),
                    ('Returned to Director', 'Returned to Director'),
                    ('Patentability Check Started', 'Patentability Check Started'),
                    ('Patentability Check Completed', 'Patentability Check Completed'),
                    ('Patentability Search Report Generated', 'Patentability Search Report Generated'),
                    ('Patent Filed', 'Patent Filed'),
                    ('Patent Published', 'Patent Published'),
                    ('Patent Granted', 'Patent Granted'),
                    ('Patent Refused', 'Patent Refused'),
                ],
                default='Draft',
                max_length=50,
            ),
        ),
    ]
