# Generated by Django 3.1.5 on 2026-04-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patent_system', '0005_application_attorney_review_fields_and_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_director',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='patent_director_applications',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
