# Generated by Django 3.1.5 on 2024-02-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_name',
            field=models.CharField(choices=[(0, 'Dr.Sharma'), (1, 'Dr.Vinay')], max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
