# Generated by Django 3.1.5 on 2024-04-14 03:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
        ('health_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medical_relief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
       
    ]
