# Generated by Django 3.1.5 on 2023-04-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contact_no',
            field=models.IntegerField(default=0),
        ),
    ]
