# Generated by Django 3.1.5 on 2024-04-21 17:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
        ('health_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathologist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathologist_name', models.CharField(choices=[(0, 'Dr.Ajay'), (1, 'Dr.Rahul')], max_length=50)),
                ('pathologist_phone', models.CharField(max_length=15)),
                ('specialization', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
        migrations.AddField(
            model_name='counter',
            name='patho_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_name',
            field=models.CharField(choices=[(0, 'Dr.Sharma'), (1, 'Dr.Vinay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='SpecialRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=datetime.date.today)),
                ('brief', models.CharField(default='--', max_length=20)),
                ('request_details', models.CharField(max_length=200)),
                ('upload_request', models.FileField(blank=True, upload_to='')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('remarks', models.CharField(default='--', max_length=300)),
                ('request_receiver', models.CharField(default='--', max_length=30)),
                ('request_ann_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_requests_made', to='globals.extrainfo')),
            ],
        ),
        migrations.CreateModel(
            name='Pathologist_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=10)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('room', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('pathologist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_center.pathologist')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=10)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('room', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_center.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_date', models.DateTimeField(default='04-04-2021')),
                ('message', models.CharField(max_length=200)),
                ('batch', models.CharField(default='Year-1', max_length=40)),
                ('department', models.CharField(default='ALL', max_length=40)),
                ('programme', models.CharField(max_length=10)),
                ('upload_announcement', models.FileField(default=' ', null=True, upload_to='health_center/upload_announcement')),
                ('anno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_made', to='globals.extrainfo')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_center.doctors_schedule'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
