# Generated by Django 3.1.5 on 2023-04-18 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='phone',
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_phone',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ambulance_request',
            name='reason',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_phone',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
