# Generated by Django 3.1.5 on 2024-07-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0002_auto_20240710_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_medicine',
            name='threshold',
            field=models.IntegerField(default=100),
        ),
    ]
