# Generated by Django 3.1.5 on 2024-04-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0002_auto_20240406_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiry',
            name='supplier',
            field=models.CharField(max_length=50),
        ),
    ]
