# Generated by Django 3.1.5 on 2023-04-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0002_auto_20230406_1140'),
        ('health_center', '0002_doctor_contact_no'),
    ]

    operations = [
    ]
