# Generated by Django 3.1.5 on 2024-02-18 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0002_auto_20240218_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathologist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathologist_name', models.CharField(choices=[(0, 'Dr.Ajay'), (1, 'Dr.Rahul')], max_length=50)),
                ('pathologist_phone', models.IntegerField(max_length=10)),
                ('specialization', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_name',
            field=models.CharField(choices=[(0, 'Dr.Sharma'), (1, 'Dr.Vinay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='pathologist_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health_center.pathologist'),
        ),
    ]
