# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-07 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0002_auto_20200607_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
    ]
