# Generated by Django 3.1.5 on 2023-04-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0003_merge_20230411_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance_request',
            name='reason',
            field=models.CharField(max_length=500),
        ),
    ]
