# Generated by Django 3.1.5 on 2024-07-15 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0004_auto_20240713_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_prescribed_medicine',
            name='prescription_followup_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_center.prescription_followup'),
        ),
    ]
