# Generated by Django 3.1.5 on 2023-04-16 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0004_auto_20230411_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='contact_no',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_phone',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
