# Generated by Django 3.1.5 on 2024-02-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0005_auto_20240218_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
