# Generated by Django 3.1.5 on 2024-07-17 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0005_all_prescribed_medicine_prescription_followup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_medicine',
            name='brand_name',
            field=models.CharField(default='NOT_SET', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='all_medicine',
            name='constituents',
            field=models.TextField(default='NOT_SET', null=True),
        ),
        migrations.AlterField(
            model_name='all_medicine',
            name='manufacturer_name',
            field=models.CharField(default='NOT_SET', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='all_medicine',
            name='medicine_name',
            field=models.CharField(default='NOT_SET', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='all_medicine',
            name='pack_size_label',
            field=models.CharField(default='NOT_SET', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='all_medicine',
            name='threshold',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prescription_followup',
            name='Doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_center.doctor'),
        ),
    ]
