# Generated by Django 3.1.5 on 2026-03-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0005_auto_20260324_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ambulance_requested',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
