# Generated by Django 3.1.5 on 2026-04-18 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0005_moduleaccess_database'),
        ('health_center', '0006_consultation_ambulance_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(help_text='Full name of the patient/caller being transported.', max_length=255)),
                ('destination', models.CharField(help_text='Destination hospital, clinic, or address.', max_length=500)),
                ('call_date', models.DateField(help_text='Date the ambulance was dispatched.')),
                ('call_time', models.TimeField(help_text='Time the ambulance was dispatched.')),
                ('purpose', models.TextField(blank=True, help_text='Brief description of the medical emergency or reason for dispatch.')),
                ('contact_number', models.CharField(blank=True, help_text='Contact number of the patient or caller.', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambulance', models.ForeignKey(blank=True, help_text='The specific ambulance vehicle used for this trip (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='health_center.ambulancerecordsv2')),
                ('logged_by', models.ForeignKey(blank=True, help_text='PHC Staff member who created this log entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_logs_created', to='globals.extrainfo')),
            ],
            options={
                'verbose_name': 'Ambulance Usage Log',
                'verbose_name_plural': 'Ambulance Usage Logs',
                'db_table': 'health_center_ambulance_log',
                'ordering': ['-call_date', '-call_time'],
            },
        ),
    ]
