# Generated by Django 3.1.5 on 2024-07-19 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0006_auto_20240717_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='all_prescribed_medicine',
            name='revoked_priscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revoked_priscription', to='health_center.prescription_followup'),
        ),
    ]
