# Generated by Django 3.1.5 on 2024-02-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0007_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='to_time',
        ),
    ]
