# Generated by Django 3.1.5 on 2026-04-18 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0005_moduleaccess_database'),
        ('health_center', '0007_ambulance_log_uc11'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('HEALTH_ADVISORY', 'Health Advisory'), ('SCHEDULE_CHANGE', 'Schedule Change'), ('EMERGENCY', 'Emergency'), ('VACCINATION', 'Vaccination Drive')], default='GENERAL', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to='globals.extrainfo')),
            ],
            options={
                'db_table': 'health_center_announcement',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
