# Generated by Django 3.1.5 on 2026-04-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0008_health_announcement_uc12'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='recorded_doctor_name',
            field=models.CharField(blank=True, help_text='Snapshot of doctor name preserved upon hard delete', max_length=255),
        ),
        migrations.AddField(
            model_name='consultation',
            name='recorded_doctor_name',
            field=models.CharField(blank=True, help_text='Snapshot of doctor name preserved upon hard delete', max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='recorded_doctor_name',
            field=models.CharField(blank=True, help_text='Snapshot of doctor name preserved upon hard delete', max_length=255),
        ),
    ]
