# Generated by Django 3.1.5 on 2024-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0008_auto_20240218_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
