# Generated by Django 3.1.5 on 2026-04-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0009_auto_20260419_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='issued_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='ISSUED', max_length=20),
        ),
        migrations.AlterField(
            model_name='reimbursementclaim',
            name='expense_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reimbursementclaim',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PHC_REVIEW', 'PHC Staff Review'), ('ACCOUNTS_VERIFICATION', 'Accounts Verification'), ('SANCTION_REVIEW', 'Sanction Review Required'), ('SANCTION_APPROVED', 'Sanctioned'), ('FINAL_PAYMENT', 'Final Payment Processing'), ('REIMBURSED', 'Reimbursed'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='DRAFT', max_length=30),
        ),
    ]
