# Generated by Django 3.1.5 on 2024-02-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0009_announcement_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='venue',
            new_name='title',
        ),
    ]
