# Generated by Django 3.1.5 on 2024-07-27 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0009_auto_20240721_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Required_tabel_last_updated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='all_prescribed_medicine',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_center.present_stock'),
        ),
    ]
