# Generated by Django 3.1.5 on 2024-10-15 18:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20241007_2302'),
        ('health_center', '0010_auto_20240727_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_relief',
            name='compounder_reject_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_date', models.DateTimeField(default=datetime.date.today)),
                ('message', models.CharField(max_length=200)),
                ('upload_announcement', models.FileField(default=' ', null=True, upload_to='health_center/upload_announcement')),
                ('anno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_made', to='globals.extrainfo')),
            ],
        ),
    ]
