# Generated by Django 3.1.5 on 2024-02-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0011_auto_20240221_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='patho_count',
            field=models.IntegerField(default=0),
        ),
    ]
