# Generated by Django 3.1.5 on 2024-02-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0012_counter_patho_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='pathologist_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='health_center.pathologist'),
        ),
    ]
