# Generated by Django 3.1.5 on 2024-02-21 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0013_auto_20240221_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='doctor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='health_center.doctor'),
        ),
    ]
