# Generated by Django 3.1.5 on 2024-02-22 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0014_auto_20240221_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='pathologist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_center.pathologist'),
        ),
    ]
