# Generated by Django 3.1.5 on 2024-03-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0016_medicalrelief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrelief',
            name='file',
            field=models.CharField(max_length=200),
        ),
    ]
