# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-28 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globals', '0003_auto_20191024_1242'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDA_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('adjustments_pending', 'Adjustments Pending'), ('finished', 'Finished')], max_length=20, null=True)),
                ('pf_number', models.CharField(default='', max_length=50)),
                ('purpose', models.CharField(blank=True, default='', max_length=500)),
                ('requested_advance', models.IntegerField(default='')),
                ('extra_info', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('request_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('adjustment_amount', models.IntegerField(default='')),
                ('bills_attached', models.IntegerField(blank=True, default='')),
                ('total_bills_amount', models.IntegerField(default='')),
                ('ppa_register_page_no', models.IntegerField(blank=True, default='')),
                ('adjustment_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CPDA Application',
            },
        ),
        migrations.CreateModel(
            name='CPDA_tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('application_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='establishment.CPDA_application')),
                ('current_design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globals.HoldsDesignation')),
                ('current_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.ExtraInfo')),
                ('forward_design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globals.Designation')),
                ('forward_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CPDA Tracking',
            },
        ),
    ]
