# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-29 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpda_application',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='cpda_tracking',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='cpda_tracking',
            name='current_design',
        ),
        migrations.RemoveField(
            model_name='cpda_tracking',
            name='current_id',
        ),
        migrations.RemoveField(
            model_name='cpda_tracking',
            name='forward_design',
        ),
        migrations.RemoveField(
            model_name='cpda_tracking',
            name='forward_to',
        ),
        migrations.DeleteModel(
            name='CPDA_application',
        ),
        migrations.DeleteModel(
            name='CPDA_tracking',
        ),
    ]
