# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-29 00:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globals', '0003_auto_20191024_1242'),
        ('establishment', '0002_auto_20200529_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpda_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('adjustments_pending', 'Adjustments Pending'), ('finished', 'Finished')], max_length=20, null=True)),
                ('pf_number', models.CharField(default='', max_length=50)),
                ('purpose', models.CharField(blank=True, default='', max_length=500)),
                ('requested_advance', models.IntegerField(blank=True)),
                ('request_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('adjustment_amount', models.IntegerField(blank=True, null=True)),
                ('bills_attached', models.IntegerField(blank=True, null=True)),
                ('total_bills_amount', models.IntegerField(blank=True, null=True)),
                ('ppa_register_page_no', models.IntegerField(blank=True, null=True)),
                ('adjustment_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cpda Application',
            },
        ),
        migrations.CreateModel(
            name='CPDA_bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FileField(blank=True, upload_to='')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='establishment.Cpda_application')),
            ],
            options={
                'db_table': 'Cpda Bills',
            },
        ),
        migrations.CreateModel(
            name='Cpda_tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('review_status', models.CharField(choices=[('under_review', 'Under Review'), ('reviewed', 'Reviewed')], max_length=20, null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='establishment.Cpda_application')),
                ('reviewer_design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globals.Designation')),
                ('reviewer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cpda Tracking',
            },
        ),
    ]
