# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-30 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0003_cpda_application_cpda_bills_cpda_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpda_application',
            name='adjustment_amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='cpda_application',
            name='bills_attached',
            field=models.IntegerField(blank=True, default='-1', null=True),
        ),
        migrations.AlterField(
            model_name='cpda_application',
            name='ppa_register_page_no',
            field=models.IntegerField(blank=True, default='-1', null=True),
        ),
        migrations.AlterField(
            model_name='cpda_application',
            name='total_bills_amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
