# Generated by Django 3.0.7 on 2020-07-07 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20191024_1242'),
        ('establishment', '0006_ltc_application_ltc_eligible_user_ltc_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Info',
            fields=[
                ('pf_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('joining_date', models.DateField()),
                ('joining_payscale', models.CharField(max_length=50)),
                ('is_vacational', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST')], default='', max_length=50)),
                ('pan_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('aadhar_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('local_address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('seperated', 'Seperated')], max_length=50, null=True)),
                ('spouse_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('children_info', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('personal_email_id', models.EmailField(blank=True, max_length=200, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Designation')),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Faculty')),
            ],
            options={
                'db_table': 'Faculty Information',
            },
        ),
    ]
