# Generated by Django 3.1.5 on 2021-04-22 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20191024_1242'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishment', '0007_auto_20210421_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisalrequest',
            old_name='remark',
            new_name='remark_director',
        ),
        migrations.RenameField(
            model_name='appraisalrequest',
            old_name='status',
            new_name='status_director',
        ),
        migrations.RemoveField(
            model_name='appraisalrequest',
            name='requested_from',
        ),
        migrations.AddField(
            model_name='appraisalrequest',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisalrequest',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisalrequest',
            name='remark_hod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appraisalrequest',
            name='status_hod',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('forwarded', 'Forwarded'), ('auto rejected', 'Auto Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='cpda_tracking',
            name='current_reviewer_id',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='cpda_tracking',
            name='remarks_rev1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cpda_tracking',
            name='remarks_rev2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cpda_tracking',
            name='remarks_rev3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cpda_tracking',
            name='reviewer_design2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desig2', to='globals.designation'),
        ),
        migrations.AddField(
            model_name='cpda_tracking',
            name='reviewer_design3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desig3', to='globals.designation'),
        ),
        migrations.AddField(
            model_name='cpda_tracking',
            name='reviewer_id2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cpda_tracking',
            name='reviewer_id3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appraisalrequest',
            name='appraisal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_tracking', to='establishment.appraisal'),
        ),
        migrations.AlterField(
            model_name='appraisalrequest',
            name='permission',
            field=models.CharField(blank=True, choices=[('intermediary', 'Intermediary Staff'), ('sanc_auth', 'Appraisal Sanctioning Authority'), ('sanc_off', 'Appraisal Sanctioning Officer')], default='sanc_auth', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coursesinstructed',
            name='co_instructor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cpda_tracking',
            name='reviewer_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desig1', to='globals.designation'),
        ),
        migrations.AlterField(
            model_name='cpda_tracking',
            name='reviewer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ltc_eligible_user',
            name='hometown_ltc_allowed',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='sponsoredprojects',
            name='co_investigators',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_co_investigators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thesisresearchsupervision',
            name='co_supervisors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_supervisors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Ltc_to_avail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('ltc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ltcToAvail', to='establishment.ltc_application')),
            ],
        ),
        migrations.CreateModel(
            name='Ltc_availed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('ltc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ltcAvailed', to='establishment.ltc_application')),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('depend', models.CharField(max_length=30)),
                ('ltc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dependent', to='establishment.ltc_application')),
            ],
        ),
    ]
