# Generated by Django 3.1.5 on 2021-03-27 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globals', '0003_auto_20191024_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(default='', max_length=40)),
                ('mother_name', models.CharField(default='', max_length=40)),
                ('hire_date', models.DateTimeField(max_length=6, null=True)),
                ('religion', models.CharField(default='', max_length=40)),
                ('category', models.CharField(choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('GENERAL', 'GENERAL'), ('PWD', 'PWD')], max_length=50)),
                ('cast', models.CharField(default='', max_length=40)),
                ('home_state', models.CharField(default='', max_length=40)),
                ('home_district', models.CharField(default='', max_length=40)),
                ('identification_mark', models.CharField(default='', max_length=40)),
                ('height', models.IntegerField(default=0)),
                ('date_of_joining', models.DateTimeField(max_length=6, null=True)),
                ('designation', models.CharField(default='', max_length=40)),
                ('blood_group', models.CharField(choices=[('AB+', 'AB+'), ('O+', 'O+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-')], max_length=50)),
                ('extra_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(max_length=6, null=True)),
                ('end_date', models.DateTimeField(max_length=6, null=True)),
                ('job_title', models.CharField(default='', max_length=50)),
                ('organisation', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=300)),
                ('salary_source', models.CharField(default='', max_length=100)),
                ('designation', models.CharField(default='', max_length=100)),
                ('service_type', models.CharField(choices=[('LIEN', 'LIEN'), ('DEPUTATION', 'DEPUTATION'), ('OTHER', 'OTHER')], max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr2.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmpTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(default='', max_length=40)),
                ('name', models.CharField(default='', max_length=40)),
                ('description', models.CharField(default='', max_length=100)),
                ('institute_name', models.CharField(default='', max_length=100)),
                ('from_date', models.DateTimeField(max_length=6, null=True)),
                ('to_date', models.DateTimeField(max_length=6, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr2.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmpDependents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=50)),
                ('dob', models.DateTimeField(max_length=6, null=True)),
                ('relationship', models.CharField(default='', max_length=40)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr2.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmpConfidentialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(default=0)),
                ('medical_certificate', models.FileField(blank=True, upload_to='')),
                ('age_certificate', models.FileField(blank=True, upload_to='')),
                ('cast_certificate', models.FileField(blank=True, upload_to='')),
                ('maritial_status', models.CharField(choices=[('MARRIED', 'MARRIED'), ('UN-MARRIED', 'UN-MARRIED'), ('WIDOW', 'WIDOW')], max_length=50)),
                ('bank_account_no', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr2.employee')),
            ],
        ),
    ]
