# Generated by Django 3.1.5 on 2021-03-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
    ]
