# Generated by Django 3.1.5 on 2024-10-12 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalform',
            name='employeeId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cpdaadvanceform',
            name='amountRequired',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cpdaadvanceform',
            name='employeeId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cpdaadvanceform',
            name='pfNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cpdareimbursementform',
            name='employeeId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cpdareimbursementform',
            name='pfNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='empconfidentialdetails',
            name='aadhar_no',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999999), django.core.validators.MinValueValidator(99999999999)]),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='employeeId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='pfNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='pfNo',
            field=models.IntegerField(),
        ),
    ]
