# Generated by Django 3.1.5 on 2024-02-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0002_ltcform'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltcform',
            name='approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='leave_availability',
            field=models.BooleanField(null=True),
        ),
    ]
