# Generated by Django 3.1.5 on 2025-04-13 15:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20241007_2302'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr2', '0002_auto_20241012_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePerYear',
            fields=[
                ('empid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='yearly_leave', serialize=False, to='hr2.employee')),
                ('casual_leave', models.IntegerField(default=8)),
                ('special_casual_leave', models.IntegerField(default=15)),
                ('earned_leave', models.IntegerField(default=15)),
                ('half_pay_leave', models.IntegerField(default=15)),
                ('maternity_leave', models.IntegerField(default=180)),
                ('child_care_leave', models.IntegerField(default=730)),
                ('paternity_leave', models.IntegerField(default=15)),
                ('leave_encashment', models.IntegerField(default=60)),
                ('restricted_holiday', models.IntegerField(default=2)),
            ],
        ),
        migrations.RenameField(
            model_name='leavebalance',
            old_name='casualLeave',
            new_name='casual_leave_taken',
        ),
        migrations.RenameField(
            model_name='leavebalance',
            old_name='commutedLeave',
            new_name='child_care_leave_taken',
        ),
        migrations.RenameField(
            model_name='leavebalance',
            old_name='earnedLeave',
            new_name='earned_leave_taken',
        ),
        migrations.RenameField(
            model_name='leavebalance',
            old_name='restrictedHoliday',
            new_name='half_pay_leave_taken',
        ),
        migrations.RenameField(
            model_name='leavebalance',
            old_name='specialCasualLeave',
            new_name='leave_encashment_taken',
        ),
        migrations.RenameField(
            model_name='leavebalance',
            old_name='stationLeave',
            new_name='maternity_leave_taken',
        ),
        migrations.RenameField(
            model_name='leavebalance',
            old_name='vacationLeave',
            new_name='paternity_leave_taken',
        ),
        migrations.RemoveField(
            model_name='empconfidentialdetails',
            name='aadhar_no',
        ),
        migrations.RemoveField(
            model_name='empconfidentialdetails',
            name='bank_account_no',
        ),
        migrations.RemoveField(
            model_name='empconfidentialdetails',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='empconfidentialdetails',
            name='maritial_status',
        ),
        migrations.RemoveField(
            model_name='empconfidentialdetails',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='empdependents',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='empdependents',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='empdependents',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='employeeId',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='academicResponsibility',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='addministrativeResponsibiltyAssigned',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='addressDuringLeave',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='employeeId',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='natureOfLeave',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='pfNo',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='purposeOfLeave',
        ),
        migrations.AddField(
            model_name='empconfidentialdetails',
            name='aadhar_number',
            field=models.CharField(default=123456789, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empconfidentialdetails',
            name='bank_account_number',
            field=models.CharField(default=123456789, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empconfidentialdetails',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, default=46000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empconfidentialdetails',
            name='empid',
            field=models.OneToOneField(default=5332, on_delete=django.db.models.deletion.CASCADE, related_name='confidential_details', to='hr2.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empconfidentialdetails',
            name='ifsc_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empconfidentialdetails',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Married', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empconfidentialdetails',
            name='pan_number',
            field=models.CharField(default='LGUPK458K', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empconfidentialdetails',
            name='personal_file_number',
            field=models.CharField(default='PF1234', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empdependents',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empdependents',
            name='contact_number',
            field=models.CharField(default='123456789', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empdependents',
            name='date_of_birth',
            field=models.DateField(default='26-11-2000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empdependents',
            name='empid',
            field=models.ForeignKey(default=5332, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='hr2.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empdependents',
            name='relation',
            field=models.CharField(default='FATHER', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='caste',
            field=models.CharField(default='HINDU', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default='23-11-2000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(default='9612345678', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_number',
            field=models.CharField(default='27-10-2009', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Staff', 'Staff'), ('Other', 'Other')], default='Faculty', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_address',
            field=models.TextField(default='JABALPUR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(default='xyz@company.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='1234567890', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='empid',
            field=models.OneToOneField(default=5332, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leave_balance', serialize=False, to='hr2.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='restricted_holiday_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='special_casual_leave_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='AcademicResponsibility_designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_academic_responsibility_designation', to='globals.designation'),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='AcademicResponsibility_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='AcademicResponsibility_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_responsibility_user', to='hr2.employee'),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Address_During_StationLeave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='AdministrativeResponsibility_designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_administrative_responsibility_designation', to='globals.designation'),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='AdministrativeResponsibility_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='AdministrativeResponsibility_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrative_responsibility_user', to='hr2.employee'),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='LeavingStation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Noof_CasualLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Noof_childCareLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Noof_commutedLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Noof_earnedLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Noof_halfPayLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Noof_maternityLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Noof_paternityLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Noof_restrictedHoliday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Noof_specialCasualLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Noof_vacationLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Purpose_of_leave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='StationLeave_enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='StationLeave_startdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='application_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=10),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='approved_by_designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_approved_by_designation', to='globals.designation'),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='attached_pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='attached_pdf_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='employee',
            field=models.ForeignKey(default=5332, on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='hr2.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaveform',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='first_recieved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_first_recieved_by', to='hr2.employee'),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='first_recieved_designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_first_recieved_designation', to='globals.designation'),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='personalfileNo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='cpdaadvanceform',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CPDA_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cpdareimbursementform',
            name='submissionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empconfidentialdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empdependents',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='empdependents',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empdependents',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default='23-10-2005'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_details', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_approved_by', to='hr2.employee'),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='submissionDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='LeaveClaim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('claim_date', models.DateField(default=datetime.date.today)),
                ('leaveStartDate', models.DateField(blank=True, null=True)),
                ('leaveEndDate', models.DateField(blank=True, null=True)),
                ('Noof_CasualLeave', models.IntegerField(default=0)),
                ('Noof_specialCasualLeave', models.IntegerField(default=0)),
                ('Noof_earnedLeave', models.IntegerField(default=0)),
                ('Noof_commutedLeave', models.IntegerField(default=0)),
                ('Noof_restrictedHoliday', models.IntegerField(default=0)),
                ('Noof_vacationLeave', models.IntegerField(default=0)),
                ('Noof_maternityLeave', models.IntegerField(default=0)),
                ('Noof_childCareLeave', models.IntegerField(default=0)),
                ('Noof_paternityLeave', models.IntegerField(default=0)),
                ('Noof_halfPayLeave', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approvedDate', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('attached_pdf', models.BinaryField(blank=True, null=True)),
                ('attached_pdf_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_id', models.IntegerField(blank=True, null=True)),
                ('application_type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=10)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_claim_approved_by', to='hr2.employee')),
                ('approved_by_designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_claim_approved_by_designation', to='globals.designation')),
                ('leave_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_claims', to='hr2.leaveform')),
            ],
            options={
                'verbose_name': 'Leave Claim',
                'verbose_name_plural': 'Leave Claims',
            },
        ),
    ]
