# Generated by Django 3.1.5 on 2021-05-11 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0002_workassignemnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empconfidentialdetails',
            name='aadhar_no',
            field=models.BigIntegerField(default=0, max_length=12, validators=[django.core.validators.MaxValueValidator(999999999999), django.core.validators.MinValueValidator(99999999999)]),
        ),
    ]
