# Generated by Django 3.1.5 on 2024-04-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0002_cpdaform_leaveform_ltcform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveform',
            old_name='ar_dr_ia_name',
            new_name='academic_responsibility',
        ),
        migrations.RenameField(
            model_name='leaveform',
            old_name='achievements_uploaded_date',
            new_name='application_date',
        ),
        migrations.RenameField(
            model_name='leaveform',
            old_name='ar_dr_name',
            new_name='leave_address',
        ),
        migrations.RenameField(
            model_name='leaveform',
            old_name='submission_date',
            new_name='nature_leave_end_date',
        ),
        migrations.RenameField(
            model_name='leaveform',
            old_name='dealing_asstt_ia_name',
            new_name='station_leave',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='adjusted_pda',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='advance_amount_pda',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='amount_required',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='balance_available',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='check_amount',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='copy_to',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='date_rspc_confirm',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='dealing_asstt_name',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='recomm_hod_confirm',
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Dealing_Assistant',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Deputy_Registrar',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='addministrative_responsibilty_assigned',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='application_pf_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='discipline',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='nature_leave_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='nature_of_leave',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='office_use',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='r_desgination',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='r_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='sign_dir_reg_r_desgination',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='sign_dir_reg_r_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='station_leave_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='station_leave_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='designation',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='employee_id',
            field=models.IntegerField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='purpose',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
