# Generated by Django 3.1.5 on 2026-04-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0002_add_leave_pdf_file'),
    ]

    operations = [
    ]
