# Generated by Django 3.1.5 on 2021-03-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0002_remove_employee_hire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='identification_mark',
        ),
    ]
