# Generated by Django 3.1.5 on 2024-02-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0003_auto_20240217_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ltcform',
            old_name='address_during_leave',
            new_name='addressDuringLeave',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='adjusted_month',
            new_name='adjustedMonth',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='amount_of_advance_required',
            new_name='amountOfAdvanceRequired',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='certified_advance',
            new_name='certifiedAdvance',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='certified_family_dependents',
            new_name='certifiedFamilyDependents',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='date_of_leave_for_family',
            new_name='dateOfLeaveForFamily',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='department_info',
            new_name='departmentInfo',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='details_of_dependents',
            new_name='detailsOfDependents',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='details_of_family_members',
            new_name='detailsOfFamilyMembers',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='details_of_family_members_already_done',
            new_name='detailsOfFamilyMembersAlreadyDone',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='family_members_about_to_avail',
            new_name='familyMembersAboutToAvail',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='hometown_or_not',
            new_name='hometownOrNot',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='leave_availability',
            new_name='leaveAvailability',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='leave_end_date',
            new_name='leaveEndDate',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='leave_start_date',
            new_name='leaveStartDate',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='mode_for_vacation',
            new_name='modeForVacation',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='nature_of_leave',
            new_name='natureOfLeave',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='phone_number_for_contact',
            new_name='phoneNumberForContact',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='place_of_visit',
            new_name='placeOfVisit',
        ),
        migrations.RenameField(
            model_name='ltcform',
            old_name='purpose_of_leave',
            new_name='purposeOfLeave',
        ),
    ]
