# Generated by Django 3.1.5 on 2021-03-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0003_remove_employee_identification_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdependents',
            name='dob',
            field=models.DateField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='emptraining',
            name='from_date',
            field=models.DateField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='emptraining',
            name='to_date',
            field=models.DateField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='foreignservice',
            name='end_date',
            field=models.DateField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='foreignservice',
            name='start_date',
            field=models.DateField(max_length=6, null=True),
        ),
    ]
