# Generated by Django 3.1.5 on 2024-04-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0003_auto_20240405_2311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveForm',
        ),
    ]
