# Generated by Django 3.1.5 on 2021-03-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20191024_1242'),
        ('hr2', '0004_auto_20210327_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empconfidentialdetails',
            name='employee',
        ),
        migrations.AddField(
            model_name='empconfidentialdetails',
            name='extra_info',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='globals.extrainfo'),
            preserve_default=False,
        ),
    ]
