# Generated by Django 3.1.5 on 2024-02-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0004_auto_20240218_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDAAdvanceform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('pfNo', models.IntegerField(max_length=20)),
                ('amountRequired', models.IntegerField()),
                ('purpose', models.TextField()),
                ('adjustedPDA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balanceAvailable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('advanceDueAdjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('advanceAmountPDA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amountCheckedInPDA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('submissionDate', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(null=True)),
            ],
        ),
    ]
