# Generated by Django 3.1.5 on 2024-04-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0004_delete_leaveform'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(max_length=22, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('designation', models.CharField(max_length=40, null=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('application_pf_no', models.CharField(max_length=30, null=True)),
                ('discipline', models.CharField(max_length=40, null=True)),
                ('nature_of_leave', models.CharField(max_length=40, null=True)),
                ('nature_leave_start_date', models.DateField(blank=True, null=True)),
                ('nature_leave_end_date', models.DateField(blank=True, null=True)),
                ('station_leave', models.CharField(blank=True, max_length=40, null=True)),
                ('station_leave_start_date', models.DateField(blank=True, null=True)),
                ('station_leave_end_date', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=40, null=True)),
                ('leave_address', models.CharField(blank=True, max_length=40, null=True)),
                ('academic_responsibility', models.CharField(blank=True, max_length=40, null=True)),
                ('addministrative_responsibilty_assigned', models.CharField(max_length=40, null=True)),
                ('sign_dir_reg_r_name', models.CharField(max_length=40, null=True)),
                ('sign_dir_reg_r_desgination', models.CharField(max_length=40, null=True)),
                ('office_use', models.TextField(null=True)),
                ('Dealing_Assistant', models.CharField(max_length=40, null=True)),
                ('Deputy_Registrar', models.CharField(max_length=40, null=True)),
                ('sanction_status', models.BooleanField(default=False)),
                ('r_name', models.CharField(max_length=40, null=True)),
                ('r_desgination', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
