# Generated by Django 3.1.5 on 2024-02-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0005_cpdaadvanceform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisalform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('disciplineInfo', models.CharField(max_length=50)),
                ('specificFieldOfKnowledge', models.TextField()),
                ('currentResearchInterests', models.TextField()),
                ('coursesTaught', models.JSONField()),
                ('sponsoredReseachProjects', models.JSONField()),
                ('performanceComments', models.TextField()),
                ('submissionDate', models.DateField()),
                ('approved', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CPDAReimbursementform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('pfNo', models.IntegerField(max_length=20)),
                ('advanceTaken', models.IntegerField()),
                ('purpose', models.TextField()),
                ('adjustmentSubmitted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balanceAvailable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('advanceDueAdjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('advanceAmountPDA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amountCheckedInPDA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('submissionDate', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leaveform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('departmentInfo', models.CharField(max_length=20)),
                ('leaveStartDate', models.DateField(blank=True, max_length=6, null=True)),
                ('leaveEndDate', models.DateField(blank=True, max_length=6, null=True)),
                ('natureOfLeave', models.TextField()),
                ('purposeOfLeave', models.TextField()),
                ('pfNo', models.IntegerField(max_length=50)),
                ('addressDuringLeave', models.TextField()),
                ('rolesTransferredTo', models.TextField()),
                ('submissionDate', models.DateField()),
                ('approved', models.BooleanField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ltcform',
            name='blockYear',
            field=models.TextField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ltcform',
            name='pfNo',
            field=models.IntegerField(default=12345, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpdaadvanceform',
            name='submissionDate',
            field=models.DateField(),
        ),
    ]
