# Generated by Django 3.1.5 on 2021-03-28 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20191024_1242'),
        ('hr2', '0005_auto_20210328_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empconfidentialdetails',
            name='extra_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo'),
        ),
    ]
