# Generated by Django 3.1.5 on 2021-03-28 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20191024_1242'),
        ('hr2', '0006_auto_20210328_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdependents',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='emptraining',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='foreignservice',
            name='employee',
        ),
        migrations.AddField(
            model_name='empdependents',
            name='extra_info',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emptraining',
            name='extra_info',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foreignservice',
            name='extra_info',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empconfidentialdetails',
            name='extra_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo'),
        ),
    ]
