# Generated by Django 3.1.5 on 2024-04-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0007_appraisalform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appraisalform',
        ),
    ]
