# Generated by Django 3.1.5 on 2021-03-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0007_auto_20210328_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empconfidentialdetails',
            name='age_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='empconfidentialdetails',
            name='cast_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='empconfidentialdetails',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(max_length=6, null=True),
        ),
    ]
