# Generated by Django 4.2 — HR LeaveForm fields aligned with applications.leave

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
        ("hr2", "0008_leaveform_workflow_history_leaveform_workflow_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveform",
            name="leave_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr2_leave_forms",
                to="leave.leavetype",
            ),
        ),
        migrations.AddField(
            model_name="leaveform",
            name="start_half",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leaveform",
            name="end_half",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leaveform",
            name="applied_leave_days",
            field=models.FloatField(
                blank=True,
                help_text="Working leave days computed like LeaveSegment (get_leave_days).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leaveform",
            name="leave_info",
            field=models.TextField(
                blank=True,
                help_text="Extra information (e.g. station leave details), like EmployeeCommonForm.leave_info.",
                max_length=500,
                null=True,
            ),
        ),
    ]
