# Generated by Django 3.1.5 on 2021-03-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0008_auto_20210328_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, max_length=6, null=True),
        ),
    ]
