# Generated by Django 4.2.18 on 2026-04-19 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("globals", "0005_moduleaccess_database"),
        ("hr2", "0009_leaveform_leave_type_applied_days_halves"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPDABalance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cpda_allotted",
                    models.DecimalField(
                        decimal_places=2, default=300000.0, max_digits=10
                    ),
                ),
                (
                    "cpda_used",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "employeeId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globals.extrainfo",
                    ),
                ),
            ],
        ),
    ]
