# Generated by Django 3.1.5 on 2024-04-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0009_appraisalform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisalform',
            old_name='Publication',
            new_name='publication',
        ),
    ]
