# Generated by Django 3.1.5 on 2021-03-30 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20191024_1242'),
        ('hr2', '0009_auto_20210328_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foreignservice',
            name='end_date',
            field=models.DateField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='foreignservice',
            name='extra_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo'),
        ),
        migrations.AlterField(
            model_name='foreignservice',
            name='start_date',
            field=models.DateField(blank=True, max_length=6, null=True),
        ),
    ]
