# Generated by Django 3.1.5 on 2024-04-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0010_auto_20240406_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisalform',
            old_name='sign_HOD',
            new_name='sign_hod',
        ),
    ]
