# Generated by Django 3.1.5 on 2026-05-06 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr2', '0010_cpdabalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform',
            name='workflow_status',
            field=models.CharField(choices=[('awaiting_substitutes', 'Awaiting Substitute Consent'), ('submitted', 'Submitted'), ('hod_approved', 'Approved by HOD'), ('hod_rejected', 'Rejected by HOD'), ('hr_approved', 'Approved by HR'), ('hr_rejected', 'Rejected by HR')], db_index=True, default='submitted', max_length=40),
        ),
        migrations.CreateModel(
            name='SubstituteNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility_type', models.CharField(choices=[('academic', 'Academic'), ('administrative', 'Administrative')], max_length=20)),
                ('consent_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('applicant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_nominations_sent', to=settings.AUTH_USER_MODEL)),
                ('leave_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_nominations', to='hr2.leaveform')),
                ('substitute_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('leave_form', 'substitute_user', 'responsibility_type')},
            },
        ),
    ]
