# Generated by Django 3.1.5 on 2024-04-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0011_auto_20240406_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform',
            name='office_use',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
