# Generated by Django 3.1.5 on 2021-03-31 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20191024_1242'),
        ('hr2', '0011_foreignservice_appraisal_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreignservice',
            name='appraisal_form',
        ),
        migrations.CreateModel(
            name='EmpAppraisalFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(blank=True, max_length=6, null=True)),
                ('appraisal_form', models.FileField(blank=True, null=True, upload_to='')),
                ('extra_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo')),
            ],
        ),
    ]
