# Generated by Django 3.1.5 on 2021-03-31 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20191024_1242'),
        ('hr2', '0012_auto_20210331_2221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpAppraisalFrom',
            new_name='EmpAppraisalForm',
        ),
    ]
