# Generated by Django 3.1.5 on 2021-03-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0013_auto_20210331_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empappraisalform',
            name='appraisal_form',
            field=models.FileField(default=' ', null=True, upload_to='Hr2/appraisal_form'),
        ),
    ]
