# Generated by Django 3.1.5 on 2021-04-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('source_account', models.CharField(max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.CharField(blank=True, max_length=100)),
                ('receipt', models.FileField(blank=True, upload_to='iemodule/income_receipts')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomeSource', to='income_expenditure.incomesource')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('granted_to', models.CharField(max_length=100)),
                ('expenditure_receipt', models.FileField(upload_to='iemodule/expenditure_receipts')),
                ('spent_on', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenditureType', to='income_expenditure.expendituretype')),
            ],
        ),
    ]
