# Generated by Django 3.1.5 on 2021-04-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
