# Generated by Django 3.1.5 on 2021-05-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenditure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='sub_type',
        ),
        migrations.RemoveField(
            model_name='income',
            name='sub_type',
        ),
    ]
