# Generated by Django 3.1.5 on 2021-04-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenditure', '0002_auto_20210420_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='date_added',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_added',
            field=models.DateField(),
        ),
    ]
