# Generated by Django 3.1.5 on 2021-05-12 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenditure', '0002_auto_20210512_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='expenditureSubType', to='income_expenditure.expendituresubtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='incomeSubType', to='income_expenditure.incomesubtype'),
            preserve_default=False,
        ),
    ]
