# Generated by Django 3.1.5 on 2021-04-20 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenditure', '0003_auto_20210420_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
