# Generated by Django 3.1.5 on 2021-04-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenditure', '0005_auto_20210420_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
