# Generated by Django 3.1.5 on 2021-04-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenditure', '0006_fixedattributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='granted_to',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='granted_by',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='income',
            name='source_account',
        ),
    ]
