# Generated by Django 3.1.5 on 2021-04-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenditure', '0007_auto_20210421_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balanceSheet', models.FileField(upload_to='')),
                ('date_added', models.DateField()),
            ],
        ),
    ]
