# Generated by Django 3.1.5 on 2021-04-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenditure', '0008_balancesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
