# Generated by Django 3.1.5 on 2021-04-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenditure', '0009_auto_20210421_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='date_added',
            field=models.CharField(max_length=10),
        ),
    ]
