# Generated by Django 3.1.5 on 2024-04-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='tracking_extra_JSON',
            field=models.JSONField(null=True),
        ),
    ]
