# Generated by Django 3.1.5 on 2025-05-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='subject',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
