# Generated by Django 3.1.5 on 2025-05-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetracking', '0003_auto_20250508_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
