# Generated by Django 3.1.5 on 2023-02-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentscheme',
            name='Unique Contraint 1',
        ),
        migrations.AddField(
            model_name='paymentscheme',
            name='userId',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='paymentscheme',
            constraint=models.UniqueConstraint(fields=('month', 'year', 'userId'), name='Unique Contraint 1'),
        ),
    ]
