# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-13 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentscheme',
            name='gr_reduction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentscheme',
            name='net_payment',
            field=models.IntegerField(default=0),
        ),
    ]
