# Generated by Django 3.1.5 on 2023-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0002_auto_20230205_2234'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentscheme',
            name='Unique Contraint 1',
        ),
        migrations.RemoveField(
            model_name='paymentscheme',
            name='userId',
        ),
        migrations.AddConstraint(
            model_name='paymentscheme',
            constraint=models.UniqueConstraint(fields=('month', 'year', 'pf'), name='Unique Contraint 1'),
        ),
    ]
