# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-27 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0002_auto_20200213_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Paymentss',
        ),
    ]
