# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-27 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0003_auto_20200527_2225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paymentss',
            new_name='Payments',
        ),
    ]
