# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-01 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0004_auto_20200527_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='account_no',
            new_name='Account_no',
        ),
    ]
