# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-01 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0005_auto_20200601_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Status',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
