# Generated by Django 3.0.7 on 2020-07-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0006_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentscheme',
            name='pf',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
