# Generated by Django 3.0.7 on 2020-07-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0007_auto_20200705_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentscheme',
            name='pf',
            field=models.IntegerField(null=True),
        ),
    ]
