# Generated by Django 3.0.7 on 2020-07-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0008_auto_20200705_1808'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentscheme',
            constraint=models.UniqueConstraint(fields=('month', 'year', 'pf'), name='Unique Contraint'),
        ),
    ]
