# Generated by Django 3.0.7 on 2020-07-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0009_auto_20200705_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='End_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
