# Generated by Django 3.0.7 on 2020-07-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0010_auto_20200705_2046'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentscheme',
            name='Unique Contraint',
        ),
        migrations.AddConstraint(
            model_name='paymentscheme',
            constraint=models.UniqueConstraint(fields=('month', 'year', 'pf'), name='Unique Contraint 1'),
        ),
    ]
