# Generated by Django 3.0.7 on 2020-07-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0011_auto_20200705_2217'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.UniqueConstraint(fields=('Bank_Name', 'IFSC_Code', 'Branch_Name'), name='Unique Contraint 2'),
        ),
    ]
