# Generated by Django 3.0.7 on 2020-07-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0012_auto_20200705_2225'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bank',
            name='Unique Contraint 2',
        ),
        migrations.AlterField(
            model_name='bank',
            name='Account_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='IFSC_Code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.UniqueConstraint(fields=('Bank_Name', 'Branch_Name'), name='Unique Contraint 2'),
        ),
    ]
