# Generated by Django 3.0.7 on 2020-07-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0013_auto_20200705_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Company_Name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
