# Generated by Django 3.0.7 on 2020-07-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_accounts', '0014_auto_20200705_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='TransactionId',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='TransactionId',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
