# Generated by Django 3.1.5 on 2021-05-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseslot',
            name='max_registration_limit',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='courseslot',
            name='min_registration_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='min_credit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
