# Generated by Django 3.1.5 on 2024-10-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_seats',
            field=models.IntegerField(default=90),
        ),
    ]
