# Generated by Django 3.1.5 on 2021-04-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('curriculum', 'semester_no')},
        ),
    ]
