# Generated by Django 3.1.5 on 2024-02-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0002_auto_20240215_1917'),
        ('programme_curriculum', '0002_auto_20240215_1730'),
    ]

    operations = [
    ]
