# Generated by Django 3.1.5 on 2024-02-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0002_auto_20240218_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseproposal',
            name='pre_requisit_courses',
            field=models.ManyToManyField(blank=True, to='programme_curriculum.Course'),
        ),
    ]
