# Generated by Django 3.1.5 on 2021-05-06 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0002_auto_20210502_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='evaluation_schema',
        ),
        migrations.AddField(
            model_name='batch',
            name='running_batch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='disciplines',
            field=models.ManyToManyField(blank=True, to='programme_curriculum.Discipline'),
        ),
        migrations.AddField(
            model_name='course',
            name='percent_course_attendance',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='course',
            name='percent_endsem',
            field=models.PositiveIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='course',
            name='percent_midsem',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='course',
            name='percent_project',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='course',
            name='percent_quiz_1',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='course',
            name='percent_quiz_2',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='course',
            name='pre_requisit_courses',
            field=models.ManyToManyField(blank=True, related_name='_course_pre_requisit_courses_+', to='programme_curriculum.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='working_course',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseslot',
            name='duration',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='discipline',
            name='acronym',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='programme',
            name='programme_begin_year',
            field=models.PositiveIntegerField(default=2021),
        ),
        migrations.AddField(
            model_name='semester',
            name='end_semester',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='instigate_semester',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='start_semester',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.curriculum'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='pre_requisits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseslot',
            name='courses',
            field=models.ManyToManyField(blank=True, to='programme_curriculum.Course'),
        ),
        migrations.AlterField(
            model_name='courseslot',
            name='type',
            field=models.CharField(choices=[('Professional Core', 'Professional Core'), ('Professional Elective', 'Professional Elective'), ('Professional Lab', 'Professional Lab'), ('Engineering Science', 'Engineering Science'), ('Natural Science', 'Natural Science'), ('Humanities', 'Humanities'), ('Design', 'Design'), ('Manufacturing', 'Manufacturing'), ('Management Science', 'Management Science'), ('Project', 'Project'), ('Optional', 'Optional'), ('Others', 'Others')], max_length=70),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='programmes',
            field=models.ManyToManyField(blank=True, to='programme_curriculum.Programme'),
        ),
        migrations.AlterUniqueTogether(
            name='courseslot',
            unique_together={('semester', 'name', 'type')},
        ),
    ]
