# Generated by Django 3.1.5 on 2024-04-13 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0010_auto_20240413_0145'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programme_curriculum', '0002_auto_20240413_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal_tracking',
            name='disciplines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.discipline'),
        ),
        migrations.AlterField(
            model_name='proposal_tracking',
            name='receive_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.designation'),
        ),
        migrations.AlterField(
            model_name='proposal_tracking',
            name='receive_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
