# Generated by Django 3.1.5 on 2021-04-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0002_auto_20210413_1807'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('discipline', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'name')},
        ),
    ]
