# Generated by Django 3.1.5 on 2024-03-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0002_auto_20240312_1929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'version')},
        ),
    ]
