# Generated by Django 3.1.5 on 2024-03-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0003_auto_20240312_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='latest_version',
            field=models.BooleanField(default=True),
        ),
    ]
