# Generated by Django 3.1.5 on 2026-03-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0003_fix_courseinstructor_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstructor',
            name='batch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.batch'),
        ),
    ]
