# Generated by Django 3.1.5 on 2021-04-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0003_auto_20210413_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_no',
            field=models.IntegerField(),
        ),
    ]
