# Generated by Django 3.1.5 on 2024-04-13 11:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globals', '0010_auto_20240413_0145'),
        ('programme_curriculum', '0003_auto_20240413_1035'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal_tracking',
            unique_together={('file_id', 'current_id', 'receive_id', 'receive_design')},
        ),
    ]
