# Generated by Django 3.1.5 on 2024-02-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0003_merge_20240217_1949'),
        ('programme_curriculum', '0002_auto_20240214_1323'),
    ]

    operations = [
    ]
