# Generated by Django 3.1.5 on 2024-03-13 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0004_course_latest_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='version',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.DecimalValidator(decimal_places=1, max_digits=5)]),
        ),
    ]
