# Generated by Django 3.1.5 on 2021-04-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0004_auto_20210413_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tproject_hours',
            new_name='project_hours',
        ),
    ]
