# Generated by Django 3.1.5 on 2025-02-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0004_auto_20241117_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='programme',
            name='programme_begin_year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
