# Generated by Django 3.1.5 on 2024-04-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0004_auto_20240413_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproposalfile',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
    ]
