# Generated by Django 3.1.5 on 2024-02-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0002_auto_20240216_2018'),
        ('programme_curriculum', '0004_merge_20240217_2302'),
    ]

    operations = [
    ]
