# Generated by Django 3.1.5 on 2024-02-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0004_auto_20240218_1325'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseproposal',
            unique_together={('code', 'faculty_code')},
        ),
    ]
