# Generated by Django 3.1.5 on 2021-04-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0005_auto_20210415_2041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name', 'discipline', 'year')},
        ),
    ]
