# Generated by Django 3.1.5 on 2024-02-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0004_merge_20240218_1736'),
        ('programme_curriculum', '0005_merge_20240218_2206'),
    ]

    operations = [
    ]
