# Generated by Django 3.1.5 on 2024-04-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0005_newproposalfile_is_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal_tracking',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal_tracking',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
