# Generated by Django 3.1.5 on 2024-02-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0005_auto_20240218_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseproposal',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='courseproposal',
            name='faculty_code',
            field=models.CharField(max_length=10),
        ),
    ]
