# Generated by Django 3.1.5 on 2025-03-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0005_auto_20250201_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproposalfile',
            name='max_seats',
            field=models.IntegerField(default=90),
        ),
    ]
