# Generated by Django 3.1.5 on 2025-04-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0006_newproposalfile_max_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstructor',
            name='semester_type',
            field=models.CharField(choices=[('Odd Semester', 'Odd Semester'), ('Even Semester', 'Even Semester'), ('Summer Semester', 'Summer Semester')], max_length=20, null=True),
        ),
    ]
