# Generated by Django 3.1.5 on 2024-04-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0006_auto_20240413_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='updatecourseproposal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='updatecourseproposal',
            name='disciplines',
        ),
        migrations.RemoveField(
            model_name='updatecourseproposal',
            name='pre_requisit_courses',
        ),
        migrations.AlterField(
            model_name='newproposalfile',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newproposalfile',
            name='uploader',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CourseProposal',
        ),
        migrations.DeleteModel(
            name='UpdateCourseProposal',
        ),
    ]
