# Generated by Django 3.1.5 on 2025-04-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0006_newproposalfile_max_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='version_int',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
