# Generated by Django 3.1.5 on 2021-04-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0006_auto_20210416_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.PositiveIntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='discussion_hours',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecture_hours',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='pratical_hours',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='project_hours',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutorial_hours',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='no_of_semester',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_no',
            field=models.PositiveIntegerField(),
        ),
    ]
