# Generated by Django 3.1.5 on 2025-04-21 09:01

from django.db import migrations

def populate_academic_year_and_semester_type(apps, schema_editor):
    import datetime

    CourseInstructor = apps.get_model('programme_curriculum', 'CourseInstructor')

    for ci in CourseInstructor.objects.all():
        if ci.semester_no % 2 == 1:
            ci.semester_type = "Odd Semester"
        else:
            ci.semester_type = "Even Semester"

        ci.save()

class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0007_auto_20250421_0900'),
    ]

    operations = [
        migrations.RunPython(populate_academic_year_and_semester_type),
        migrations.RemoveField(
            model_name='courseinstructor',
            name='semester_no',
        ),
    ]
