# Generated by Django 3.1.5 on 2024-02-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0007_updatecourseproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseproposal',
            name='credit',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='courseproposal',
            name='discussion_hours',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='courseproposal',
            name='lecture_hours',
            field=models.PositiveIntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='courseproposal',
            name='pratical_hours',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='courseproposal',
            name='project_hours',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='courseproposal',
            name='tutorial_hours',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
