# Generated by Django 3.1.5 on 2024-04-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0007_auto_20240414_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal_tracking',
            old_name='is_read',
            new_name='is_added',
        ),
    ]
