# Generated by Django 3.1.5 on 2025-04-04 22:01

from django.db import migrations

def move_decimal_to_int(apps, schema_editor):
    Curriculum = apps.get_model('programme_curriculum', 'Curriculum')
    for obj in Curriculum.objects.all():
        obj.version_int = int(obj.version)  # safely converts Decimal/Float to Integer
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0007_curriculum_version_int'),
    ]

    operations = [
        migrations.RunPython(move_decimal_to_int),
    ]
