# Generated by Django 3.1.5 on 2025-05-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_extrainfo_last_selected_role'),
        ('programme_curriculum', '0008_populate_semester_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseinstructor',
            unique_together={('course_id', 'instructor_id', 'year', 'semester_type')},
        ),
    ]
