# Generated by Django 3.1.5 on 2025-04-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0008_convert_version_to_integer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='version_int',
        ),
    ]
