# Generated by Django 3.1.5 on 2025-08-24 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programme_curriculum', '0009_auto_20250503_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBatchUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jee_app_no', models.CharField(help_text='JEE Application Number', max_length=50, unique=True)),
                ('roll_number', models.CharField(blank=True, help_text='Institute Roll Number', max_length=20, null=True, unique=True)),
                ('institute_email', models.EmailField(blank=True, help_text='Institute Email ID', max_length=254, null=True)),
                ('name', models.CharField(help_text='Full Name', max_length=200)),
                ('father_name', models.CharField(help_text="Father's Name", max_length=200)),
                ('mother_name', models.CharField(help_text="Mother's Name", max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'Other Backward Class'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('EWS', 'Economically Weaker Section')], max_length=10)),
                ('pwd', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', help_text='Person with Disability', max_length=3)),
                ('phone_number', models.CharField(blank=True, help_text='Mobile Number', max_length=15, null=True)),
                ('personal_email', models.EmailField(blank=True, help_text='Personal Email ID', max_length=254, null=True)),
                ('address', models.TextField(help_text='Full Address')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(help_text='Discipline/Branch', max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('ai_rank', models.IntegerField(blank=True, help_text='JEE AI Rank', null=True)),
                ('category_rank', models.IntegerField(blank=True, help_text='Category Rank', null=True)),
                ('tenth_marks', models.FloatField(blank=True, help_text='10th Class Marks (%)', null=True)),
                ('twelfth_marks', models.FloatField(blank=True, help_text='12th Class Marks (%)', null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('father_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('allotted_category', models.CharField(blank=True, max_length=10, null=True)),
                ('allotted_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.IntegerField(help_text='Academic Year')),
                ('programme_type', models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('phd', 'PhD')], max_length=10)),
                ('reported_status', models.CharField(choices=[('NOT_REPORTED', 'Not Reported'), ('REPORTED', 'Reported')], default='NOT_REPORTED', max_length=20)),
                ('password', models.CharField(blank=True, help_text='Auto-generated password', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Batch Upload',
                'verbose_name_plural': 'Student Batch Uploads',
                'ordering': ['roll_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('excel', 'Excel Upload'), ('manual', 'Manual Entry'), ('bulk', 'Bulk Import')], max_length=20)),
                ('programme_type', models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('phd', 'PhD')], max_length=10)),
                ('total_records', models.IntegerField(default=0)),
                ('successful_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload History',
                'verbose_name_plural': 'Upload History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_reported_status', models.CharField(max_length=20)),
                ('new_reported_status', models.CharField(max_length=20)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='programme_curriculum.studentbatchupload')),
            ],
            options={
                'verbose_name': 'Student Status Log',
                'verbose_name_plural': 'Student Status Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(choices=[('B.Tech', 'Bachelor of Technology'), ('B.Des', 'Bachelor of Design'), ('M.Tech', 'Master of Technology'), ('M.Des', 'Master of Design'), ('PhD', 'Doctor of Philosophy')], max_length=50)),
                ('discipline', models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Smart Manufacturing', 'Smart Manufacturing'), ('Design', 'Design')], max_length=100)),
                ('year', models.IntegerField(help_text='Academic year (e.g., 2025 for 2025-26)')),
                ('total_seats', models.IntegerField(default=60)),
                ('filled_seats', models.IntegerField(default=0, editable=False)),
                ('available_seats', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch Configuration',
                'verbose_name_plural': 'Batch Configurations',
                'ordering': ['programme', 'discipline', 'year'],
                'unique_together': {('programme', 'discipline', 'year')},
            },
        ),
        migrations.AddIndex(
            model_name='studentbatchupload',
            index=models.Index(fields=['programme_type', 'year'], name='programme_c_program_a95017_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbatchupload',
            index=models.Index(fields=['branch'], name='programme_c_branch_76eb51_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbatchupload',
            index=models.Index(fields=['reported_status'], name='programme_c_reporte_681f29_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbatchupload',
            index=models.Index(fields=['jee_app_no'], name='programme_c_jee_app_cec0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbatchupload',
            index=models.Index(fields=['roll_number'], name='programme_c_roll_nu_d6ad8b_idx'),
        ),
    ]
