# Generated by Django 3.1.5 on 2025-08-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0010_auto_20250824_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbatchupload',
            name='allotted_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentbatchupload',
            name='allotted_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
