# Generated by Django 3.1.5 on 2025-08-25 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programme_curriculum', '0011_auto_20250824_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPasswordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_initial_password', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('change_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='programme_curriculum.studentbatchupload')),
            ],
            options={
                'verbose_name': 'Student Password History',
                'verbose_name_plural': 'Student Password History',
                'db_table': 'student_password_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordEmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to_email', models.EmailField(help_text='Email address where password was sent', max_length=254)),
                ('email_status', models.CharField(choices=[('SENT', 'Successfully Sent'), ('FAILED', 'Failed to Send'), ('PENDING', 'Pending'), ('BOUNCED', 'Email Bounced')], default='PENDING', max_length=10)),
                ('password_generated', models.CharField(blank=True, help_text='The password that was generated (for audit)', max_length=100, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('email_content_preview', models.TextField(blank=True, help_text='First 200 chars of email content', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempts_count', models.IntegerField(default=1)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('sent_by', models.ForeignKey(blank=True, help_text='Admin who triggered the password email', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_emails', to='programme_curriculum.studentbatchupload')),
            ],
            options={
                'verbose_name': 'Password Email Log',
                'verbose_name_plural': 'Password Email Logs',
                'db_table': 'password_email_log',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('INITIAL_PASSWORD', 'Initial Password Email'), ('PASSWORD_RESET', 'Password Reset Email'), ('BULK_PASSWORD', 'Bulk Password Email'), ('REMINDER', 'Login Reminder Email')], max_length=20, unique=True)),
                ('subject_template', models.CharField(max_length=255)),
                ('html_template', models.TextField()),
                ('text_template', models.TextField(blank=True, null=True)),
                ('variables_info', models.JSONField(default=dict, help_text='JSON object describing available template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_template',
            },
        ),
        migrations.CreateModel(
            name='BulkPasswordEmailOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(max_length=100, unique=True)),
                ('programme_type', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('branch_filter', models.CharField(blank=True, max_length=200, null=True)),
                ('total_students', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('emails_failed', models.IntegerField(default=0)),
                ('emails_pending', models.IntegerField(default=0)),
                ('operation_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=15)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Password Email Operation',
                'verbose_name_plural': 'Bulk Password Email Operations',
                'db_table': 'bulk_password_email_operation',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='passwordemaillog',
            index=models.Index(fields=['email_status'], name='password_em_email_s_0aff1d_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordemaillog',
            index=models.Index(fields=['sent_at'], name='password_em_sent_at_a4c3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordemaillog',
            index=models.Index(fields=['student'], name='password_em_student_6e6088_idx'),
        ),
    ]
