# Generated by Django 3.1.5 on 2025-08-25 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programme_curriculum', '0012_add_password_email_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbatchupload',
            name='password',
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentbatchupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
