# Generated by Django 3.1.5 on 2025-08-25 20:48

import applications.programme_curriculum.models_student_management
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programme_curriculum', '0013_remove_password_field_add_user_link'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentbatchupload',
            name='programme_c_program_a95017_idx',
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='academic_year',
            field=models.CharField(blank=True, db_column='academic_year', help_text='Academic Year String (e.g., 2025-26)', max_length=20),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='allocation_status',
            field=models.CharField(default='ALLOCATED', help_text='Allocation Status', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentbatchupload',
            name='ai_rank',
            field=models.IntegerField(blank=True, db_column='jee_rank', help_text='JEE AI Rank', null=True),
        ),
        migrations.AlterField(
            model_name='studentbatchupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentbatchupload',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentbatchupload',
            name='year',
            field=models.IntegerField(db_column='batch_year', default=applications.programme_curriculum.models_student_management.get_current_academic_year, help_text='Academic Year'),
        ),
        migrations.AddIndex(
            model_name='studentbatchupload',
            index=models.Index(fields=['programme_type', 'year'], name='programme_c_program_8a36dc_idx'),
        ),
    ]
