# Generated by Django 3.1.5 on 2025-08-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0014_auto_20250825_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbatchupload',
            name='email_password',
            field=models.CharField(blank=True, help_text='Temporary storage for email notification', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='password_email_sent',
            field=models.BooleanField(default=False, help_text='Whether password email has been sent'),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='password_generated_at',
            field=models.DateTimeField(blank=True, help_text='When password was generated', null=True),
        ),
    ]
