# Generated by Django 3.1.5 on 2025-08-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0015_add_email_password_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
