# Generated by Django 3.1.5 on 2025-08-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0016_batch_total_seats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('name', 'programme', 'version')},
        ),
    ]
