# Generated by Django 3.1.5 on 2025-08-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0017_fix_curriculum_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbatchupload',
            name='source',
            field=models.CharField(default='admin_upload', help_text='Source of student data (admin_upload, excel_upload, manual_entry, etc.)', max_length=50),
        ),
    ]
