# Generated by Django 3.1.5 on 2025-08-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0018_studentbatchupload_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbatchupload',
            name='source',
        ),
        migrations.AlterField(
            model_name='studentbatchupload',
            name='reported_status',
            field=models.CharField(choices=[('NOT_REPORTED', 'Not Reported'), ('REPORTED', 'Reported'), ('WITHDRAWAL', 'Withdrawal')], default='NOT_REPORTED', max_length=20),
        ),
    ]
