# Generated by Django 3.1.5 on 2025-08-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0019_add_withdrawal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='total_seats',
        ),
        migrations.AlterField(
            model_name='studentbatchupload',
            name='reported_status',
            field=models.CharField(choices=[('NOT_REPORTED', 'Not Reported'), ('REPORTED', 'Reported')], default='NOT_REPORTED', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('name', 'version')},
        ),
    ]
