# Generated by Django 3.1.5 on 2025-08-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0020_auto_20250830_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbatchupload',
            name='source',
            field=models.CharField(default='admin_upload', help_text='Source of student data (admin_upload, excel_upload, manual_entry, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentbatchupload',
            name='reported_status',
            field=models.CharField(choices=[('NOT_REPORTED', 'Not Reported'), ('REPORTED', 'Reported'), ('WITHDRAWAL', 'Withdrawal')], default='NOT_REPORTED', max_length=20),
        ),
    ]
