# Generated by Django 3.1.5 on 2025-08-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0021_auto_20250830_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='total_seats',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
