# Generated by Django 3.1.5 on 2025-08-30 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programme_curriculum', '0022_batch_total_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], default='UPDATE', max_length=20)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(default=list)),
                ('version_bump_type', models.CharField(choices=[('NONE', 'No Version Bump'), ('PATCH', 'Patch (0.0.1)'), ('MINOR', 'Minor (0.1.0)'), ('MAJOR', 'Major (1.0.0)')], default='NONE', max_length=10)),
                ('old_version', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('new_version', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('admin_override', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='programme_curriculum.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
