# Generated by Django 3.1.5 on 2025-09-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0023_courseauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbatchupload',
            name='minority',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', help_text='Minority Status', max_length=3),
        ),
    ]
