# Generated by Django 3.1.5 on 2025-09-02 16:53

from django.db import migrations, models


def update_minority_values(apps, schema_editor):
    """Convert existing YES/NO values to Applicable/Not Applicable"""
    StudentBatchUpload = apps.get_model('programme_curriculum', 'StudentBatchUpload')
    
    # Update YES to Applicable
    StudentBatchUpload.objects.filter(minority='YES').update(minority='Applicable')
    
    # Update NO to Not Applicable
    StudentBatchUpload.objects.filter(minority='NO').update(minority='Not Applicable')


def reverse_minority_values(apps, schema_editor):
    """Reverse the migration: convert back to YES/NO"""
    StudentBatchUpload = apps.get_model('programme_curriculum', 'StudentBatchUpload')
    
    # Update Applicable to YES
    StudentBatchUpload.objects.filter(minority='Applicable').update(minority='YES')
    
    # Update Not Applicable to NO
    StudentBatchUpload.objects.filter(minority='Not Applicable').update(minority='NO')


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0024_add_minority_field'),
    ]

    operations = [
        # First, increase field length to accommodate longer values
        migrations.AlterField(
            model_name='studentbatchupload',
            name='minority',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('Applicable', 'Applicable'), ('Not Applicable', 'Not Applicable')], default='NO', help_text='Minority Status', max_length=20),
        ),
        
        # Then update the data
        migrations.RunPython(update_minority_values, reverse_minority_values),
        
        # Finally, update the field with the new choices and default
        migrations.AlterField(
            model_name='studentbatchupload',
            name='minority',
            field=models.CharField(choices=[('Applicable', 'Applicable'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', help_text='Minority Status', max_length=20),
        ),
    ]
