# Generated by Django 3.1.5 on 2025-09-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0026_add_database_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbatchupload',
            name='minority',
            field=models.TextField(blank=True, help_text='Minority Status (e.g., Muslim, Christian, Sikh, Buddhist, Jain, Parsi, etc.)', null=True),
        ),
    ]
