# Generated by Django 3.1.5 on 2025-11-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0027_auto_20250918_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbatchupload',
            name='admission_mode',
            field=models.CharField(blank=True, choices=[('JEE Main', 'JEE Main'), ('JEE Advanced', 'JEE Advanced'), ('GATE', 'GATE'), ('DASA', 'DASA'), ('Foreign National', 'Foreign National'), ('Sponsored', 'Sponsored'), ('Any other (remarks)', 'Any other (remarks)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='admission_mode_remarks',
            field=models.TextField(blank=True, help_text="Required when admission mode is 'Any other (remarks)'", null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='blood_group_remarks',
            field=models.TextField(blank=True, help_text="Blood group remarks when 'Other' is selected", null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual family income', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='income_group',
            field=models.CharField(blank=True, choices=[('Below 1 Lakh', 'Below 1 Lakh'), ('1-2.5 Lakhs', '1-2.5 Lakhs'), ('2.5-5 Lakhs', '2.5-5 Lakhs'), ('5-8 Lakhs', '5-8 Lakhs'), ('Above 8 Lakhs', 'Above 8 Lakhs')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='nationality',
            field=models.CharField(blank=True, default='Indian', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='Parent Email ID', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='pwd_category',
            field=models.CharField(blank=True, choices=[('Locomotor Disability', 'Locomotor Disability'), ('Visual Impairment', 'Visual Impairment'), ('Hearing Impairment', 'Hearing Impairment'), ('Speech and Language Disability', 'Speech and Language Disability'), ('Intellectual Disability', 'Intellectual Disability'), ('Autism Spectrum Disorder', 'Autism Spectrum Disorder'), ('Multiple Disabilities', 'Multiple Disabilities'), ('Any other (remarks)', 'Any other (remarks)')], help_text='Required when PWD is YES', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='pwd_category_remarks',
            field=models.TextField(blank=True, help_text="Required when PWD category is 'Any other (remarks)'", null=True),
        ),
    ]
