# Generated by Django 3.1.5 on 2025-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0028_add_new_student_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbatchupload',
            name='allotted_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentbatchupload',
            name='allotted_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
