# Generated by Django 3.1.5 on 2025-11-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0029_increase_allotted_field_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbatchupload',
            name='specialization',
            field=models.CharField(blank=True, help_text='Specialization', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentbatchupload',
            name='jee_app_no',
            field=models.CharField(help_text='JEE App. No./CCMT Roll. No.', max_length=50, unique=True),
        ),
    ]
