# Generated by Django 3.1.5 on 2025-11-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0030_add_specialization_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='curriculum_options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
