# Generated by Django 3.1.5 on 2026-07-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0032_auto_20260210_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstructor',
            name='section_label',
            field=models.CharField(blank=True, help_text='Section (A-F) this offering teaches; blank for a single-offering elective.', max_length=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='courseinstructor',
            unique_together={('course_id', 'year', 'semester_type', 'section_label')},
        ),
    ]
