# Generated by Django 3.1.5 on 2026-07-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0033_auto_20260704_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbatchupload',
            name='section',
            field=models.CharField(blank=True, help_text='B.Tech section (A-F), auto-derived at save from discipline + roll-number parity', max_length=2, null=True),
        ),
    ]
