# Generated by Django 3.1.5 on 2026-02-11 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0034_progressseminar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Professional Core', 'Professional Core'), ('Professional Elective', 'Professional Elective'), ('Professional Lab', 'Professional Lab'), ('Engineering Science', 'Engineering Science'), ('Natural Science', 'Natural Science'), ('Humanities', 'Humanities'), ('Design', 'Design'), ('Manufacturing', 'Manufacturing'), ('Management Science', 'Management Science'), ('Open Elective', 'Open Elective'), ('Swayam', 'Swayam'), ('Project', 'Project'), ('Optional', 'Optional'), ('Backlog', 'Backlog'), ('Others', 'Others')], max_length=70)),
                ('thesis_slot_info', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=1)),
                ('min_registration_limit', models.PositiveIntegerField(default=0)),
                ('max_registration_limit', models.PositiveIntegerField(default=1000)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.semester')),
                ('theses', models.ManyToManyField(blank=True, to='programme_curriculum.Thesis')),
            ],
            options={
                'unique_together': {('semester', 'name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ProgressSeminarSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Professional Core', 'Professional Core'), ('Professional Elective', 'Professional Elective'), ('Professional Lab', 'Professional Lab'), ('Engineering Science', 'Engineering Science'), ('Natural Science', 'Natural Science'), ('Humanities', 'Humanities'), ('Design', 'Design'), ('Manufacturing', 'Manufacturing'), ('Management Science', 'Management Science'), ('Open Elective', 'Open Elective'), ('Swayam', 'Swayam'), ('Project', 'Project'), ('Optional', 'Optional'), ('Backlog', 'Backlog'), ('Others', 'Others')], max_length=70)),
                ('progress_seminar_slot_info', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=1)),
                ('min_registration_limit', models.PositiveIntegerField(default=0)),
                ('max_registration_limit', models.PositiveIntegerField(default=1000)),
                ('progress_seminars', models.ManyToManyField(blank=True, to='programme_curriculum.ProgressSeminar')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.semester')),
            ],
            options={
                'unique_together': {('semester', 'name', 'type')},
            },
        ),
    ]
