# Generated by Django 3.1.5 on 2026-03-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0037_phd_student_missing_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='phdstudentbatchupload',
            name='phd_stud_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='phdstudentbatchupload',
            name='phd_stud_disc_idx',
        ),
        migrations.RemoveIndex(
            model_name='phdstudentbatchupload',
            name='phd_stud_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='phdstudentbatchupload',
            name='phd_stud_sem_idx',
        ),
        migrations.RemoveIndex(
            model_name='phdstudentbatchupload',
            name='phd_stud_appno_idx',
        ),
        migrations.RemoveIndex(
            model_name='phdstudentbatchupload',
            name='phd_stud_roll_idx',
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Academic Year String (e.g., 2025-26)', max_length=20),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='admission_semester',
            field=models.CharField(blank=True, choices=[('Odd', 'Odd Semester'), ('Even', 'Even Semester')], help_text='Semester of PhD admission: Odd or Even', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='admission_type',
            field=models.CharField(blank=True, choices=[('FULL TIME with Institute Assistantship', 'FULL TIME with Institute Assistantship'), ('FULL TIME with Govt. / Semi Govt. Fellowship Award', 'FULL TIME with Govt. / Semi Govt. Fellowship Award'), ('FULL TIME Self Financed', 'FULL TIME Self Financed'), ('PART TIME (External)', 'PART TIME (External)'), ('QIP', 'QIP'), ('Any other (remarks)', 'Any other (remarks)')], help_text='Admission Type (col: Admission Type)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='allotted_category',
            field=models.CharField(blank=True, help_text='allottedcat', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='discipline',
            field=models.CharField(help_text='Discipline / Branch (col: Discipline)', max_length=200),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='gate_qualified',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], help_text='GATE Qualified (col: GATE Qualaified)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='gate_rank',
            field=models.IntegerField(blank=True, help_text='GATE Rank (col: GATE Rank)', null=True),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='gate_stream',
            field=models.CharField(blank=True, help_text='GATE Stream (col: GATE Stream)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='institute_email',
            field=models.EmailField(blank=True, help_text='Institute Email ID (col: Institute Email ID)', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='minority',
            field=models.TextField(blank=True, help_text='Minority Status (col: Minority)', null=True),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='name',
            field=models.CharField(help_text='Full Name (col: Name)', max_length=200),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='Parent Email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Alternate Email ID', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='phone_number',
            field=models.CharField(blank=True, help_text='MobileNo', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='roll_number',
            field=models.CharField(blank=True, help_text='Institute Roll Number (col: Institute Roll Number)', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phdstudentbatchupload',
            name='source',
            field=models.CharField(default='admin_upload', help_text='Source of data: excel_upload, manual_entry, etc.', max_length=50),
        ),
        migrations.AddIndex(
            model_name='phdstudentbatchupload',
            index=models.Index(fields=['year'], name='programme_c_batch_y_c985fe_idx'),
        ),
        migrations.AddIndex(
            model_name='phdstudentbatchupload',
            index=models.Index(fields=['discipline'], name='programme_c_discipl_72ce54_idx'),
        ),
        migrations.AddIndex(
            model_name='phdstudentbatchupload',
            index=models.Index(fields=['reported_status'], name='programme_c_reporte_7022dd_idx'),
        ),
        migrations.AddIndex(
            model_name='phdstudentbatchupload',
            index=models.Index(fields=['admission_semester'], name='programme_c_admissi_a286bd_idx'),
        ),
        migrations.AddIndex(
            model_name='phdstudentbatchupload',
            index=models.Index(fields=['application_no'], name='programme_c_applica_e9ceaf_idx'),
        ),
        migrations.AddIndex(
            model_name='phdstudentbatchupload',
            index=models.Index(fields=['roll_number'], name='programme_c_roll_nu_64bfc6_idx'),
        ),
    ]
