# Generated by Django 3.1.5 on 2026-03-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0038_thesis_registration_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressseminarslot',
            name='type',
            field=models.CharField(choices=[('Thesis', 'Thesis'), ('Progress Seminar', 'Progress Seminar'), ('Teaching Credit', 'Teaching Credit')], max_length=70),
        ),
        migrations.AlterField(
            model_name='thesisslot',
            name='type',
            field=models.CharField(choices=[('Thesis', 'Thesis'), ('Progress Seminar', 'Progress Seminar'), ('Teaching Credit', 'Teaching Credit')], max_length=70),
        ),
    ]
