# Generated by Django 3.1.5 on 2026-03-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0039_auto_20260306_1157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progressseminarslot',
            unique_together={('semester', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='thesisslot',
            unique_together={('semester', 'name')},
        ),
        migrations.RemoveField(
            model_name='progressseminarslot',
            name='type',
        ),
        migrations.RemoveField(
            model_name='thesisslot',
            name='type',
        ),
    ]
