# Generated by Django 3.1.5 on 2026-03-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0032_auto_20260210_1820'),
        ('programme_curriculum', '0040_remove_type_from_thesis_and_ps_slots'),
    ]

    operations = [
    ]
