# Generated by Django 3.1.5 on 2026-08-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0034_studentbatchupload_section'),
        ('programme_curriculum', '0041_merge_20260314_1604'),
    ]

    operations = [
    ]
