# Generated by Django 3.1.5 on 2026-08-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0042_merge_20260805_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('M.Tech AI & ML', 'M.Tech AI & ML'), ('M.Tech Data Science', 'M.Tech Data Science'), ('M.Tech Communication and Signal Processing', 'M.Tech Communication and Signal Processing'), ('M.Tech Nanoelectronics and VLSI Design', 'M.Tech Nanoelectronics and VLSI Design'), ('M.Tech Power & Control', 'M.Tech Power & Control'), ('M.Tech Design', 'M.Tech Design'), ('M.Tech CAD/CAM', 'M.Tech CAD/CAM'), ('M.Tech Manufacturing and Automation', 'M.Tech Manufacturing and Automation'), ('B.Des', 'B.Des'), ('M.Des', 'M.Des'), ('PhD (Odd)', 'PhD (Odd)'), ('PhD (Even)', 'PhD (Even)')], max_length=50),
        ),
    ]
