# Generated by Django 3.1.5 on 2026-07-09 10:47

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0042_auto_20260410_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseauditlog',
            name='new_values',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='courseauditlog',
            name='old_values',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
