# Generated by Django 3.1.5 on 2026-07-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0043_courseauditlog_json_encoder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('programme_type', models.CharField(choices=[('PG', 'Postgraduate'), ('PHD', 'Doctor of Philosophy')], max_length=3)),
                ('working_teaching_credit', models.BooleanField(default=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.discipline')),
            ],
            options={
                'unique_together': {('code', 'discipline')},
            },
        ),
        migrations.CreateModel(
            name='TeachingCreditSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teaching_credit_slot_info', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=1)),
                ('min_registration_limit', models.PositiveIntegerField(default=0)),
                ('max_registration_limit', models.PositiveIntegerField(default=1000)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.semester')),
                ('teaching_credits', models.ManyToManyField(blank=True, to='programme_curriculum.TeachingCredit')),
            ],
            options={
                'unique_together': {('semester', 'name')},
            },
        ),
    ]
