# Generated by Django 3.1.5 on 2026-08-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0046_thesisslot_evaluation_type'),
        ('programme_curriculum', '0034_studentbatchupload_section'),
    ]

    operations = [
    ]
