# Generated by Django 3.1.5 on 2026-08-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0043_auto_20260805_2217'),
        ('programme_curriculum', '0047_merge_20260804_2335'),
    ]

    operations = [
    ]
