# Generated by Django 3.1.5 on 2026-08-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0048_merge_20260805_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdstudentbatchupload',
            name='hindi_name',
            field=models.CharField(blank=True, help_text='Full Name in Hindi', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phdstudentbatchupload',
            name='photo',
            field=models.ImageField(blank=True, help_text='Passport photo (max 200KB)', null=True, upload_to='programme_curriculum/student_photos'),
        ),
        migrations.AddField(
            model_name='phdstudentbatchupload',
            name='signature',
            field=models.ImageField(blank=True, help_text='Signature image (max 30KB)', null=True, upload_to='programme_curriculum/student_signatures'),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='hindi_name',
            field=models.CharField(blank=True, help_text='Full Name in Hindi', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='photo',
            field=models.ImageField(blank=True, help_text='Passport photo (max 200KB)', null=True, upload_to='programme_curriculum/student_photos'),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='signature',
            field=models.ImageField(blank=True, help_text='Signature image (max 30KB)', null=True, upload_to='programme_curriculum/student_signatures'),
        ),
    ]
