# Generated by Django 3.1.5 on 2026-08-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0049_auto_20260812_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdstudentbatchupload',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='True once the student submits the first-login profile-completion popup'),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='True once the student submits the first-login profile-completion popup'),
        ),
    ]
