# Generated by Django 3.1.5 on 2026-08-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0050_auto_20260813_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdstudentbatchupload',
            name='photo_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phdstudentbatchupload',
            name='photo_mime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phdstudentbatchupload',
            name='signature_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phdstudentbatchupload',
            name='signature_mime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='photo_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='photo_mime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='signature_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='signature_mime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
