# Generated by Django 3.1.5 on 2026-08-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0051_auto_20260813_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdstudentbatchupload',
            name='apaar_id',
            field=models.CharField(blank=True, help_text='APAAR ID (12 digits), collected at first login', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='studentbatchupload',
            name='apaar_id',
            field=models.CharField(blank=True, help_text='APAAR ID (12 digits), collected at first login', max_length=12, null=True),
        ),
    ]
