# Generated by Django 3.1.5 on 2026-08-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0052_student_apaar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstructor',
            name='section_label',
            field=models.CharField(blank=True, help_text='Section this offering teaches; blank for a single-offering elective.', max_length=8, null=True),
        ),
    ]
