# Generated by Django 3.1.5 on 2026-10-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0056_student_joining_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name', 'discipline', 'year', 'curriculum')},
        ),
    ]
