# Generated by Django 4.2.29 on 2026-03-15 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('Leave Module', 'Leave Module'), ('Placement Cell', 'Placement Cell'), ("Academic's Module", "Academic's Module"), ('Central Mess', 'Central Mess'), ("Visitor's Hostel", "Visitor's Hostel"), ('Healthcare Center', 'Healthcare Center'), ('File Tracking', 'File Tracking'), ('Scholarship Portal', 'Scholarship Portal'), ('Complaint System', 'Complaint System'), ('Office of Dean PnD Module', 'Office of Dean PnD Module'), ('Office Module', 'Office Module'), ('Gymkhana Module', 'Gymkhana Module'), ('Assistantship Request', 'Assistantship Request'), ('department', 'Department'), ('Research Procedures', 'Research Procedures')], max_length=60)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
