# Generated by Django 4.2.29 on 2026-03-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_extension', '0002_notificationeventtype_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationeventtype',
            name='default_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
    ]
