# Generated by Django 4.2.29 on 2026-03-29 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications_extension', '0003_alter_notificationeventtype_default_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.IntegerField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived Notification',
                'unique_together': {('user', 'notification_id')},
            },
        ),
    ]
