# Generated by Django 4.2.29 on 2026-04-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_extension', '0004_archivednotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalsDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=30)),
                ('basic', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'globals_designation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalsExtraInfo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'globals_extrainfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalsHoldsDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_id', models.IntegerField()),
                ('held_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'globals_holdsdesignation',
                'managed': False,
            },
        ),
    ]
