# Generated by Django 4.2.29 on 2026-04-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_extension', '0005_globalsdesignation_globalsextrainfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='audience_type',
            field=models.CharField(choices=[('all', 'All Users'), ('students', 'All Students'), ('faculty', 'All Faculty'), ('staff', 'All Staff'), ('group', 'Specific Designation'), ('department', 'By Department'), ('batch', 'By Batch')], default='all', max_length=20),
        ),
    ]
