# Generated by Django 3.1.5 on 2026-04-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_extension', '0007_auto_20260425_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='audience_type',
            field=models.CharField(choices=[('all', 'All Users'), ('students', 'All Students'), ('faculty', 'All Faculty'), ('staff', 'All Staff'), ('group', 'Specific Designation'), ('department', 'By Department'), ('batch', 'By Batch'), ('specific_user', 'Specific User')], default='all', max_length=20),
        ),
    ]
