# Generated by Django 3.1.5 on 2026-04-26 13:10

from django.db import migrations, models
import uuid


def backfill_approval_id(apps, schema_editor):
    """Give every existing Announcement a unique UUID before the unique constraint is added."""
    Announcement = apps.get_model("notifications_extension", "Announcement")
    for ann in Announcement.objects.all():
        ann.approval_id = uuid.uuid4()
        ann.save(update_fields=["approval_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_extension', '0008_auto_20260426_1221'),
    ]

    operations = [
        # Step 1: add field WITHOUT unique constraint, allow temp duplicates
        migrations.AddField(
            model_name='announcement',
            name='approval_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: backfill each row with a fresh UUID
        migrations.RunPython(backfill_approval_id, migrations.RunPython.noop),
        # Step 3: now apply the unique constraint
        migrations.AlterField(
            model_name='announcement',
            name='approval_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
