from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('page1-1/', views.page1_1, name='page1_1'),
    path('aes-form/', views.AESForm, name='AESForm'),
    path('page2-1/', views.page2_1, name='page2_1'),
    path('corrigendum-input/', views.corrigendumInput, name='corrigendumInput'),
    path('addendum-input/', views.addendumInput, name='addendumInput'),
    path('pre-bid-form/', views.PreBidForm, name='PreBidForm'),
    path('no-of-entries-technical-bid/', views.noOfEntriesTechnicalBid, name='noOfEntriesTechnicalBid'),
    path('technical-bid-form/', views.TechnicalBidForm, name='TechnicalBidForm'),
    path('no-of-entries-financial-bid/', views.noOfEntriesFinancialBid, name='noOfEntriesFinancialBid'),
    path('letter-of-intent/', views.letterOfIntent, name='letterOfIntent'),
    path('work-order-form/', views.workOrderForm, name='workOrderForm'),
    path('agreement-input/', views.AgreementInput, name='AgreementInput'),
    path('milestones-form/', views.milestonesForm, name='milestonesForm'),
    path('page3-1/', views.page3_1, name='page3_1'),
    path('extension-of-time-form/', views.ExtensionOfTimeForm, name='ExtensionOfTimeForm'),
    path('page1-view/', views.page1View, name='page1View'),
    path('page2-view/', views.page2View, name='page2View'),
    path('aes-view/', views.AESView, name='AESView'),
    path('financial-bid-view/', views.financialBidView, name='financialBidView'),
    path('technical-bid-view/', views.technicalBidView, name='technicalBidView'),
    path('pre-bid-details-view/', views.preBidDetailsView, name='preBidDetailsView'),
    path('corrigendum-view/', views.corrigendumView, name='corrigendumView'),
    path('addendum-view/', views.addendumView, name='addendumView'),
    path('letter-of-intent-view/', views.letterOfIntentView, name='letterOfIntentView'),
    path('work-order-form-view/', views.workOrderFormView, name='workOrderFormView'),
    path('agreement-view/', views.agreementView, name='agreementView'),
    path('milestone-view/', views.milestoneView, name='milestoneView'),
    path('page3-view/', views.page3View, name='page3View'),
    path('extension-form-view/', views.extensionFormView, name='extensionFormView'),
    path('fetch-designations/', views.fetchDesignations, name='fetchDesignations'),
    path('requests-view/', views.requestsView, name='requestsView'),
    path('created-requests-view/', views.created_requests_view, name='createdRequests'),
    path('view-file/', views.view_file_api, name='viewFile'),
    path('handle-engineer-process-requests/', views.handleEngineerProcessRequests, name='handleEngineerProcessRequests'),
    path('rejected-requests-view/', views.rejectedRequests, name='rejectedRequests'),
    path('update-rejected-requests/', views.updateRejectedRequests, name='updateRejectedRequests'),
    path('handle-update-requests/', views.handleUpdateRequests, name='handleUpdateRequests'),
    path('issue-work-order/', views.issueWorkOrder, name='issueWorkOrder'),
    path('fetch-request/', views.fetchRequest, name='fetchRequest'),
    path('work-order/', views.workOrder, name='workOrder'),
    path('requests-status/', views.requestsStatus, name='requestsStatus'),
    path('requests-in-progress/', views.requestsInProgress, name='requestsInProgress'),
    path('generate-final-bill/', views.generateFinalBill, name='generateFinalBill'),
    path('view-budget/', views.viewBudget, name='viewBudget'),
    path('add-budget/', views.addBudget, name='addBudget'),
    path('edit-budget/', views.editBudget, name='editBudget'),
]

