# Generated by Django 3.1.5 on 2023-04-15 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DueType',
            fields=[
                ('due_id', models.AutoField(primary_key=True, serialize=False)),
                ('due_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewDue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=50)),
                ('check1', models.BooleanField(default=False)),
                ('check2', models.BooleanField(default=False)),
                ('due_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_procedures.duetype')),
            ],
            options={
                'unique_together': {('due_type', 'roll_no')},
            },
        ),
    ]
