# Generated by Django 3.1.5 on 2025-04-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0002_auto_20250402_1850'),
        ('academic_information', '0002_student_hall_id'),
        ('academic_procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_registration',
            name='registration_type',
            field=models.CharField(choices=[('Audit', 'Audit'), ('Improvement', 'Improvement'), ('Backlog', 'Backlog'), ('Regular', 'Regular'), ('Extra Credits', 'Extra Credits'), ('Replacement', 'Replacement')], default='Regular', max_length=20),
        ),
        migrations.AddField(
            model_name='finalregistration',
            name='registration_type',
            field=models.CharField(choices=[('Audit', 'Audit'), ('Improvement', 'Improvement'), ('Backlog', 'Backlog'), ('Regular', 'Regular')], default='Regular', max_length=20),
        ),
        migrations.AddField(
            model_name='initialregistration',
            name='registration_type',
            field=models.CharField(choices=[('Audit', 'Audit'), ('Improvement', 'Improvement'), ('Backlog', 'Backlog'), ('Regular', 'Regular')], default='Regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='assistantshipclaim',
            name='year',
            field=models.IntegerField(choices=[(2025, 2025), (2024, 2024)]),
        ),
        migrations.AlterField(
            model_name='course_registration',
            name='working_year',
            field=models.IntegerField(blank=True, choices=[(2025, 2025), (2024, 2024)], null=True),
        ),
        migrations.AlterField(
            model_name='finalregistrations',
            name='batch',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='messdue',
            name='year',
            field=models.IntegerField(choices=[(2025, 2025), (2024, 2024)]),
        ),
        migrations.AlterField(
            model_name='register',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterUniqueTogether(
            name='course_registration',
            unique_together={('course_id', 'student_id', 'semester_id', 'registration_type')},
        ),
        migrations.AlterUniqueTogether(
            name='finalregistration',
            unique_together={('course_id', 'student_id', 'semester_id', 'registration_type')},
        ),
        migrations.AlterUniqueTogether(
            name='initialregistration',
            unique_together={('course_id', 'student_id', 'semester_id', 'registration_type')},
        ),
        migrations.CreateModel(
            name='course_replacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaces', to='academic_procedures.course_registration')),
                ('old_course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced', to='academic_procedures.course_registration')),
            ],
            options={
                'db_table': 'course_replacement',
                'unique_together': {('old_course_registration', 'new_course_registration')},
            },
        ),
    ]
