# Generated by Django 3.1.5 on 2024-04-16 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programme_curriculum', '0001_initial'),
        ('academic_procedures', '0001_initial'),
        ('academic_information', '0002_auto_20240416_2325'),
        ('globals', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrationchecks',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.semester'),
        ),
        migrations.AddField(
            model_name='studentregistrationchecks',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='studentregistrationcheck',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='semestermarks',
            name='curr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AddField(
            model_name='semestermarks',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='register',
            name='curr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.curriculum'),
        ),
        migrations.AddField(
            model_name='register',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='phdprogressexamination',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='mtechgraduateseminarreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='messdue',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='marksubmissioncheck',
            name='curr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AddField(
            model_name='initialregistrations',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AddField(
            model_name='initialregistrations',
            name='course_slot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.courseslot'),
        ),
        migrations.AddField(
            model_name='initialregistrations',
            name='semester_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.semester'),
        ),
        migrations.AddField(
            model_name='initialregistrations',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='initialregistration',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AddField(
            model_name='initialregistration',
            name='course_slot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.courseslot'),
        ),
        migrations.AddField(
            model_name='initialregistration',
            name='semester_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.semester'),
        ),
        migrations.AddField(
            model_name='initialregistration',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='finalregistrations',
            name='curr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.curriculum'),
        ),
        migrations.AddField(
            model_name='finalregistrations',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='finalregistration',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AddField(
            model_name='finalregistration',
            name='course_slot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.courseslot'),
        ),
        migrations.AddField(
            model_name='finalregistration',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.semester'),
        ),
        migrations.AddField(
            model_name='finalregistration',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='feepayments',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.semester'),
        ),
        migrations.AddField(
            model_name='feepayments',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='dues',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='coursesmtech',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.course'),
        ),
        migrations.AddField(
            model_name='courserequested',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AddField(
            model_name='courserequested',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='course_slot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.courseslot'),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.semester'),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='branchchange',
            name='branches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.departmentinfo'),
        ),
        migrations.AddField(
            model_name='branchchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='bonafide',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='assistantshipclaim',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='assistantshipclaim',
            name='ta_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TA_SUPERVISOR', to='globals.faculty'),
        ),
        migrations.AddField(
            model_name='assistantshipclaim',
            name='thesis_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='THESIS_SUPERVISOR', to='globals.faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='register',
            unique_together={('curr_id', 'student_id')},
        ),
    ]
