# Generated by Django 3.1.5 on 2024-11-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialregistration',
            name='registration_type',
            field=models.CharField(choices=[('Audit', 'Audit'), ('Improvement', 'Improvement'), ('Backlog', 'Backlog'), ('Regular', 'Regular')], default='Regular', max_length=20),
        ),
    ]
