# Generated by Django 3.1.5 on 2024-02-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0002_auto_20240219_0959'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bonafidedetails',
            table='BonafideDetails',
        ),
    ]
