# Generated by Django 3.1.5 on 2024-12-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0003_finalregistration_registration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_registration',
            name='registration_type',
            field=models.CharField(choices=[('Audit', 'Audit'), ('Improvement', 'Improvement'), ('Backlog', 'Backlog'), ('Regular', 'Regular')], default='Regular', max_length=20),
        ),
    ]
