# Generated by Django 3.1.5 on 2024-02-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0003_merge_20240217_1949'),
        ('academic_procedures', '0002_auto_20240214_1323'),
    ]

    operations = [
    ]
