# Generated by Django 3.1.5 on 2023-04-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0004_auto_20230415_1712'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bonafide',
            table=None,
        ),
    ]
