# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-28 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0004_register_test_attr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='test_attr',
        ),
    ]
