# Generated by Django 3.1.5 on 2024-12-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0004_auto_20241117_0137'),
        ('academic_information', '0001_initial'),
        ('academic_procedures', '0004_course_registration_registration_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course_registration',
            unique_together={('course_id', 'student_id', 'semester_id', 'registration_type')},
        ),
    ]
