# Generated by Django 3.1.5 on 2024-02-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0004_merge_20240218_1736'),
        ('academic_procedures', '0005_merge_20240218_2206'),
    ]

    operations = [
    ]
