# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
        ('academic_procedures', '0005_remove_register_test_attr'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='register',
            unique_together=set([('curr_id', 'student_id')]),
        ),
    ]
