# Generated by Django 3.1.5 on 2025-02-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
        ('academic_procedures', '0006_auto_20250114_0326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finalregistration',
            unique_together={('course_id', 'student_id', 'semester_id', 'registration_type')},
        ),
        migrations.AlterUniqueTogether(
            name='initialregistration',
            unique_together={('course_id', 'student_id', 'semester_id', 'registration_type')},
        ),
    ]
