# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0006_auto_20191024_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='r_id',
            new_name='id',
        ),
    ]
