# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0007_auto_20191024_0509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='id',
            new_name='register_id',
        ),
    ]
