# Generated by Django 3.1.5 on 2025-02-04 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0007_auto_20250203_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_replacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaces', to='academic_procedures.course_registration')),
                ('old_course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced', to='academic_procedures.course_registration')),
            ],
            options={
                'db_table': 'course_replacement',
                'unique_together': {('old_course_registration', 'new_course_registration')},
            },
        ),
    ]
