# Generated by Django 3.1.5 on 2025-04-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0008_course_replacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_registration',
            name='semester_type',
            field=models.CharField(choices=[('Odd Semester', 'Odd Semester'), ('Even Semester', 'Even Semester'), ('Summer Semester', 'Summer Semester')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='session',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
