# Generated by Django 3.1.5 on 2025-04-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0008_course_replacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalregistration',
            name='old_course_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_procedures.course_registration'),
        ),
        migrations.AddField(
            model_name='initialregistration',
            name='old_course_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_procedures.course_registration'),
        ),
    ]
