# Generated by Django 3.1.5 on 2025-04-09 21:29

from django.db import migrations

def populate_session_and_semester_type(apps, schema_editor):
    course_registration = apps.get_model('academic_procedures', 'course_registration')
    Semester = apps.get_model('programme_curriculum', 'Semester')

    for obj in course_registration.objects.select_related('semester_id').all():
        sem_no = obj.semester_id.semester_no
        working_year = obj.working_year

        # session logic
        if sem_no % 2 == 1:
            session = f"{working_year}-{str(working_year + 1)[-2:]}"
        else:
            session = f"{working_year - 1}-{str(working_year)[-2:]}"

        # semester_type logic
        if sem_no == 0:
            semester_type = "Summer Semester"
        elif sem_no % 2 == 0:
            semester_type = "Even Semester"
        else:
            semester_type = "Odd Semester"

        obj.session = session
        obj.semester_type = semester_type
        obj.save(update_fields=['session', 'semester_type'])

class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0009_auto_20250409_2128'),
    ]

    operations = [
        migrations.RunPython(populate_session_and_semester_type),
    ]
