# Generated by Django 3.1.5 on 2025-04-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0009_auto_20250420_1221'),
        ('academic_procedures', '0010_populate_session_and_type'),
    ]

    operations = [
    ]