# Generated by Django 3.1.5 on 2025-04-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0011_merge_20250420_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_registration',
            name='semester_type',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='session',
        ),
    ]