# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-21 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0011_auto_20191127_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalregistrations',
            name='batch',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='initialregistrations',
            name='batch',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='register',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
