# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-22 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0012_auto_20200123_2047'),
        ('academic_procedures', '0012_auto_20200123_2006'),
        ('academic_procedures', '0012_auto_20200203_0247'),
    ]

    operations = [
    ]
