# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0004_auto_20191113_0334'),
        ('academic_procedures', '0012_auto_20200123_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonafide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=15)),
                ('enrolled_course', models.CharField(max_length=10)),
                ('fathers_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
            ],
            options={
                'db_table': 'Bonafide',
            },
        ),
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_due', models.IntegerField()),
                ('hostel_due', models.IntegerField()),
                ('library_due', models.IntegerField()),
                ('placement_cell_due', models.IntegerField()),
                ('academic_due', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.Student')),
            ],
            options={
                'db_table': 'Dues',
            },
        ),
    ]
