# Generated by Django 3.1.5 on 2025-04-23 14:01

from django.db import migrations, models

def populate_session_and_semester_type(apps, schema_editor):
    course_registration = apps.get_model('academic_procedures', 'course_registration')
    Semester = apps.get_model('programme_curriculum', 'Semester')

    for obj in course_registration.objects.select_related('semester_id').all():
        sem_no = obj.semester_id.semester_no
        working_year = obj.working_year

        # session logic
        if sem_no % 2 == 1:
            session = f"{working_year}-{str(working_year + 1)[-2:]}"
        else:
            session = f"{working_year - 1}-{str(working_year)[-2:]}"

        # semester_type logic
        if sem_no == 0:
            semester_type = "Summer Semester"
        elif sem_no % 2 == 0:
            semester_type = "Even Semester"
        else:
            semester_type = "Odd Semester"

        obj.session = session
        obj.semester_type = semester_type
        obj.save(update_fields=['session', 'semester_type'])

class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0012_auto_20250422_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_registration',
            name='semester_type',
            field=models.CharField(choices=[('Odd Semester', 'Odd Semester'), ('Even Semester', 'Even Semester'), ('Summer Semester', 'Summer Semester')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='session',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.RunPython(populate_session_and_semester_type),
    ]
