# Generated by Django 3.1.5 on 2025-05-03 01:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_extrainfo_last_selected_role'),
        ('academic_information', '0001_initial'),
        ('programme_curriculum', '0008_populate_semester_type'),
        ('academic_procedures', '0013_auto_20250423_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField()),
                ('start_month', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('end_month', models.IntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.faculty')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
        migrations.CreateModel(
            name='StipendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved_by_faculty', 'Approved by Faculty'), ('approved_by_hod', 'Approved by HOD')], default='pending', max_length=20)),
                ('faculty_remark', models.TextField(blank=True, null=True)),
                ('hod_remark', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stipends', to='academic_procedures.assignment')),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('assignment', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CourseReplacementRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester_type', models.CharField(choices=[('Odd Semester', 'Odd Semester'), ('Even Semester', 'Even Semester'), ('Summer Semester', 'Summer Semester')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('course_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.courseslot')),
                ('new_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_course_reqs', to='programme_curriculum.course')),
                ('old_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_course_reqs', to='programme_curriculum.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'unique_together': {('student', 'course_slot', 'academic_year', 'semester_type')},
            },
        ),
    ]
