# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0013_bonafide_dues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafide',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.Student'),
        ),
    ]
