# Generated by Django 3.2.25 on 2025-07-09 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def create_questions(apps, schema_editor):
    Q = apps.get_model("academic_procedures", "FeedbackQuestion")
    O = apps.get_model("academic_procedures", "FeedbackOption")


    attendance_texts = [
      "Number of classes you missed",
    ]
    for idx, txt in enumerate(attendance_texts, start=1):
        q = Q.objects.create(section="attendance", order=idx, text=txt)
        for j, opt in enumerate(["None", "Less than 5", "Between 5 - 10", "Between 10 - 15", "More than 15"], start=1):
            O.objects.create(question=q, text=opt, order=j)

    texts = [
      "Amount of materials covered in this course was just right",
      "Texts/Reference material/Class notes were easily available",
      "Learning material was relevant and well organized",
      "All the contents were covered",
    ]
    for idx, txt in enumerate(texts, start=1):
        q = Q.objects.create(section="contents", order=idx, text=txt)
        for j, opt in enumerate(["Excellent","Good","Average","Poor"], start=1):
            O.objects.create(question=q, text=opt, order=j)
    Q.objects.create(
        section="contents", order=5,
        text="Any Suggestion Regarding Course Contents [Overall]"
    )

    instr_texts_1 = [
      "Number of classes actually engaged by the instructor",
      "Instructor was punctual in coming to the classes",
      "Duration of most of the classes was as per schedule",
      "All the allocated classes were held on scheduled time and duration",
    ]
    percents = ["< 80%","80% - 90%","90% - 95%","95% - 100%"]
    for idx, txt in enumerate(instr_texts_1, start=1):
        q = Q.objects.create(section="instructor", order=idx, text=txt)
        for j, opt in enumerate(percents, start=1):
            O.objects.create(question=q, text=opt, order=j)

    instr_texts_2 = [
      "Topics were covered in a logical sequence with even pace.",
      "Effective use of teaching aids (Board work/ Presentation/ Audio-Visual aids)",
      "Evaluation schema (Quizzes/ exams/  Assignments) Covered the entire course material.",
      "The evaluation Assignments/ Quizzes etc. was done fairly and on time.",
      "The questions raised in the class were satisfactorily answered.",
      "The Overall effectiveness of the instructor",

    ]
    for idx, txt in enumerate(instr_texts_2, start=5):
        q = Q.objects.create(section="instructor", order=idx, text=txt)
        for j, opt in enumerate(["Excellent","Good","Average","Poor"], start=1):
            O.objects.create(question=q, text=opt, order=j)
    Q.objects.create(
        section="instructor", order=11,
        text="Strengths and Weaknesses of the Instructor"
    )

    tut_texts = [
      "The Tutorials helped in better understanding of the course.",
      "All allocated tutorials were conducted.",
      "Doubts were clarified effectively.",
      "Questions were encouraged.",
      "The evaluation of Assignment/ Quizzes etc was done fairly and on time.",
      "Overall the tutor was effective.",
    ]
    for idx, txt in enumerate(tut_texts, start=1):
        q = Q.objects.create(section="tutorial", order=idx, text=txt)
        for j, opt in enumerate(["Excellent","Good","Average","Poor"], start=1):
            O.objects.create(question=q, text=opt, order=j)
    Q.objects.create(
        section="tutorial", order=7,
        text="Any Constructive Suggestion for Improving the Tutorials"
    )

    lab1 = Q.objects.create(section="lab", order=1,
        text="Course Instructor present in the lab")
    for j, opt in enumerate(["Less than 5 lab","5 to 10 lab","More than 10 lab","Not present any lab"], start=1):
        O.objects.create(question=lab1, text=opt, order=j)
    lab_texts = [
      "Equipment's available in the laboratory were functioning.",
      "Lab Instructor ensured the smooth conduct of experiments.",
      "Laboratory reports were corrected weekly and in time",
    ]
    for idx, txt in enumerate(lab_texts, start=2):
        q = Q.objects.create(section="lab", order=idx, text=txt)
        for j, opt in enumerate(["Excellent","Good","Average","Poor"], start=1):
            O.objects.create(question=q, text=opt, order=j)


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0009_auto_20250503_1355'),
        ('academic_information', '0001_initial'),
        ('academic_procedures', '0014_assignment_coursereplacementrequest_stipendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('contents', 'Course Contents'), ('instructor', 'Course Instructor'), ('tutorial', 'Tutorial'), ('lab', 'Lab Instructor'), ('attendance', 'Attendance')], max_length=20)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('section', models.CharField(choices=[('contents', 'Course Contents'), ('instructor', 'Course Instructor'), ('tutorial', 'Tutorial'), ('lab', 'Lab Instructor'), ('attendance', 'Attendance')], max_length=20)),
                ('session', models.CharField(max_length=9)),
                ('semester_type', models.CharField(choices=[('Odd Semester', 'Odd Semester'), ('Even Semester', 'Even Semester'), ('Summer Semester', 'Summer Semester')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_procedures.feedbackoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_procedures.feedbackquestion')),
            ],
        ),
        migrations.AddField(
            model_name='feedbackoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='academic_procedures.feedbackquestion'),
        ),
        migrations.CreateModel(
            name='BatchChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('new_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_new', to='programme_curriculum.batch')),
                ('old_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_old', to='programme_curriculum.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackFilled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.PositiveIntegerField()),
                ('filled_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'unique_together': {('student', 'semester_no')},
            },
        ),
        migrations.RunPython(create_questions)
    ]
