# Generated by Django 3.0.6 on 2020-05-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0012_auto_20200121_2305'),
        ('academic_procedures', '0014_bonafide_dues'),
    ]

    operations = [
    ]
