# Generated by Django 3.1.5 on 2021-03-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0016_auto_20200522_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalregistrations',
            name='batch',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='initialregistrations',
            name='batch',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='register',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
