# Generated by Django 3.1.5 on 2026-01-06 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0017_courseaddrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseaddrequest',
            name='old_course_registration',
            field=models.ForeignKey(blank=True, help_text='Reference to the previous course registration being replaced (for backlog/improvement)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_procedures.course_registration'),
        ),
        migrations.AlterField(
            model_name='assistantshipclaim',
            name='year',
            field=models.IntegerField(choices=[(2026, 2026), (2025, 2025)]),
        ),
        migrations.AlterField(
            model_name='course_registration',
            name='working_year',
            field=models.IntegerField(blank=True, choices=[(2026, 2026), (2025, 2025)], null=True),
        ),
        migrations.AlterField(
            model_name='finalregistrations',
            name='batch',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='messdue',
            name='year',
            field=models.IntegerField(choices=[(2026, 2026), (2025, 2025)]),
        ),
        migrations.AlterField(
            model_name='register',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
