# Generated by Django 3.1.5 on 2021-03-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0017_auto_20210327_1326'),
        ('academic_procedures', '0017_auto_20210303_2238'),
    ]

    operations = [
    ]
