# Generated by Django 3.1.7 on 2021-04-11 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0017_auto_20210303_2238'),
        ('academic_procedures', '0017_auto_20210307_1956'),
    ]

    operations = [
    ]
