# Generated by Django 3.1.5 on 2021-05-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0002_auto_20210502_1626'),
        ('academic_procedures', '0020_auto_20210422_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_registration',
            name='course_slot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.courseslot'),
        ),
        migrations.AddField(
            model_name='finalregistration',
            name='course_slot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.courseslot'),
        ),
        migrations.AddField(
            model_name='initialregistration',
            name='course_slot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.courseslot'),
        ),
    ]
