# Generated by Django 3.1.5 on 2026-03-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0038_thesis_registration_models'),
        ('academic_information', '0002_thesis_registration_models'),
        ('academic_procedures', '0020_reviewinvitation_thesissubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_year', models.IntegerField(blank=True, null=True)),
                ('academic_session', models.CharField(blank=True, max_length=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_registrations', to='academic_information.student')),
                ('thesis_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='programme_curriculum.thesisslot')),
                ('thesis_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_registrations', to='academic_procedures.thesistopic')),
            ],
            options={
                'db_table': 'ThesisRegistration',
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='ProgressSeminarRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('progress_seminar_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='programme_curriculum.progressseminarslot')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_seminar_registrations', to='academic_information.student')),
            ],
            options={
                'db_table': 'ProgressSeminarRegistration',
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
