# Generated by Django 3.1.5 on 2026-07-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0033_auto_20260704_1109'),
        ('academic_procedures', '0020_backfill_course_registration_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_registration',
            name='course_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.courseinstructor'),
        ),
        migrations.AddField(
            model_name='finalregistration',
            name='course_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.courseinstructor'),
        ),
    ]
