# Generated by Django 3.1.5 on 2026-03-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0021_thesis_registration_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisregistration',
            name='credits',
            field=models.PositiveSmallIntegerField(choices=[(3, '3 Credits'), (6, '6 Credits'), (9, '9 Credits'), (12, '12 Credits')], default=6, help_text='Credits the student is registering for this semester (3/6/9/12)'),
        ),
    ]
