# Generated by Django 3.1.5 on 2026-07-09 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0034_studentbatchupload_section'),
        ('academic_procedures', '0021_auto_20260704_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='course_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.courseinstructor'),
        ),
    ]
