# Generated by Django 3.1.5 on 2021-05-07 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0006_auto_20210422_2332'),
        ('academic_procedures', '0021_auto_20210502_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistantshipclaim',
            old_name='hod_approval',
            new_name='acad_approval',
        ),
        migrations.AddField(
            model_name='assistantshipclaim',
            name='account_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistantshipclaim',
            name='stipend',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MessDue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Jan', 'January'), ('Feb', 'Febuary'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=10)),
                ('year', models.IntegerField(choices=[(2021, 2021), (2020, 2020)])),
                ('description', models.CharField(choices=[('Stu_paid', 'Paid'), ('Stu_due', 'Due')], max_length=15)),
                ('amount', models.IntegerField()),
                ('remaining_amount', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
    ]
