# Generated by Django 3.1.5 on 2021-06-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0022_auto_20210507_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistantship_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_status', models.BooleanField()),
                ('hod_status', models.BooleanField()),
                ('account_status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='assistantshipclaim',
            name='hod_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='mode',
            field=models.CharField(choices=[('Online Payment', 'Online Payment'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('Bank Challan', 'Bank Challan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feepayments',
            name='mode',
            field=models.CharField(choices=[('Online Payment', 'Online Payment'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('Bank Challan', 'Bank Challan')], max_length=20),
        ),
    ]
