# Generated by Django 3.1.5 on 2026-08-03 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0034_studentbatchupload_section'),
        ('academic_procedures', '0022_feedbackresponse_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseaddrequest',
            name='course_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.courseinstructor'),
        ),
    ]
