# Generated by Django 3.1.5 on 2026-03-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0019_swayamreplacementrequest'),
        ('academic_procedures', '0023_thesis_evaluation_models'),
    ]

    operations = [
    ]
