# Generated by Django 3.1.5 on 2026-08-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0023_courseaddrequest_course_instructor'),
        ('academic_procedures', '0024_merge_20260314_1604'),
    ]

    operations = [
    ]
