# Generated by Django 3.1.5 on 2026-07-05 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_procedures', '0024_merge_20260314_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewinvitation',
            options={'ordering': ['submission', 'examiner_type', 'priority']},
        ),
        migrations.AddField(
            model_name='reviewinvitation',
            name='examiner_type',
            field=models.CharField(choices=[('indian', 'Indian'), ('foreign', 'Foreign')], db_index=True, default='indian', max_length=10),
        ),
        migrations.AddField(
            model_name='thesissubmission',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deaned_subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thesissubmission',
            name='dean_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesissubmission',
            name='dean_invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thesissubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('dean_panel_review', 'Pending Dean Panel Approval'), ('director_review', 'Pending Director Prioritization'), ('dean_invite_pending', 'Pending Dean Invitation'), ('in_review', 'In External Review'), ('completed', 'Review Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='reviewinvitation',
            unique_together={('submission', 'examiner_type', 'priority')},
        ),
    ]
