# Generated by Django 3.1.5 on 2026-07-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0020_backfill_course_registration_session'),
        ('academic_procedures', '0025_auto_20260705_1724'),
    ]

    operations = [
    ]
