# Generated by Django 3.1.5 on 2026-07-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0026_merge_20260705_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewinvitation',
            name='prof_fax',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
