# Generated by Django 3.1.5 on 2026-07-09 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0027_reviewinvitation_prof_fax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originality_presentation', models.TextField(blank=True, default='')),
                ('quality_comparable', models.BooleanField(blank=True, null=True)),
                ('new_ideas_original', models.BooleanField(blank=True, null=True)),
                ('correction_severity', models.CharField(blank=True, choices=[('none', 'None'), ('minor', 'Minor'), ('major', 'Major')], default='', max_length=10)),
                ('technical_content', models.TextField(blank=True, default='')),
                ('highlights', models.TextField(blank=True, default='')),
                ('suggestions', models.TextField(blank=True, default='')),
                ('defense_questions', models.TextField(blank=True, default='')),
                ('recommendation', models.CharField(choices=[('accept', 'Acceptable in present form for award of the PhD degree'), ('accept_with_corrections', 'Acceptable; suggested corrections/modifications to be incorporated'), ('needs_improvement', "Needs technical improvement to the examiner's satisfaction"), ('reject', 'Rejected -- thesis does not contain novel work')], max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='academic_procedures.reviewinvitation')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminerBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_address', models.TextField(blank=True, default='')),
                ('account_no', models.CharField(blank=True, default='', max_length=50)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=20)),
                ('pan_no', models.CharField(blank=True, default='', max_length=20)),
                ('iban_no', models.CharField(blank=True, default='', max_length=40)),
                ('swift_code', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='academic_procedures.reviewinvitation')),
            ],
        ),
    ]
