# Generated by Django 3.1.5 on 2026-07-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0028_examinerbankdetails_thesisreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarentry',
            name='pub_presented_unpublished',
            field=models.PositiveIntegerField(default=0, help_text='Papers presented in conferences/meetings/workshops (unpublished)'),
        ),
        migrations.AddField(
            model_name='seminarentry',
            name='pub_published_or_accepted',
            field=models.PositiveIntegerField(default=0, help_text='Papers published/accepted in journals or conference proceedings'),
        ),
        migrations.AddField(
            model_name='seminarentry',
            name='pub_submitted_under_review',
            field=models.PositiveIntegerField(default=0, help_text='Papers submitted (under review)'),
        ),
        migrations.DeleteModel(
            name='PublicationCount',
        ),
    ]
