# Generated by Django 3.1.5 on 2026-07-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0029_auto_20260712_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesissubmission',
            name='dean_panel_remarks',
            field=models.TextField(blank=True),
        ),
    ]
