# Generated by Django 3.1.5 on 2026-07-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0030_thesissubmission_dean_panel_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesissubmission',
            name='director_remarks',
            field=models.TextField(blank=True),
        ),
    ]
