# Generated by Django 3.1.5 on 2026-07-13 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globals', '0007_moduleaccess_thesis_research'),
        ('academic_information', '0003_merge_20260314_1604'),
        ('academic_procedures', '0031_thesissubmission_director_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensiveExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_thesis_title', models.CharField(blank=True, max_length=300)),
                ('entry_qualification', models.CharField(choices=[('masters', 'ME/M.Tech/M.Des/M.Phil (16 credits required)'), ('bachelors', 'B.Tech/B.E./M.Sc./MA (40 credits required)')], max_length=10)),
                ('credits_completed', models.PositiveIntegerField(default=0)),
                ('current_cpi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('research_methodology_completed', models.BooleanField(default=False)),
                ('credits_verified', models.BooleanField(default=False)),
                ('cpi_verified', models.BooleanField(default=False)),
                ('research_methodology_verified', models.BooleanField(default=False)),
                ('academic_office_remarks', models.TextField(blank=True)),
                ('academic_office_verified_at', models.DateTimeField(blank=True, null=True)),
                ('convener_remarks', models.TextField(blank=True)),
                ('convener_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('academic_office_pending', 'Pending Academic Office Verification'), ('academic_office_rejected', 'Rejected by Academic Office'), ('convener_pending', 'Pending Convener Approval'), ('convener_rejected', 'Rejected by Convener'), ('in_progress', 'Committee Approved — In Progress'), ('passed', 'Passed'), ('failed_final', 'Failed — Attempts Exhausted')], default='academic_office_pending', max_length=30)),
                ('current_attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_office_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprehensive_exams_office_verified', to=settings.AUTH_USER_MODEL)),
                ('co_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_exams_cosupervised', to='globals.faculty')),
                ('convener_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprehensive_exams_convened', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_exam', to='academic_information.student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_exams_supervised', to='globals.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ComprehensiveExamAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('subjects_floated', 'Subjects Floated, Pending HOD Approval'), ('hod_rejected', 'Subjects Rejected by HOD'), ('subjects_ready', 'Subjects Approved, Pending Student Selection'), ('subjects_opted', 'Subjects Opted, Pending Supervisor Confirmation'), ('confirmation_rejected', 'Supervisor Rejected Opted Subjects'), ('result_pending', 'Confirmed — Awaiting Result'), ('passed', 'Passed'), ('failed', 'Failed')], default='subjects_floated', max_length=25)),
                ('written_exam_date', models.DateField(blank=True, null=True)),
                ('oral_exam_date', models.DateField(blank=True, null=True)),
                ('hod_remarks', models.TextField(blank=True)),
                ('hod_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_confirmation_remarks', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=10, null=True)),
                ('fundamentals_comment', models.TextField(blank=True)),
                ('problem_identification_comment', models.TextField(blank=True)),
                ('plan_of_work_comment', models.TextField(blank=True)),
                ('suggestions_comment', models.TextField(blank=True)),
                ('additional_literature_comment', models.TextField(blank=True)),
                ('milestone_plan_upload', models.FileField(blank=True, null=True, upload_to='comprehensive_exam_milestones/')),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='academic_procedures.comprehensiveexam')),
                ('hod_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprehensive_attempts_hod_reviewed', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprehensive_attempts_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exam', 'attempt_number'],
                'unique_together': {('exam', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='FloatedSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('selected_by_student', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic_procedures.comprehensiveexamattempt')),
            ],
        ),
        migrations.CreateModel(
            name='ComprehensiveExamCommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='academic_procedures.comprehensiveexam')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.faculty')),
            ],
            options={
                'unique_together': {('exam', 'member')},
            },
        ),
    ]
