# Generated by Django 3.1.5 on 2026-07-14 12:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_merge_20260314_1604'),
        ('programme_curriculum', '0045_rename_progress_seminar_to_seminar'),
        ('globals', '0007_moduleaccess_thesis_research'),
        ('academic_procedures', '0032_comprehensiveexam_comprehensiveexamattempt_comprehensiveexamcommitteemember_floatedsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhDCourseRegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester_type', models.CharField(choices=[('Odd Semester', 'Odd Semester'), ('Even Semester', 'Even Semester'), ('Summer Semester', 'Summer Semester')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phd_course_requests', to='programme_curriculum.course')),
                ('course_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.courseslot')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phd_course_requests_processed', to='globals.extrainfo')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phd_course_requests', to='academic_information.student')),
            ],
            options={
                'db_table': 'PhDCourseRegistrationRequest',
                'unique_together': {('student', 'semester', 'course_slot')},
            },
        ),
    ]
