# Generated by Django 3.1.5 on 2026-07-15 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globals', '0007_moduleaccess_thesis_research'),
        ('academic_information', '0003_merge_20260314_1604'),
        ('academic_procedures', '0033_phdcourseregistrationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_thesis_title', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('satisfactory', 'Satisfactory')], default='in_progress', max_length=20)),
                ('current_attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_seminars_cosupervised', to='globals.faculty')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_seminar', to='academic_information.student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_seminars_supervised', to='globals.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='OpenSeminarAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('convener_pending', 'Pending Convener Approval'), ('convener_rejected', 'Rejected by Convener'), ('result_pending', 'Committee Approved — Awaiting Result'), ('satisfactory', 'Satisfactory'), ('not_satisfactory', 'Not Satisfactory')], default='convener_pending', max_length=20)),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('course_work_credits', models.PositiveIntegerField(default=0)),
                ('progress_seminar_credits', models.PositiveIntegerField(default=0)),
                ('thesis_research_credits', models.PositiveIntegerField(default=0)),
                ('teaching_credits', models.PositiveIntegerField(default=0)),
                ('semesters_completed', models.PositiveIntegerField(default=0)),
                ('rpc_recommended_open_seminar', models.BooleanField(default=False)),
                ('first_draft_sent_to_dean', models.BooleanField(default=False)),
                ('convener_remarks', models.TextField(blank=True)),
                ('convener_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('satisfactory', 'Satisfactory'), ('not_satisfactory', 'Not Satisfactory')], max_length=20, null=True)),
                ('committee_comments', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('dn_quality', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Sat', 'Satisfactory'), ('Unsat', 'Unsatisfactory')], max_length=20)),
                ('dn_quantity', models.CharField(blank=True, choices=[('Enough', 'Enough'), ('Just', 'Just Sufficient'), ('Insuff', 'Insufficient')], max_length=10)),
                ('dn_publications', models.CharField(blank=True, choices=[('Enough', 'Enough'), ('Just', 'Just Sufficient'), ('Insuff', 'Insufficient')], max_length=10)),
                ('dn_overall', models.CharField(blank=True, choices=[('satisfactory', 'Satisfactory'), ('not_satisfactory', 'Not Satisfactory')], max_length=20)),
                ('dn_comments', models.TextField(blank=True)),
                ('dn_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('convener_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_seminar_attempts_convened', to=settings.AUTH_USER_MODEL)),
                ('dean_nominee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_seminar_nominations', to='globals.faculty')),
                ('open_seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='academic_procedures.openseminar')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_seminar_attempts_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['open_seminar', 'attempt_number'],
                'unique_together': {('open_seminar', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='OpenSeminarCommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='academic_procedures.openseminarattempt')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.faculty')),
            ],
            options={
                'unique_together': {('attempt', 'member')},
            },
        ),
    ]
