# Generated by Django 3.1.5 on 2026-07-15 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0045_rename_progress_seminar_to_seminar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_information', '0003_merge_20260314_1604'),
        ('academic_procedures', '0034_openseminar_openseminarattempt_openseminarcommitteemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingCreditPreRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending HOD Decision'), ('sent_back', 'Sent Back by HOD'), ('allocated', 'Course Allocated'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('hod_remarks', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('satisfactory', 'Satisfactory'), ('not_satisfactory', 'Not Satisfactory')], max_length=20, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_credit_allocations', to='programme_curriculum.course')),
                ('choice_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_credit_choice1', to='programme_curriculum.course')),
                ('choice_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_credit_choice2', to='programme_curriculum.course')),
                ('choice_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_credit_choice3', to='programme_curriculum.course')),
                ('choice_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_credit_choice4', to='programme_curriculum.course')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_credit_completions', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_credit_decisions', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_credit_registrations', to='academic_information.student')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='TeachingCreditEvaluationResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality_band', models.CharField(blank=True, choices=[('<80', '<80%'), ('80-90', '80%-90%'), ('90-95', '90%-95%'), ('95-100', '95%-100%')], max_length=10)),
                ('schedule_adherence_band', models.CharField(blank=True, choices=[('<80', '<80%'), ('80-90', '80%-90%'), ('90-95', '90%-95%'), ('95-100', '95%-100%')], max_length=10)),
                ('topics_sequence', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=10)),
                ('teaching_aids', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=10)),
                ('questions_answered', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=10)),
                ('overall_effectiveness', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=10)),
                ('strengths_weaknesses', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic_procedures.teachingcreditpreregistration')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_credit_evaluations_given', to='academic_information.student')),
            ],
            options={
                'unique_together': {('registration', 'respondent')},
            },
        ),
    ]
