# Generated by Django 3.1.5 on 2026-07-18 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0045_rename_progress_seminar_to_seminar'),
        ('academic_procedures', '0036_rename_seminar_and_teaching_credit_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressseminarentry',
            name='semester',
            field=models.ForeignKey(blank=True, help_text="Student's semester when this report was created.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.semester'),
        ),
    ]
