# Generated by Django 3.1.5 on 2026-07-21 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0007_moduleaccess_thesis_research'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_procedures', '0037_add_semester_to_progress_seminar_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensiveExamConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComprehensiveExamRPCComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='floatedsubject',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='comprehensiveexam',
            name='convener_at',
        ),
        migrations.RemoveField(
            model_name='comprehensiveexam',
            name='convener_by',
        ),
        migrations.RemoveField(
            model_name='comprehensiveexam',
            name='convener_remarks',
        ),
        migrations.RemoveField(
            model_name='comprehensiveexamattempt',
            name='hod_remarks',
        ),
        migrations.RemoveField(
            model_name='comprehensiveexamattempt',
            name='hod_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='comprehensiveexamattempt',
            name='hod_reviewed_by',
        ),
        migrations.RemoveField(
            model_name='comprehensiveexamattempt',
            name='oral_exam_date',
        ),
        migrations.RemoveField(
            model_name='comprehensiveexamattempt',
            name='supervisor_confirmation_remarks',
        ),
        migrations.RemoveField(
            model_name='comprehensiveexamattempt',
            name='written_exam_date',
        ),
        migrations.AddField(
            model_name='comprehensiveexam',
            name='dpgc_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprehensiveexam',
            name='dpgc_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprehensive_exams_dpgc_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprehensiveexam',
            name='dpgc_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comprehensiveexamattempt',
            name='dean_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprehensiveexamattempt',
            name='dean_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprehensive_attempts_dean_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprehensiveexamattempt',
            name='exam_date',
            field=models.DateField(blank=True, help_text='Settable by the supervisor or any RPC member; may be updated again when RPC finalizes the report.', null=True),
        ),
        migrations.AddField(
            model_name='comprehensiveexamattempt',
            name='pgcs_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comprehensiveexamattempt',
            name='pgcs_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprehensiveexamattempt',
            name='pgcs_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprehensive_attempts_pgcs_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comprehensiveexam',
            name='status',
            field=models.CharField(choices=[('academic_office_pending', 'Pending Academic Office Verification'), ('academic_office_rejected', 'Rejected by Academic Office'), ('dpgc_pending', 'Pending Convener (DPGC) Approval'), ('dpgc_rejected', 'Rejected by Convener (DPGC)'), ('in_progress', 'Approved by DPGC — In Progress'), ('passed', 'Passed'), ('failed_final', 'Failed — Attempts Exhausted')], default='academic_office_pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='comprehensiveexamattempt',
            name='reported_by',
            field=models.ForeignKey(blank=True, help_text='Whichever RPC member finalized the panel (moved rpc_pending -> pgcs_pending).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprehensive_attempts_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comprehensiveexamattempt',
            name='status',
            field=models.CharField(choices=[('rpc_pending', 'Pending RPC Consensus'), ('pgcs_pending', 'RPC Finalized — Pending Convener (PGCS) Review'), ('dean_pending', 'Approved by PGCS — Pending Dean Academic'), ('passed', 'Passed'), ('failed', 'Failed')], default='rpc_pending', max_length=25),
        ),
        migrations.DeleteModel(
            name='ComprehensiveExamCommitteeMember',
        ),
        migrations.DeleteModel(
            name='FloatedSubject',
        ),
        migrations.AddField(
            model_name='comprehensiveexamrpccomment',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpc_comments', to='academic_procedures.comprehensiveexamattempt'),
        ),
        migrations.AddField(
            model_name='comprehensiveexamrpccomment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.faculty'),
        ),
        migrations.AddField(
            model_name='comprehensiveexamconsent',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='academic_procedures.comprehensiveexamattempt'),
        ),
        migrations.AddField(
            model_name='comprehensiveexamconsent',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='comprehensiveexamrpccomment',
            unique_together={('attempt', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='comprehensiveexamconsent',
            unique_together={('attempt', 'member')},
        ),
    ]
