# Generated by Django 3.1.5 on 2026-07-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0038_auto_20260721_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprehensiveexam',
            name='proposed_exam_date',
            field=models.DateField(blank=True, help_text="Set by the supervisor at proposal time; seeds attempt 1's exam_date once DPGC approves.", null=True),
        ),
    ]
