# Generated by Django 3.1.5 on 2026-07-22 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globals', '0007_moduleaccess_thesis_research'),
        ('academic_procedures', '0039_comprehensiveexam_proposed_exam_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSeminarConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenSeminarRPCComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='openseminarattempt',
            name='convener_at',
        ),
        migrations.RemoveField(
            model_name='openseminarattempt',
            name='convener_by',
        ),
        migrations.RemoveField(
            model_name='openseminarattempt',
            name='convener_remarks',
        ),
        migrations.RemoveField(
            model_name='openseminarattempt',
            name='course_work_credits',
        ),
        migrations.RemoveField(
            model_name='openseminarattempt',
            name='first_draft_sent_to_dean',
        ),
        migrations.RemoveField(
            model_name='openseminarattempt',
            name='progress_seminar_credits',
        ),
        migrations.RemoveField(
            model_name='openseminarattempt',
            name='proposed_date',
        ),
        migrations.RemoveField(
            model_name='openseminarattempt',
            name='rpc_recommended_open_seminar',
        ),
        migrations.RemoveField(
            model_name='openseminarattempt',
            name='semesters_completed',
        ),
        migrations.RemoveField(
            model_name='openseminarattempt',
            name='teaching_credits',
        ),
        migrations.RemoveField(
            model_name='openseminarattempt',
            name='thesis_research_credits',
        ),
        migrations.AddField(
            model_name='openseminar',
            name='course_work_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='openseminar',
            name='dean_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openseminar',
            name='dean_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_seminars_dean_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openseminar',
            name='dean_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='openseminar',
            name='first_draft_sent_to_dean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openseminar',
            name='hod_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openseminar',
            name='hod_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_seminars_hod_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openseminar',
            name='hod_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='openseminar',
            name='progress_seminar_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='openseminar',
            name='proposed_date',
            field=models.DateField(blank=True, help_text="Set by the supervisor at proposal time; seeds attempt 1's seminar_date once Dean approves.", null=True),
        ),
        migrations.AddField(
            model_name='openseminar',
            name='rpc_recommended_open_seminar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openseminar',
            name='semesters_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='openseminar',
            name='teaching_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='openseminar',
            name='thesis_research_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='openseminarattempt',
            name='dean_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openseminarattempt',
            name='dean_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_seminar_attempts_dean_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openseminarattempt',
            name='hod_review_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='openseminarattempt',
            name='hod_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openseminarattempt',
            name='hod_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_seminar_attempts_hod_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openseminarattempt',
            name='seminar_date',
            field=models.DateField(blank=True, help_text='Settable by the supervisor or any RPC member; may be updated again when RPC finalizes.', null=True),
        ),
        migrations.AlterField(
            model_name='openseminar',
            name='status',
            field=models.CharField(choices=[('hod_pending', 'Pending Convener (DPGC) Review'), ('hod_rejected', 'Rejected by Convener (DPGC)'), ('dean_pending', 'Pending Dean Academic Approval'), ('dean_rejected', 'Rejected by Dean Academic'), ('in_progress', 'Approved — In Progress'), ('satisfactory', 'Satisfactory')], default='hod_pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='openseminarattempt',
            name='reported_by',
            field=models.ForeignKey(blank=True, help_text='Whichever RPC member finalized the panel (moved rpc_pending -> hod_review_pending).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_seminar_attempts_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='openseminarattempt',
            name='status',
            field=models.CharField(choices=[('rpc_pending', 'Pending RPC Consensus'), ('hod_review_pending', 'RPC Finalized — Pending Convener (DPGC) Review'), ('dean_pending', 'Approved by Convener — Pending Dean Academic'), ('satisfactory', 'Satisfactory'), ('not_satisfactory', 'Not Satisfactory')], default='rpc_pending', max_length=25),
        ),
        migrations.DeleteModel(
            name='OpenSeminarCommitteeMember',
        ),
        migrations.AddField(
            model_name='openseminarrpccomment',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpc_comments', to='academic_procedures.openseminarattempt'),
        ),
        migrations.AddField(
            model_name='openseminarrpccomment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.faculty'),
        ),
        migrations.AddField(
            model_name='openseminarconsent',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='academic_procedures.openseminarattempt'),
        ),
        migrations.AddField(
            model_name='openseminarconsent',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='openseminarrpccomment',
            unique_together={('attempt', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='openseminarconsent',
            unique_together={('attempt', 'member')},
        ),
    ]
