# Generated by Django 3.1.5 on 2026-08-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    NOTE: first_draft_sent_to_dean (bool) -> first_draft_document (FileField)
    is a deliberate, unavoidable loss of historical signal for any existing
    OpenSeminar row: a "was it sent" flag carries no actual file to migrate
    into the new field, so pre-existing True rows simply lose that signal
    (become an empty file field) once this runs.
    """

    dependencies = [
        ('academic_procedures', '0040_auto_20260722_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openseminar',
            name='first_draft_sent_to_dean',
        ),
        migrations.AddField(
            model_name='openseminar',
            name='first_draft_document',
            field=models.FileField(blank=True, null=True, upload_to='open_seminar_first_drafts/'),
        ),
    ]
