# Generated by Django 3.1.5 on 2026-08-03 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globals', '0008_announcement'),
        ('programme_curriculum', '0046_thesisslot_evaluation_type'),
        ('academic_procedures', '0042_auto_20260802_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisExaminerCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Not Yet Invited'), ('invited', 'Invited'), ('accepted', 'Accepted'), ('rejected', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['panel', 'priority'],
            },
        ),
        migrations.AddField(
            model_name='thesisevaluation',
            name='numeric_grade',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Decimal-mode final grade: average of supervisor_score and examiner_score', max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='ThesisExaminerPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('hod_pending', 'Awaiting HOD Nomination'), ('dean_pending', 'Awaiting Dean Ranking'), ('invited', 'Invitations Sent'), ('accepted', 'Examiner Confirmed'), ('all_declined', 'All Candidates Declined')], default='hod_pending', max_length=20)),
                ('hod_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('dean_invited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_candidate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academic_procedures.thesisexaminercandidate')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_examiner_panel', to='programme_curriculum.batch')),
                ('dean_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_panels_ranked', to=settings.AUTH_USER_MODEL)),
                ('hod_submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_panels_nominated', to='globals.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='thesisexaminercandidate',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='academic_procedures.thesisexaminerpanel'),
        ),
        migrations.CreateModel(
            name='ThesisEvaluationScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('supervisor_scored_at', models.DateTimeField(blank=True, null=True)),
                ('examiner_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('examiner_scored_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_inputs', to='academic_procedures.thesisevaluation')),
                ('examiner_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores_given', to='academic_procedures.thesisexaminercandidate')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='thesisexaminercandidate',
            unique_together={('panel', 'priority')},
        ),
    ]
