# Generated by Django 3.1.5 on 2026-08-04 10:58

import applications.academic_procedures.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0043_pg_thesis_examiner_panel_decimal_grading'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGThesisSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('synopsis', models.FileField(upload_to=applications.academic_procedures.models.upload_pg_synopsis)),
                ('thesis_report', models.FileField(upload_to=applications.academic_procedures.models.upload_pg_report)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('thesis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pg_submission', to='academic_procedures.thesistopic')),
            ],
        ),
    ]
