# Generated by Django 3.1.5 on 2026-08-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0044_pgthesissubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisevaluation',
            name='numeric_grade',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Decimal-mode final grade: average of supervisor_score and examiner_score', max_digits=4, null=True),
        ),
    ]
