# Generated by Django 3.1.5 on 2026-08-04 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0023_courseaddrequest_course_instructor'),
        ('academic_procedures', '0045_widen_thesisevaluation_numeric_grade'),
    ]

    operations = [
    ]
