# Generated by Django 3.1.5 on 2026-08-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0046_merge_20260804_2334'),
        ('academic_procedures', '0025_merge_20260805_2216'),
    ]

    operations = [
    ]
