# Generated by Django 3.1.5 on 2026-08-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0051_auto_20260813_1430'),
        ('academic_procedures', '0047_merge_20260805_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdcourseregistrationrequest',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('Backlog', 'Backlog'), ('Improvement', 'Improvement')], max_length=20),
        ),
        migrations.AddField(
            model_name='phdcourseregistrationrequest',
            name='source_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phd_source_course_requests', to='programme_curriculum.course'),
        ),
    ]
