# Generated by Django 3.1.5 on 2026-08-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0051_auto_20260813_1430'),
        ('academic_procedures', '0048_auto_20260815_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisregistration',
            name='thesis',
            field=models.ForeignKey(blank=True, help_text='Catalog entry chosen within thesis_slot (admin manual add/allot only -- the student self-registration flow does not set this)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.thesis'),
        ),
    ]
