# Generated by Django 3.1.5 on 2026-08-25 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_information', '0010_normalize_phd_programme'),
        ('academic_procedures', '0050_auto_20260815_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonafideCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('Scholarship', 'Scholarship'), ('Railway Pass', 'Railway Pass'), ('Education Loan', 'Education Loan'), ('Higher Studies', 'Higher Studies'), ('Staff Benefit Fund', 'Staff Benefit Fund'), ('Bihar Student Credit Card', 'Bihar Student Credit Card'), ('Internship', 'Internship'), ('VISA Purpose', 'VISA Purpose'), ('Other', 'Other')], max_length=40)),
                ('custom_purpose', models.CharField(blank=True, max_length=150)),
                ('reference_number', models.CharField(db_index=True, max_length=120, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_bonafide_certificates', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonafide_certificates', to='academic_information.student')),
            ],
            options={
                'db_table': 'BonafideCertificate',
                'ordering': ('-issued_at',),
            },
        ),
    ]
