# Generated by Django 3.1.5 on 2026-08-23 12:59

import applications.academic_procedures.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0012_acad_role_module_access'),
        ('academic_procedures', '0050_auto_20260815_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesisreview',
            options={'ordering': ['invitation', 'round_number']},
        ),
        migrations.AddField(
            model_name='reviewinvitation',
            name='revision_round',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='thesisreview',
            name='round_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='thesissubmission',
            name='defense_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesissubmission',
            name='examiner_reports_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesissubmission',
            name='final_review_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesissubmission',
            name='reports_forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesissubmission',
            name='revision_consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesissubmission',
            name='revision_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesissubmission',
            name='revision_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thesisreview',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='academic_procedures.reviewinvitation'),
        ),
        migrations.AlterField(
            model_name='thesissubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('dean_panel_review', 'Pending Dean Panel Approval'), ('director_review', 'Pending Director Prioritization'), ('dean_invite_pending', 'Pending Dean Invitation'), ('in_review', 'In External Review'), ('examiner_reports_ready', 'Examiner Reports Ready'), ('supervisor_reports_review', 'Pending Supervisor Review'), ('student_revision_pending', 'Pending Student Revision'), ('supervisor_revision_review', 'Pending Supervisor & RPC Consent'), ('dean_final_review', 'Pending Dean Final Review'), ('approved_for_defense', 'Approved for Defense')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='thesisreview',
            unique_together={('invitation', 'round_number')},
        ),
        migrations.CreateModel(
            name='ThesisRevisionRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('revised_thesis', models.FileField(blank=True, null=True, upload_to=applications.academic_procedures.models.upload_report)),
                ('revised_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_consented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_rounds', to='academic_procedures.thesissubmission')),
            ],
            options={
                'ordering': ['submission', 'round_number'],
                'unique_together': {('submission', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='ThesisRevisionConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.faculty')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='academic_procedures.thesisrevisionround')),
            ],
            options={
                'unique_together': {('round', 'member')},
            },
        ),
    ]
