# Generated by Django 3.1.5 on 2026-08-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0010_normalize_phd_programme'),
        ('programme_curriculum', '0053_alphanumeric_sections'),
        ('academic_procedures', '0051_bonafidecertificate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course_registration',
            unique_together={('course_id', 'student_id', 'semester_id', 'registration_type', 'semester_type')},
        ),
    ]
