# Generated by Django 3.1.5 on 2026-08-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0051_auto_20260823_1259'),
        ('academic_procedures', '0053_bonafidecertificate_pdf_content'),
    ]

    operations = [
    ]
