# Generated by Django 3.1.5 on 2026-09-07 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globals', '0012_acad_role_module_access'),
        ('academic_procedures', '0054_merge_20260828_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisTopicChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_category', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Sponsored', 'Sponsored'), ('External', 'External')], max_length=20)),
                ('new_broad_area', models.CharField(blank=True, max_length=200)),
                ('new_research_theme', models.TextField(blank=True)),
                ('current_supervisor_consented', models.BooleanField(default=False)),
                ('current_co_supervisor_consented', models.BooleanField(default=False)),
                ('new_supervisor_consented', models.BooleanField(default=False)),
                ('new_co_supervisor_consented', models.BooleanField(default=False)),
                ('decline_remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_consents', 'Pending Consents'), ('declined', 'Declined by a Consenter'), ('hod_pending', 'Pending with HOD'), ('hod_rejected', 'Rejected by HOD'), ('dean_pending', 'Pending with Dean'), ('dean_rejected', 'Rejected by Dean'), ('approved', 'Approved')], default='pending_consents', max_length=20)),
                ('hod_remarks', models.TextField(blank=True)),
                ('hod_at', models.DateTimeField(blank=True, null=True)),
                ('dean_remarks', models.TextField(blank=True)),
                ('dean_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dean_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_change_dean_reviews', to=settings.AUTH_USER_MODEL)),
                ('declined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_change_declines', to=settings.AUTH_USER_MODEL)),
                ('hod_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_change_hod_reviews', to=settings.AUTH_USER_MODEL)),
                ('new_co_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thesis_change_requests_as_new_co_supervisor', to='globals.faculty')),
                ('new_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thesis_change_requests_as_new_supervisor', to='globals.faculty')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='academic_procedures.thesistopic')),
            ],
        ),
    ]
