# Generated by Django 3.1.5 on 2026-09-08 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0012_acad_role_module_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_procedures', '0055_thesistopicchangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisCommitteeChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('hod_pending', 'Pending with HOD'), ('hod_rejected', 'Rejected by HOD, Returned to Supervisor'), ('dean_pending', 'Pending with Dean'), ('dean_rejected', 'Rejected by Dean, Returned to Supervisor'), ('approved', 'Approved')], default='hod_pending', max_length=20)),
                ('hod_remarks', models.TextField(blank=True)),
                ('hod_at', models.DateTimeField(blank=True, null=True)),
                ('dean_remarks', models.TextField(blank=True)),
                ('dean_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dean_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_committee_change_dean_reviews', to=settings.AUTH_USER_MODEL)),
                ('hod_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_committee_change_hod_reviews', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='thesis_committee_change_requests', to='globals.Faculty')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_change_requests', to='academic_procedures.thesistopic')),
            ],
        ),
    ]
