# Generated by Django 3.1.5 on 2026-09-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0056_thesiscommitteechangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_category', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Post Graduate'), ('PHD', 'Doctor of Philosophy')], db_index=True, max_length=3)),
                ('start_year', models.PositiveSmallIntegerField(db_index=True)),
                ('one_time_heads', models.JSONField(blank=True, default=list)),
                ('semester_heads', models.JSONField(blank=True, default=list)),
                ('tuition_hostel_heads', models.JSONField(blank=True, default=list)),
                ('mess_advance_per_semester', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'FeeStructure',
                'ordering': ('programme_category', '-start_year'),
            },
        ),
        migrations.AddField(
            model_name='bonafidecertificate',
            name='certificate_type',
            field=models.CharField(choices=[('bonafide', 'Bonafide Certificate'), ('fee', 'Paid / Unpaid Fee Certificate')], db_index=True, default='bonafide', max_length=16),
        ),
        migrations.AddField(
            model_name='bonafidecertificate',
            name='fee_rows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('programme_category', 'start_year'), name='fee_structure_one_per_session'),
        ),
    ]
