# Generated by Django 3.1.5 on 2026-09-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0057_fee_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='concession_label',
            field=models.CharField(default='PWD/SC/ST', max_length=40),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='general_label',
            field=models.CharField(default='Gen/OBC/EWS', max_length=40),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='semester_count',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
