# Generated by Django 3.1.5 on 2026-10-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0058_fee_structure_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafidecertificate',
            name='certificate_type',
            field=models.CharField(choices=[('bonafide', 'Bonafide Certificate'), ('fee', 'Paid / Unpaid Fee Certificate'), ('demand', 'Demand Letter'), ('fee_structure', 'Fee Structure Certificate')], db_index=True, default='bonafide', max_length=16),
        ),
    ]
