# Generated by Django 3.1.5 on 2026-10-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0059_demand_and_fee_structure_certificate_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandLetterBankAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_fee_account', models.JSONField(blank=True, default=dict)),
                ('mess_fee_account', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'DemandLetterBankAccounts',
            },
        ),
    ]
