# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-08 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_hostel', '0002_auto_20190908_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetail',
            name='visitor',
        ),
    ]
