# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-08 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_hostel', '0003_auto_20190908_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='room',
        ),
    ]
