# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_hostel', '0003_remove_roomdetail_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='thevisitor',
            field=models.ManyToManyField(blank=True, to='visitor_hostel.VisitorDetail'),
        ),
    ]
