# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-08 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_hostel', '0004_remove_bill_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='room',
            field=models.ManyToManyField(to='visitor_hostel.RoomDetail'),
        ),
    ]
