# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-08 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_hostel', '0004_roomdetail_thevisitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomdetail',
            old_name='thevisitor',
            new_name='visitor',
        ),
    ]
