# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-08 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_hostel', '0005_bill_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_room',
            fields=[
                ('br_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_count', models.IntegerField(default=0)),
                ('visitor_category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('person_count', models.IntegerField(default=1)),
                ('purpose', models.TextField()),
                ('booking_from', models.DateField()),
                ('Booking_to', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('remark', models.CharField(max_length=40)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('visitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_hostel.VisitorDetail')),
            ],
        ),
        migrations.RemoveField(
            model_name='roomdetail',
            name='visitor',
        ),
        migrations.AlterField(
            model_name='bill',
            name='room',
            field=models.ManyToManyField(to='visitor_hostel.Book_room'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='rooms',
            field=models.ManyToManyField(to='visitor_hostel.Book_room'),
        ),
        migrations.AlterField(
            model_name='mealrecord',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='visitor_hostel.Book_room'),
        ),
        migrations.DeleteModel(
            name='RoomDetail',
        ),
    ]
