# Generated by Django 3.1.5
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_hostel', '0005_bill_payment_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybill',
            name='bill_photo',
            field=models.ImageField(blank=True, help_text='Bill photo is required for inventory replenishment', null=True, upload_to='inventory_bills/'),
        ),
    ]