# Generated by Django 3.1.5 on 2026-04-21 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitor_hostel', '0006_add_bill_photo_to_inventory_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInCheckOutAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('no_show', 'No-Show'), ('due_checkout', 'Due Checkout')], help_text='Type of alert: no_show or due_checkout', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='pending', help_text='Alert status: pending, acknowledged, resolved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When alert was created')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When alert was acknowledged by staff', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When alert was resolved', null=True)),
                ('message', models.TextField(help_text='Alert message describing the situation')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Alert severity level', max_length=10)),
                ('acknowledgment_remarks', models.TextField(blank=True, help_text='Remarks when acknowledging the alert')),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='Staff member who acknowledged the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_vh_alerts', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='visitor_hostel.bookingdetail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='checkincheckoutalert',
            index=models.Index(fields=['booking', 'alert_type', 'status'], name='visitor_hos_booking_474fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='checkincheckoutalert',
            index=models.Index(fields=['status', 'created_at'], name='visitor_hos_status_8fc60e_idx'),
        ),
    ]
