# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-08 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_hostel', '0006_auto_20190908_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=4, unique=True)),
                ('room_type', models.CharField(choices=[('SingleBed', 'SingleBed'), ('DoubleBed', 'DoubleBed'), ('VIP', 'VIP')], max_length=12)),
                ('room_floor', models.CharField(choices=[('GroundFloor', 'GroundFloor'), ('FirstFloor', 'FirstFloor'), ('SecondFloor', 'SecondFloor'), ('ThirdFloor', 'ThirdFloor')], max_length=12)),
                ('room_status', models.CharField(choices=[('Booked', 'Booked'), ('CheckedIn', 'CheckedIn'), ('Available', 'Available'), ('UnderMaintenance', 'UnderMaintenance')], default='Available', max_length=20)),
                ('visitor', models.ManyToManyField(blank=True, to='visitor_hostel.VisitorDetail')),
            ],
        ),
        migrations.RemoveField(
            model_name='book_room',
            name='visitor_id',
        ),
        migrations.AlterField(
            model_name='bill',
            name='room',
            field=models.ManyToManyField(to='visitor_hostel.RoomDetail'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='rooms',
            field=models.ManyToManyField(to='visitor_hostel.RoomDetail'),
        ),
        migrations.AlterField(
            model_name='mealrecord',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='visitor_hostel.RoomDetail'),
        ),
        migrations.DeleteModel(
            name='Book_room',
        ),
    ]
