# Generated by Django 3.0.6 on 2020-06-04 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateIssued', models.DateField()),
                ('dateConstructionStarted', models.DateField(blank=True, null=True)),
                ('dateConstructionCompleted', models.DateField(blank=True, null=True)),
                ('dateOperational', models.DateField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('constructionCostEstimated', models.IntegerField(blank=True, null=True)),
                ('constructionCostActual', models.IntegerField(blank=True, null=True)),
                ('numRooms', models.IntegerField(blank=True, null=True)),
                ('numWashrooms', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contractorName', models.CharField(max_length=100)),
                ('dateIssued', models.DateField()),
                ('dateStarted', models.DateField(blank=True, null=True)),
                ('dateCompleted', models.DateField(blank=True, null=True)),
                ('costEstimated', models.IntegerField(blank=True, null=True)),
                ('costActual', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_module.Estate')),
                ('workType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_module.WorkType')),
            ],
        ),
        migrations.CreateModel(
            name='SubWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateIssued', models.DateField()),
                ('dateStarted', models.DateField(blank=True, null=True)),
                ('dateCompleted', models.DateField(blank=True, null=True)),
                ('costEstimated', models.IntegerField(blank=True, null=True)),
                ('costActual', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_module.Work')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dateOrdered', models.DateField()),
                ('dateReceived', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_module.Estate')),
                ('inventoryType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_module.InventoryType')),
            ],
        ),
    ]
