# Generated by Django 3.0.6 on 2020-06-04 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estate_module.Work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='workType',
            field=models.CharField(choices=[('CW', 'Construction Work'), ('MW', 'Maintenance Work')], default='MW', max_length=2),
        ),
    ]
