# Generated by Django 3.0.7 on 2020-07-11 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate_module', '0002_inventoryconsumable_inventorynonconsumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorynonconsumable',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
