# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-13 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_auto_20191113_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_details',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=300),
        ),
    ]
