# Generated by Django 3.1.5 on 2024-10-31 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
        ('placement_cell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextRoundInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField(default=1)),
                ('test_type', models.CharField(default='Interview', max_length=20)),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_cell.placementschedule')),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(default='Pending', max_length=20)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_cell.placementschedule')),
                ('unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'unique_together': {('schedule_id', 'unique_id')},
            },
        ),
    ]
