# Generated by Django 3.1.5 on 2023-03-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_cell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='unique_id',
            new_name='unique',
        ),
    ]
