# Generated by Django 3.1.5 on 2026-02-21 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_information', '0002_auto_20260221_2129'),
        ('placement_cell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('domain', models.CharField(blank=True, help_text='Industry domain, e.g., IT, Finance, Manufacturing', max_length=200, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_email', models.EmailField(max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='placement/company_logos/')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_companies', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, help_text='The TPO/user who registered this company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('OFFER_EXTENDED', 'Offer Extended'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume_link', models.FileField(blank=True, null=True, upload_to='documents/placement/resumes/')),
                ('remarks', models.TextField(blank=True, help_text='Remarks by TPO or Company', max_length=500, null=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('max_offers_allowed', models.IntegerField(default=1, help_text='Maximum active offers a student can hold at a time')),
                ('allow_dream_company', models.BooleanField(default=False, help_text='Allow students to apply to dream companies after being placed')),
                ('dream_ctc_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Minimum CTC (LPA) for dream company classification', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Placement Policies',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title / role name', max_length=200)),
                ('description', models.TextField(max_length=3000)),
                ('job_type', models.CharField(choices=[('PLACEMENT', 'Placement'), ('INTERNSHIP', 'Internship'), ('PBI', 'PBI')], default='PLACEMENT', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('ctc', models.DecimalField(decimal_places=2, help_text='CTC / Stipend in LPA', max_digits=10)),
                ('bond_details', models.TextField(blank=True, max_length=500, null=True)),
                ('min_cpi', models.FloatField(default=0.0, help_text='Minimum CPI required')),
                ('eligible_programmes', models.CharField(blank=True, help_text='Comma-separated: B.Tech,M.Tech,B.Des,M.Des,PhD', max_length=200, null=True)),
                ('eligible_branches', models.CharField(blank=True, help_text='Comma-separated: CSE,ECE,ME,SM,DESIGN', max_length=300, null=True)),
                ('eligible_batch_from', models.IntegerField(blank=True, help_text='Minimum batch year (e.g., 2022)', null=True)),
                ('eligible_batch_to', models.IntegerField(blank=True, help_text='Maximum batch year (e.g., 2026)', null=True)),
                ('backlog_allowed', models.BooleanField(default=False)),
                ('application_deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='documents/placement/job_postings/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='placement_cell.company')),
                ('posted_by', models.ForeignKey(blank=True, help_text='TPO who posted this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('required_skills', models.ManyToManyField(blank=True, related_name='required_for_jobs', to='placement_cell.Skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc_offered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('designation_offered', models.CharField(blank=True, max_length=200, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='documents/placement/offer_letters/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('response_deadline', models.DateTimeField(help_text='Deadline for student to accept/reject')),
                ('extended_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='placement_cell.jobapplication')),
            ],
            options={
                'ordering': ['-extended_at'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placement_cell.jobposting'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='academic_information.student'),
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=10)),
                ('venue_or_link', models.CharField(blank=True, help_text='Physical venue or online meeting link', max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='placement_cell.jobposting')),
            ],
            options={
                'ordering': ['date', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=3000)),
                ('announcement_type', models.CharField(choices=[('PLACEMENT_DRIVE', 'Placement Drive'), ('COMPANY_VISIT', 'Company Visit'), ('TRAINING_SESSION', 'Training Session'), ('WORKSHOP', 'Workshop'), ('INTERNSHIP', 'Internship Program'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('target_audience', models.CharField(blank=True, help_text='Comma-separated: ALL,B.Tech,M.Tech,CSE,ECE etc.', max_length=200, null=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='documents/placement/announcements/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job_posting', 'student')},
        ),
        migrations.CreateModel(
            name='InterviewPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('result', models.CharField(blank=True, help_text='SELECTED / REJECTED / WAITLISTED', max_length=20, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_panels', to='placement_cell.jobapplication')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelists', to='placement_cell.interviewschedule')),
            ],
            options={
                'unique_together': {('interview', 'application')},
            },
        ),
    ]
