# Generated by Django 3.1.5 on 2025-04-12 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_student_hall_id'),
        ('placement_cell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('web_url', models.URLField()),
                ('company_logo', models.ImageField(upload_to='placement_cell/company_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('field_type', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NextRoundInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField(default=1)),
                ('test_type', models.CharField(default='Interview', max_length=20)),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_cell.placementschedule')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalRestrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('value', models.JSONField(default=dict)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'unique_together': {('criteria', 'condition', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('passout_year', models.IntegerField(blank=True, default=-1, null=True)),
                ('branch', models.CharField(blank=True, default='All', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, default='All', max_length=20, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_cell.notifystudent')),
            ],
        ),
        migrations.CreateModel(
            name='DebarStudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('unique_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
        migrations.AddField(
            model_name='placementschedule',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placement_cell.company_registration'),
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(default='Pending', max_length=20)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_cell.placementschedule')),
                ('unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'unique_together': {('schedule_id', 'unique_id')},
            },
        ),
        migrations.CreateModel(
            name='PlacementForm_responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(default=dict)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_cell.placementschedule')),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_cell.customfield')),
                ('unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'unique_together': {('company_id', 'unique_id', 'field_id')},
            },
        ),
        migrations.CreateModel(
            name='Placementform_fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_cell.placementschedule')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_cell.customfield')),
            ],
            options={
                'unique_together': {('company_id', 'custom_field')},
            },
        ),
    ]
