# Generated by Django 3.1.5 on 2023-03-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_cell', '0002_auto_20230328_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='unique',
            new_name='unique_id',
        ),
    ]
