# Generated by Django 3.1.5 on 2025-01-16 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
        ('placement_cell', '0002_nextroundinfo_studentapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebarStudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('unique_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
    ]
