# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-08 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_cell', '0002_remove_placementstatus_no_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementstatus',
            name='no_of_days',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
