# Generated by Django 3.1.5 on 2023-04-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_cell', '0002_placementrecord_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementrecord',
            name='branch',
            field=models.CharField(default='', max_length=100),
        ),
    ]
