# Generated by Django 3.1.5 on 2023-01-27 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20230127_1556'),
        ('placement_cell', '0003_auto_20230124_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementrecord',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='globals.extrainfo'),
        ),
    ]
