# Generated by Django 3.1.5 on 2023-04-06 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_cell', '0003_placementrecord_branch'),
        ('placement_cell', '0002_placementrecord_unique_id'),
    ]

    operations = [
    ]
