# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-08 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_cell', '0003_placementstatus_no_of_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='unique_id',
            new_name='unique',
        ),
    ]
