# Generated by Django 3.1.5 on 2025-03-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement_cell', '0004_company_registration_customfield_eligibility_globalrestrictions_placementform_fields_placementform_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementform_responses',
            name='value',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='placementschedule',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placement_cell.company_registration'),
        ),
        migrations.AlterField(
            model_name='placementform_fields',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_cell.placementschedule'),
        ),
        migrations.AlterField(
            model_name='placementform_responses',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_cell.placementschedule'),
        ),
    ]
