# Generated by Django 3.1.5 on 2023-01-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_auto_20230127_1631'),
        ('placement_cell', '0004_auto_20230127_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementrecord',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='globals.extrainfo'),
        ),
    ]
