# Generated by Django 3.1.5 on 2023-01-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_cell', '0006_auto_20230127_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
