# Generated by Django 3.1.5 on 2026-06-21 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0006_auto_20260304_0836'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placement_cell', '0013_sync_index_names_and_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_pinned', '-posted_at'),
            },
        ),
        migrations.CreateModel(
            name='OffCampusPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=200)),
                ('offer_type', models.CharField(choices=[('placement', 'Placement'), ('internship', 'Internship')], default='placement', max_length=20)),
                ('ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stipend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_offcampus_placements', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offcampus_placements', to='globals.extrainfo')),
            ],
            options={
                'ordering': ('-offer_date', '-id'),
            },
        ),
    ]
