# Generated by Django 3.1.5 on 2026-06-21 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placement_cell', '0014_offcampusplacement_placementannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementCalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('event', 'Event'), ('drive', 'Drive'), ('test', 'Online Test'), ('interview', 'Interview'), ('deadline', 'Deadline'), ('other', 'Other')], default='event', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('start', 'id'),
            },
        ),
    ]
