# Generated by Django 3.1.5 on 2026-09-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0010_normalize_phd_programme'),
        ('placement_cell', '0015_placementcalendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(default='', max_length=200)),
                ('bank_name', models.CharField(default='', max_length=200)),
                ('branch_name', models.CharField(blank=True, default='', max_length=200)),
                ('account_number', models.CharField(default='', max_length=30)),
                ('ifsc_code', models.CharField(default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='academic_information.student')),
            ],
        ),
    ]
