# Generated by Django 3.1.5 on 2024-11-06 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globals', '0002_auto_20241007_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=200)),
                ('target_group', models.CharField(choices=[('faculty', 'Faculty'), ('students', 'Students'), ('all', 'All Staff and Students'), ('specific_users', 'Specific Users')], max_length=20)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('upload_announcement', models.FileField(default=' ', null=True, upload_to='notifications/upload_announcement')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globals.departmentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notification.announcements')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo')),
            ],
        ),
    ]
