# Generated by Django 3.1.5 on 2024-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='module',
            field=models.CharField(default='Fusion', max_length=200),
        ),
    ]
