# Generated by Django 3.1.5 on 2026-04-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_assignment7_implementation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='announcements',
            name='notification_announ_is_acti_idx',
        ),
        migrations.RemoveIndex(
            model_name='announcements',
            name='notification_announ_expiry_idx',
        ),
        migrations.AlterField(
            model_name='registeredmodule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='announcements',
            index=models.Index(fields=['is_active', 'is_published'], name='notificatio_is_acti_63390e_idx'),
        ),
        migrations.AddIndex(
            model_name='announcements',
            index=models.Index(fields=['expiry_date'], name='notificatio_expiry__bb3b14_idx'),
        ),
    ]
