# Generated by Django 3.1.5 on 2023-03-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='end_time',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='start_time',
            field=models.TimeField(default='20:00'),
        ),
    ]
