# Generated by Django 3.1.5 on 2023-03-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hall_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
