# Generated by Django 3.1.5 on 2025-03-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hall_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
