# Generated by Django 3.1.5 on 2024-04-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hall_no',
        ),
        migrations.AddField(
            model_name='student',
            name='hall_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
