# Generated by Django 3.1.5 on 2023-04-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hall_id',
            field=models.CharField(blank=True, choices=[('saraswati', 'saraswati'), ('vivekananda', 'vivekananda'), ('aryabhatta', 'aryabhatta'), ('vashishtha', 'vashishtha')], max_length=255, null=True),
        ),
    ]
