# Generated by Django 3.1.5 on 2024-04-16 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programme_curriculum', '0001_initial'),
        ('academic_information', '0001_initial'),
        ('globals', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.batch'),
        ),
        migrations.AddField(
            model_name='spi',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='grades',
            name='curriculum_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.curriculum'),
        ),
        migrations.AddField(
            model_name='grades',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='curriculum_instructor',
            name='curriculum_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.curriculum'),
        ),
        migrations.AddField(
            model_name='curriculum_instructor',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.course'),
        ),
        migrations.AlterUniqueTogether(
            name='spi',
            unique_together={('student_id', 'sem')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculum_instructor',
            unique_together={('curriculum_id', 'instructor_id')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('course_code', 'batch', 'programme')},
        ),
    ]
