# Generated by Django 3.1.5 on 2026-03-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=20)),
                ('instructor_id', models.IntegerField()),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'course_attendance',
                'unique_together': {('student_id', 'course_code', 'instructor_id', 'date')},
            },
        ),
    ]
