# Generated by Django 3.1.5 on 2026-03-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_thesis_registration_models'),
        ('academic_information', '0002_auto_20260210_1820'),
    ]

    operations = [
    ]
