# Generated by Django 3.1.5 on 2025-04-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_student_hall_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hall_id',
        ),
    ]
