# Generated by Django 3.1.5 on 2023-03-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_auto_20230321_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='start',
            new_name='start_time',
        ),
    ]
