# Generated by Django 3.1.5 on 2026-07-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_auto_20260210_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2, null=True),
        ),
    ]
