# Generated by Django 3.1.5 on 2024-04-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_auto_20240409_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hall_id',
        ),
        migrations.AddField(
            model_name='student',
            name='hall_no',
            field=models.IntegerField(default=0),
        ),
    ]
