# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-13 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_auto_20191113_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=600),
        ),
    ]
