# Generated by Django 3.1.5 on 2026-08-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_merge_20260314_1604'),
        ('academic_information', '0003_student_section'),
    ]

    operations = [
    ]
