# Generated by Django 3.1.5 on 2023-03-29 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_auto_20230328_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='end_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
