# Generated by Django 3.1.5 on 2026-08-03 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programme_curriculum', '0045_rename_progress_seminar_to_seminar'),
        ('globals', '0008_announcement'),
        ('academic_information', '0003_merge_20260314_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='audience_type',
            field=models.CharField(choices=[('all', 'Everyone'), ('role', 'Specific Role'), ('batch', 'Specific Batch'), ('department', 'Specific Department'), ('individual', 'Specific Individuals')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='calendar',
            name='target_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.batch'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='globals.departmentinfo'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='target_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='globals.designation'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='targeted_calendar_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
