# Generated by Django 3.1.5 on 2023-03-25 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_auto_20230325_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='hall_name',
            new_name='hall_id',
        ),
    ]
