# Generated by Django 3.1.5 on 2023-03-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0004_auto_20230325_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hall_id',
            field=models.CharField(blank=True, choices=[('saraswati', 'saraswati'), ('vivekananda', 'vivekananda'), ('aryabhatta', 'aryabhatta'), ('vashishtha', 'vashishtha')], max_length=255, null=True),
        ),
    ]
