# Generated by Django 3.1.5 on 2025-04-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_remove_student_hall_id'),
        ('academic_information', '0004_add_student_hall_id'),
    ]

    operations = [
    ]
