# Generated by Django 3.1.5 on 2026-08-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_student_section'),
        ('academic_information', '0004_auto_20260803_0930'),
    ]

    operations = [
    ]
