# Generated by Django 3.1.5 on 2026-08-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0004_merge_20260805_2216'),
        ('academic_information', '0005_merge_20260804_2335'),
    ]

    operations = [
    ]
