# Generated by Django 3.1.5 on 2021-04-22 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0001_initial'),
        ('academic_information', '0005_auto_20200522_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.batch'),
        ),
        migrations.AddField(
            model_name='student',
            name='curr_semester_no',
            field=models.IntegerField(default=1),
        ),
    ]
