# Generated by Django 3.1.5 on 2026-08-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0006_merge_20260805_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
