# Generated by Django 3.1.5 on 2026-08-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0007_auto_20260807_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_ews',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_pwd',
            field=models.BooleanField(default=False),
        ),
    ]
