# Generated by Django 3.1.5 on 2026-08-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0008_student_ews_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
