# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-29 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0004_auto_20191113_0334'),
        ('gymkhana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting_choices',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=500)),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-votes'],
            },
        ),
        migrations.CreateModel(
            name='Voting_polls',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exp_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Voting_voters',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50)),
                ('poll_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymkhana.Voting_polls')),
            ],
        ),
        migrations.AddField(
            model_name='voting_choices',
            name='poll_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymkhana.Voting_polls'),
        ),
    ]
