# Generated by Django 3.1.5 on 2024-10-13 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('budget_for', models.CharField(max_length=256)),
                ('budget_amt', models.IntegerField(default=0)),
                ('budget_file', models.FileField(upload_to='uploads/')),
                ('description', models.TextField(max_length=256)),
                ('status', models.CharField(choices=[('ACCEPT', 'Accepted'), ('REJECT', 'Rejected'), ('COORDINATOR', 'Coordinator Review'), ('FIC', 'FIC Review'), ('COUNSELLOR', 'Counsellor Review'), ('DEAN', 'Dean Review')], default='COORDINATOR', max_length=50)),
                ('remarks', models.CharField(max_length=256, null=True)),
                ('club', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='gymkhana.club_info')),
            ],
            options={
                'db_table': 'Budget',
            },
        ),
        migrations.CreateModel(
            name='Budget_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_designation', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('comment_date', models.DateField(default=django.utils.timezone.now)),
                ('comment_time', models.TimeField(default=django.utils.timezone.now)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gymkhana.budget')),
            ],
            options={
                'db_table': 'Budget_Comments',
            },
        ),
        migrations.CreateModel(
            name='Event_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_designation', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('comment_date', models.DateField(default=django.utils.timezone.now)),
                ('comment_time', models.TimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Event_Comments',
            },
        ),
        migrations.RemoveField(
            model_name='voting_choices',
            name='poll_event',
        ),
        migrations.RemoveField(
            model_name='voting_voters',
            name='poll_event',
        ),
        migrations.RenameField(
            model_name='event_info',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='event_info',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='status',
            field=models.CharField(choices=[('ACCEPT', 'Accepted'), ('REJECT', 'Rejected'), ('COORDINATOR', 'Coordinator Review'), ('FIC', 'FIC Review'), ('COUNSELLOR', 'Counsellor Review'), ('DEAN', 'Dean Review')], default='open', max_length=50),
        ),
        migrations.DeleteModel(
            name='Core_team',
        ),
        migrations.DeleteModel(
            name='Voting_choices',
        ),
        migrations.DeleteModel(
            name='Voting_polls',
        ),
        migrations.DeleteModel(
            name='Voting_voters',
        ),
        migrations.AddField(
            model_name='event_comments',
            name='Event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gymkhana.event_info'),
        ),
    ]
