# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-03 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0001_initial'),
    ]
