# Generated by Django 3.1.5 on 2024-02-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_info',
            name='created_on',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='club_info',
            name='head_changed_on',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='registration_form',
            name='roll',
            field=models.CharField(default='20160017', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session_info',
            name='end_time',
            field=models.TimeField(default=None),
        ),
    ]
