# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-05 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_info',
            name='event_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='incharge',
            field=models.CharField(max_length=256),
        ),
    ]
