# Generated by Django 3.1.5 on 2023-04-10 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_info',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='club_info',
            name='head_changed_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
