# Generated by Django 3.1.5 on 2025-04-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filetracking', '0001_initial'),
        ('gymkhana', '0002_auto_20250413_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='file_id',
            field=models.ForeignKey(default=615, on_delete=django.db.models.deletion.CASCADE, to='filetracking.file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_info',
            name='file_id',
            field=models.ForeignKey(default=615, on_delete=django.db.models.deletion.CASCADE, to='filetracking.file'),
            preserve_default=False,
        ),
    ]
