# Generated by Django 3.1.5 on 2024-10-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0002_auto_20241013_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='change_office',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('member', 'Member'), ('co-ordinator', 'Co-ordinator'), ('Co-cordinator', 'Co-cordinator')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='club_budget',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('member', 'Member'), ('co-ordinator', 'Co-ordinator'), ('Co-cordinator', 'Co-cordinator')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='club_info',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('member', 'Member'), ('co-ordinator', 'Co-ordinator'), ('Co-cordinator', 'Co-cordinator')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='club_member',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('member', 'Member'), ('co-ordinator', 'Co-ordinator'), ('Co-cordinator', 'Co-cordinator')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='fest_budget',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('member', 'Member'), ('co-ordinator', 'Co-ordinator'), ('Co-cordinator', 'Co-cordinator')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='session_info',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('member', 'Member'), ('co-ordinator', 'Co-ordinator'), ('Co-cordinator', 'Co-cordinator')], default='open', max_length=50),
        ),
    ]
