# Generated by Django 3.1.5 on 2024-02-16 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0002_auto_20240214_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_info',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='club_info',
            name='head_changed_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
