# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-04 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0002_registration_form'),
    ]
