# Generated by Django 3.1.5 on 2023-04-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0002_auto_20230411_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club_info',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='club_info',
            name='head_changed_on',
        ),
    ]
