# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-05 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0003_auto_20200604_1737'),
    ]
