# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-29 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0003_auto_20200529_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting_polls',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
    ]
