# Generated by Django 3.1.5 on 2025-04-21 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filetracking', '0001_initial'),
        ('gymkhana', '0003_auto_20250415_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('ACCEPT', 'Accepted'), ('REJECT', 'Rejected'), ('COORDINATOR', 'Coordinator Review'), ('FIC', 'FIC Review'), ('COUNSELLOR', 'Counsellor Review'), ('DEAN', 'Dean Review'), ('REREVIEW', 'ReReview')], default='COORDINATOR', max_length=50)),
                ('file_link', models.CharField(max_length=255)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymkhana.club_info')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filetracking.file')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyPlanEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('tentative_start_date', models.DateField()),
                ('tentative_end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('yearly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='gymkhana.yearlyplan')),
            ],
        ),
    ]
