# Generated by Django 3.1.5 on 2024-02-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0003_auto_20240216_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_info',
            name='created_on',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='club_info',
            name='head_changed_on',
            field=models.DateField(default=None, null=True),
        ),
    ]
