# Generated by Django 3.1.5 on 2024-10-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0003_auto_20241016_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('achievement', models.TextField()),
            ],
            options={
                'db_table': 'Achievements',
            },
        ),
    ]
