# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-29 23:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0004_auto_20200529_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voting_polls',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='voting_polls',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 23, 2, 15, 763378)),
        ),
    ]
