# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-05 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0004_auto_20200605_0924'),
    ]
