# Generated by Django 3.1.5 on 2024-02-16 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0004_auto_20240216_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_info',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
