# Generated by Django 3.1.5 on 2024-10-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0004_achievements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_comments',
            old_name='Event_id',
            new_name='event_id',
        ),
    ]
