# Generated by Django 3.1.5 on 2024-02-17 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0005_auto_20240216_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_info',
            name='head_changed_on',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
