# Generated by Django 3.1.5 on 2024-10-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0005_auto_20241017_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('FIC', 'FIC'), ('COORDINATOR', 'Coordinator'), ('TECHNICAL_COUNSELLOR', 'Technical counsellor'), ('SPORTS_COUNSELLOR', 'Sports counsellor'), ('CULTURAL_COUNSELLOR', 'Cultural counsellor')], max_length=50)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymkhana.club_info')),
            ],
            options={
                'db_table': 'ClubPosition',
            },
        ),
    ]
