# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-29 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0005_auto_20200529_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting_polls',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
