# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-08 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0005_auto_20200605_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default='True', max_length=5)),
            ],
            options={
                'db_table': 'Form_available',
            },
        ),
    ]
