# Generated by Django 3.1.5 on 2025-02-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0006_clubposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=256, null=True)),
                ('date', models.DateField(default=None)),
                ('link', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'fest',
            },
        ),
    ]
