# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-08 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0006_form_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_available',
            name='id',
        ),
        migrations.AddField(
            model_name='form_available',
            name='roll',
            field=models.CharField(default=2016001, max_length=7, primary_key=True, serialize=False),
        ),
    ]
