# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-01 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0006_auto_20200529_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voting_choices',
            options={},
        ),
    ]
