# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-01 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0007_auto_20200601_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voting_choices',
            options={'get_latest_by': 'votes'},
        ),
    ]
