# Generated by Django 3.1.5 on 2025-02-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0007_fest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fest',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Sports', 'Sports'), ('Cultural', 'Cultural')], max_length=50),
        ),
    ]
