# Generated by Django 3.1.5 on 2025-03-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0008_auto_20250217_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('images', models.ImageField(null=True, upload_to='gymkhana/event_images')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymkhana.event_info')),
            ],
        ),
    ]
