# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0008_auto_20200601_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting_polls',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='voting_polls',
            name='exp_date',
        ),
    ]
