# Generated by Django 3.1.5 on 2025-03-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0009_eventinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(max_length=100)),
                ('incharge', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_announcement', models.TextField(blank=True, null=True)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='event_reports/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymkhana.event_info')),
            ],
            options={
                'db_table': 'EventReport',
            },
        ),
    ]
