# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0010_auto_20200602_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting_polls',
            name='groups',
            field=models.CharField(default='{}', max_length=500),
        ),
    ]
