# Generated by Django 3.1.5 on 2025-03-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0010_eventreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget_amt',
            new_name='budget_requested',
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_allocated',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_comment',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('ACCEPT', 'Accepted'), ('REJECT', 'Rejected'), ('COORDINATOR', 'Coordinator Review'), ('FIC', 'FIC Review'), ('COUNSELLOR', 'Counsellor Review'), ('DEAN', 'Dean Review'), ('REREVIEW', 'ReReview')], default='COORDINATOR', max_length=50),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='status',
            field=models.CharField(choices=[('ACCEPT', 'Accepted'), ('REJECT', 'Rejected'), ('COORDINATOR', 'Coordinator Review'), ('FIC', 'FIC Review'), ('COUNSELLOR', 'Counsellor Review'), ('DEAN', 'Dean Review'), ('REREVIEW', 'ReReview')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='venue',
            field=models.CharField(choices=[('CR101', 'CR101'), ('CR102', 'CR102'), ('CR103', 'CR103'), ('CR104', 'CR104'), ('CR107', 'CR107'), ('CR108', 'CR108'), ('CR109', 'CR109'), ('CR201', 'CR201'), ('CR202', 'CR202'), ('CR208', 'CR208'), ('L101', 'L101'), ('L102', 'L102'), ('L103', 'L103'), ('L104', 'L104'), ('L105', 'L105'), ('L106', 'L106'), ('L107', 'L107'), ('L108', 'L108'), ('L201', 'L201'), ('L202', 'L202'), ('L206', 'L206'), ('L207', 'L207'), ('Football Ground', 'Football Ground'), ('Cricket Ground', 'Cricket Ground'), ('Basketball Ground', 'Basketball Ground'), ('Volleyball Ground', 'Volleyball Ground'), ('Tennis Court', 'Tennis Court'), ('Athletics Ground', 'Athletics Ground'), ('Badminton Court', 'Badminton Court'), ('Table Tennis Court', 'Table Tennis Court'), ('Chess Room', 'Chess Room'), ('Carrom Room', 'Carrom Room'), ('Gym', 'Gym'), ('CC First Floor', 'CC First Floor'), ('CC Second Floor', 'CC Second Floor'), ('CC Third Floor', 'CC Third Floor'), ('OAT', 'OAT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session_info',
            name='venue',
            field=models.CharField(choices=[('CR101', 'CR101'), ('CR102', 'CR102'), ('CR103', 'CR103'), ('CR104', 'CR104'), ('CR107', 'CR107'), ('CR108', 'CR108'), ('CR109', 'CR109'), ('CR201', 'CR201'), ('CR202', 'CR202'), ('CR208', 'CR208'), ('L101', 'L101'), ('L102', 'L102'), ('L103', 'L103'), ('L104', 'L104'), ('L105', 'L105'), ('L106', 'L106'), ('L107', 'L107'), ('L108', 'L108'), ('L201', 'L201'), ('L202', 'L202'), ('L206', 'L206'), ('L207', 'L207'), ('Football Ground', 'Football Ground'), ('Cricket Ground', 'Cricket Ground'), ('Basketball Ground', 'Basketball Ground'), ('Volleyball Ground', 'Volleyball Ground'), ('Tennis Court', 'Tennis Court'), ('Athletics Ground', 'Athletics Ground'), ('Badminton Court', 'Badminton Court'), ('Table Tennis Court', 'Table Tennis Court'), ('Chess Room', 'Chess Room'), ('Carrom Room', 'Carrom Room'), ('Gym', 'Gym'), ('CC First Floor', 'CC First Floor'), ('CC Second Floor', 'CC Second Floor'), ('CC Third Floor', 'CC Third Floor'), ('OAT', 'OAT')], max_length=50),
        ),
    ]
