# Generated by Django 3.0.6 on 2020-06-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0011_voting_polls_groups'),
        ('gymkhana', '0002_auto_20200522_1851'),
    ]

    operations = [
    ]
