# Generated by Django 3.0.6 on 2020-06-05 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0012_merge_20200603_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=256)),
                ('venue', models.CharField(choices=[('Classroom', (('CR101', 'CR101'), ('CR102', 'CR102'))), ('Lecturehall', (('L101', 'L101'), ('L102', 'L102')))], max_length=50)),
                ('incharge', models.CharField(max_length=256)),
                ('date', models.DateField(default=None)),
                ('start_time', models.TimeField(default=None)),
                ('end_time', models.TimeField(default=None, null=True)),
                ('event_poster', models.FileField(blank=True, upload_to='gymkhana/event_poster')),
                ('details', models.TextField(max_length=256, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='open', max_length=50)),
                ('club', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymkhana.Club_info')),
            ],
            options={
                'db_table': 'Event_info',
            },
        ),
    ]
