# Generated by Django 3.0.6 on 2020-06-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0005_auto_20200605_0937'),
        ('gymkhana', '0013_event_info'),
    ]

    operations = [
    ]
