# Generated by Django 3.0.6 on 2020-06-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0014_merge_20200606_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_form',
            fields=[
                ('roll', models.CharField(default='2016001', max_length=7, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='Student', max_length=40)),
                ('branch', models.CharField(default='open', max_length=20)),
                ('cpi', models.FloatField(default=6.0, max_length=3)),
                ('programme', models.CharField(default='B.tech', max_length=20)),
            ],
            options={
                'db_table': 'Registration_form',
            },
        ),
    ]
