# Generated by Django 3.0.7 on 2020-06-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0015_registration_form'),
        ('gymkhana', '0002_auto_20200605_2047'),
    ]

    operations = [
    ]
