# Generated by Django 3.0.7 on 2020-06-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0007_auto_20200608_2210'),
        ('gymkhana', '0016_merge_20200610_2238'),
    ]

    operations = [
    ]
