# Generated by Django 3.0.7 on 2020-06-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0017_merge_20200611_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_info',
            name='session_poster',
            field=models.FileField(null=True, upload_to='gymkhana/session_poster'),
        ),
    ]
