# Generated by Django 3.0.7 on 2020-06-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0018_auto_20200611_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_available',
            name='status',
            field=models.BooleanField(default=True, max_length=5),
        ),
    ]
