# Generated by Django 3.0.7 on 2020-06-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0019_auto_20200613_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_available',
            name='form_name',
            field=models.CharField(default='senate_registration', max_length=30),
        ),
    ]
