# Generated by Django 3.0.7 on 2020-06-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0020_form_available_form_name'),
        ('gymkhana', '0019_auto_20200613_1945'),
    ]

    operations = [
    ]
