# Generated by Django 3.0.7 on 2020-07-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0021_merge_20200615_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_info',
            name='session_poster',
            field=models.ImageField(null=True, upload_to='gymkhana/session_poster'),
        ),
    ]
