# Generated by Django 3.1.5 on 2024-10-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveformtable',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='leaveformtable',
            name='rejected',
        ),
        migrations.AddField(
            model_name='leaveformtable',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveformtable',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
    ]
