# Generated by Django 3.1.5 on 2024-04-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0001_initial'),
    ]

    operations = [
    ]
