# Generated by Django 3.1.5 on 2024-04-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_clear',
        # ),
        # migrations.RemoveField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_notclear',
        # ),
    ]
