# Generated by Django 3.1.5 on 2024-10-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0002_auto_20241018_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonafideformtableupdated',
            name='approve',
        ),
        migrations.RemoveField(
            model_name='bonafideformtableupdated',
            name='reject',
        ),
        migrations.AddField(
            model_name='bonafideformtableupdated',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
