# Generated by Django 3.1.5 on 2024-02-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0006_auto_20240220_0901'),
        ('otheracademic', '0002_graduateseminarform'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonafideFormTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('branch_type', models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Smart Manufacturing', 'Smart Manufacturing'), ('Electroctics and Communication Engineering', 'Electronic and Communication Engineering'), ('Design', 'Design')], max_length=50)),
                ('semester_type', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=20)),
                ('purpose', models.TextField()),
                ('date_of_application', models.DateField()),
                ('approved', models.BooleanField()),
                ('rejected', models.BooleanField()),
                ('download_file', models.FileField(blank=True, upload_to='')),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo')),
            ],
            options={
                'db_table': 'BonafideFormTable',
            },
        ),
    ]
