# Generated by Django 3.1.5 on 2024-04-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0003_auto_20240416_2047'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_clear',
        # ),
        # migrations.RemoveField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_notclear',
        # ),
        migrations.AddField(
            model_name='leavepg',
            name='thesis_approved',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavepg',
            name='thesis_rejected',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavepg',
            name='thesis_supervisor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
