# Generated by Django 3.1.5 on 2024-10-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0003_auto_20241018_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafideformtableupdated',
            name='download_file',
            field=models.CharField(default='unavailable', max_length=20),
        ),
    ]
