# Generated by Django 3.1.5 on 2024-02-20 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0007_auto_20240220_0947'),
        ('otheracademic', '0003_bonafideformtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafideformtable',
            name='branch_type',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ME', 'ME'), ('SM', 'SM'), ('ECE', 'ECE'), ('Design', 'Design')], max_length=50),
        ),
        migrations.CreateModel(
            name='BonafideFormTableUpdated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_names', models.CharField(max_length=100)),
                ('branch_types', models.CharField(max_length=50)),
                ('semester_types', models.CharField(max_length=20)),
                ('purposes', models.TextField()),
                ('date_of_applications', models.DateField()),
                ('approve', models.BooleanField()),
                ('reject', models.BooleanField()),
                ('download_file', models.FileField(blank=True, upload_to='')),
                ('roll_nos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo')),
            ],
            options={
                'db_table': 'BonafideFormTableUpdated',
            },
        ),
    ]
