# Generated by Django 3.1.5 on 2024-04-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0004_auto_20240416_2112'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_clear',
        # ),
        # migrations.RemoveField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_notclear',
        # ),
        migrations.AlterField(
            model_name='leavepg',
            name='upload_file',
            field=models.FileField(default='not_available', upload_to='leave_doc'),
        ),
    ]
