# Generated by Django 3.1.5 on 2024-11-15 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0004_auto_20241018_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveformtable',
            name='status',
        ),
    ]
