# Generated by Django 3.1.5 on 2024-04-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0005_auto_20240411_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodues',
            name='acad_admin_float',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nodues',
            name='acad_credential',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodues',
            name='bank_credential',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodues',
            name='btp_credential',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodues',
            name='cse_credential',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodues',
            name='design_credential',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodues',
            name='ece_credential',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodues',
            name='hostel_credential',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodues',
            name='library_credential',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodues',
            name='me_credential',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodues',
            name='mess_credential',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodues',
            name='physics_credential',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
