# Generated by Django 3.1.5 on 2024-11-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0005_remove_leaveformtable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveformtable',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
