# Generated by Django 3.1.5 on 2024-02-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0007_auto_20240220_0947'),
        ('otheracademic', '0005_graduateseminarformtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantshipClaimForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('discipline', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('bank_account', models.CharField(max_length=100)),
                ('student_signature', models.CharField(max_length=100)),
                ('ta_supervisor', models.CharField(max_length=100)),
                ('thesis_supervisor', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('approved', models.BooleanField()),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo')),
            ],
            options={
                'db_table': 'AssistantshipClaimForm',
            },
        ),
    ]
