# Generated by Django 3.1.5 on 2024-04-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0006_auto_20240412_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafideformtableupdated',
            name='download_file',
            field=models.FileField(upload_to='Bonafide'),
        ),
    ]
