# Generated by Django 3.1.5 on 2024-04-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0006_auto_20240416_2310'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_clear',
        # ),
        # migrations.RemoveField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_notclear',
        # ),
        migrations.AddField(
            model_name='assistantshipclaimformstatusupd',
            name='remark',
            field=models.TextField(default=''),
        ),
    ]
