# Generated by Django 3.1.5 on 2024-04-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0007_auto_20240412_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantshipclaimformstatusupd',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistantshipclaimformstatusupd',
            name='full_day_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assistantshipclaimformstatusupd',
            name='half_day_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assistantshipclaimformstatusupd',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_clear',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_notclear',
        #     field=models.BooleanField(default=False),
        # ),
    ]
