# Generated by Django 3.1.5 on 2024-04-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0008_auto_20240418_0029'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_clear',
        # ),
        # migrations.RemoveField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_notclear',
        # ),
    ]
