# Generated by Django 3.1.5 on 2024-04-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0008_auto_20240412_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantshipclaimformstatusupd',
            name='hod',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_clear',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_notclear',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AlterField(
            model_name='assistantshipclaimformstatusupd',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='assistantshipclaimformstatusupd',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
