# Generated by Django 3.1.5 on 2024-04-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0009_auto_20240412_1107'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_clear',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_notclear',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AlterField(
            model_name='bonafideformtableupdated',
            name='download_file',
            field=models.FileField(default='not available', upload_to='Bonafide'),
        ),
    ]
