# Generated by Django 3.1.5 on 2024-04-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '__first__'),
        ('otheracademic', '0010_auto_20240413_0133'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_clear',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='nodues',
        #     name='discipline_office_dsa_notclear',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AlterField(
            model_name='nodues',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo'),
        ),
    ]
