# Generated by Django 3.1.5 on 2024-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='dept',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='to_dept',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='transfer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
