# Generated by Django 3.1.5 on 2023-03-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filetracking', '0001_initial'),
        ('ps1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndentFile2',
            fields=[
                ('file_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='filetracking.file')),
                ('title', models.CharField(default='', max_length=250)),
                ('budgetary_head', models.CharField(max_length=250)),
                ('expected_delivery', models.DateField()),
                ('sources_of_supply', models.CharField(max_length=250)),
                ('head_approval', models.BooleanField(default=False)),
                ('director_approval', models.BooleanField(default=False)),
                ('financial_approval', models.BooleanField(default=False)),
                ('procured', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'IndentFile2',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=250)),
                ('quantiy', models.IntegerField()),
                ('present_stock', models.IntegerField()),
                ('estimated_cost', models.IntegerField(null=True)),
                ('purpose', models.CharField(max_length=250)),
                ('specification', models.CharField(max_length=250)),
                ('indent_type', models.CharField(max_length=250)),
                ('nature', models.BooleanField(default=False)),
                ('indigenous', models.BooleanField(default=False)),
                ('replaced', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('file_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='filetracking.file')),
                ('indent_file_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ps1.indentfile2')),
            ],
            options={
                'db_table': 'Item',
            },
        ),
    ]
