# Generated by Django 3.1.5 on 2023-03-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStockAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('item_name', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('floor_no', models.IntegerField()),
                ('rooms', models.IntegerField(max_length=100)),
                ('year', models.IntegerField()),
                ('item_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ps2_global_admin',
            },
        ),
    ]
