# Generated by Django 3.1.5 on 2024-05-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indentfile',
            name='item_subtype',
            field=models.CharField(default='computers', max_length=250),
        ),
    ]
