# Generated by Django 3.1.5 on 2021-04-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='indentfile',
            table='IndentFile',
        ),
    ]
