# Generated by Django 3.1.5 on 2025-03-24 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indentfile',
            name='budgetary_head',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='expected_delivery',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='indigenous',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='item_subtype',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='present_stock',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='replaced',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='sources_of_supply',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='specification',
        ),
        migrations.AddField(
            model_name='indentfile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indentfile',
            name='indent_name',
            field=models.CharField(default='Untitled Indent', max_length=250),
        ),
        migrations.CreateModel(
            name='IndentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('present_stock', models.IntegerField()),
                ('estimated_cost', models.IntegerField(null=True)),
                ('purpose', models.CharField(max_length=250)),
                ('specification', models.CharField(max_length=250)),
                ('item_type', models.CharField(max_length=250)),
                ('item_subtype', models.CharField(default='computers', max_length=250)),
                ('nature', models.BooleanField(default=False)),
                ('indigenous', models.BooleanField(default=False)),
                ('replaced', models.BooleanField(default=False)),
                ('budgetary_head', models.CharField(max_length=250)),
                ('expected_delivery', models.DateField()),
                ('sources_of_supply', models.CharField(max_length=250)),
                ('indent_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ps1.indentfile')),
            ],
            options={
                'db_table': 'IndentItem',
            },
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='item_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ps1.indentitem'),
        ),
    ]
