# Generated by Django 3.1.5 on 2024-04-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0002_auto_20240423_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='indentfile',
            name='item_subtype',
            field=models.CharField(default='computers', max_length=250),
        ),
    ]
