# Generated by Django 3.1.5 on 2023-04-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0002_indentfile2_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indentfile2',
            old_name='director_approval',
            new_name='approved',
        ),
        migrations.RemoveField(
            model_name='indentfile2',
            name='financial_approval',
        ),
        migrations.RemoveField(
            model_name='indentfile2',
            name='head_approval',
        ),
    ]
