# Generated by Django 3.1.5 on 2024-03-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0002_indentfile2_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file_info',
        ),
        migrations.RemoveField(
            model_name='item',
            name='indent_file_id',
        ),
        migrations.DeleteModel(
            name='IndentFile2',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
