# Generated by Django 3.1.5 on 2021-04-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0003_auto_20210420_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='dealing_assistant_id',
            field=models.CharField(default='-1', max_length=250),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='item_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
