# Generated by Django 3.1.5 on 2023-04-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0003_auto_20230402_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantiy',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='file_info',
        ),
        migrations.AddField(
            model_name='indentfile2',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='upload_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
