# Generated by Django 3.1.5 on 2024-03-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0004_auto_20240322_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='item_name',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='itemType',
            field=models.CharField(default='Computers', max_length=250),
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('StockEntryId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ps1.stockentry')),
            ],
            options={
                'db_table': 'StockItem',
            },
        ),
    ]
