# Generated by Django 3.1.5 on 2024-03-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0006_auto_20240322_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='grade',
        ),
    ]
