# Generated by Django 3.1.5 on 2024-03-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0007_remove_stockitem_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='department',
        ),
    ]
