# Generated by Django 3.1.5 on 2024-03-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0008_remove_stockentry_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='itemType',
        ),
    ]
