# Generated by Django 3.1.5 on 2024-03-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0009_remove_stockentry_itemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='nomenclature',
            field=models.CharField(default='item_mohit', max_length=100, unique=True),
        ),
    ]
