# Generated by Django 3.1.5 on 2024-03-23 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0010_stockitem_nomenclature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='StockEntryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps1.stockentry'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='nomenclature',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
