# Generated by Django 3.1.5 on 2024-03-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0011_auto_20240323_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='inUse',
            field=models.BooleanField(default=True),
        ),
    ]
