# Generated by Django 3.1.5 on 2024-03-24 23:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0014_auto_20240324_2310'),
        ('ps1', '0012_stockitem_inuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globals.departmentinfo'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='location',
            field=models.CharField(choices=[('H1', 'Vashistha Hostel'), ('H4', 'Vivekananda Hostel'), ('H3', 'AryaBhatta Hostel'), ('SR1', 'Storage Room 1'), ('SR2', 'Storage Room 2'), ('SR3', 'Storage Room 3'), ('SR4', 'Storage Room 4'), ('SR5', 'Storage Room 5')], default='SR1', max_length=100),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_location', models.CharField(choices=[('H1', 'Vashistha Hostel'), ('H4', 'Vivekananda Hostel'), ('H3', 'AryaBhatta Hostel'), ('SR1', 'Storage Room 1'), ('SR2', 'Storage Room 2'), ('SR3', 'Storage Room 3'), ('SR4', 'Storage Room 4'), ('SR5', 'Storage Room 5')], default='SR1', max_length=100)),
                ('dest_location', models.CharField(choices=[('H1', 'Vashistha Hostel'), ('H4', 'Vivekananda Hostel'), ('H3', 'AryaBhatta Hostel'), ('SR1', 'Storage Room 1'), ('SR2', 'Storage Room 2'), ('SR3', 'Storage Room 3'), ('SR4', 'Storage Room 4'), ('SR5', 'Storage Room 5')], default='SR2', max_length=100)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('dest_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_dest_transfers', to='globals.departmentinfo')),
                ('indent_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps1.indentfile')),
                ('src_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_src_transfers', to='globals.departmentinfo')),
                ('stockItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps1.stockitem')),
            ],
            options={
                'db_table': 'StockTransfer',
            },
        ),
    ]
