# Generated by Django 3.1.5 on 2024-03-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0013_auto_20240324_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='isTransferred',
            field=models.BooleanField(default=False),
        ),
    ]
