# Generated by Django 3.1.5 on 2024-04-10 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0014_stockitem_istransferred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='recieved_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
