# Generated by Django 3.1.5 on 2024-04-10 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0015_auto_20240410_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='recieved_date',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='received_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
