# Generated by Django 3.1.5 on 2024-04-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0016_auto_20240410_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='received_date',
            field=models.DateField(),
        ),
    ]
