# Generated by Django 3.1.5 on 2024-04-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0017_auto_20240410_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockentry',
            old_name='received_date',
            new_name='recieved_date',
        ),
    ]
