# Generated by Django 3.1.5 on 2025-03-25 05:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('budgetIssued', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('area', models.CharField(max_length=200)),
                ('requestCreatedBy', models.CharField(max_length=200)),
                ('engineerProcessed', models.IntegerField(default=0)),
                ('directorApproval', models.IntegerField(default=0)),
                ('deanProcessed', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=200)),
                ('issuedWorkOrder', models.IntegerField(default=0)),
                ('workCompleted', models.IntegerField(default=0)),
                ('billGenerated', models.IntegerField(default=0)),
                ('billProcessed', models.IntegerField(default=0)),
                ('billSettled', models.IntegerField(default=0)),
                ('activeProposal', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('agency', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('deposit', models.IntegerField(default=0)),
                ('alloted_time', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.requests')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=200)),
                ('proposal_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='proposals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='iwdModuleV2.requests')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=255)),
                ('description', models.TextField(default=' ')),
                ('unit', models.CharField(default=' ', max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('docs', models.FileField(blank=True, null=True, upload_to='items/')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='iwdModuleV2.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.requests')),
            ],
        ),
    ]
