# Generated by Django 3.1.5 on 2026-04-19 18:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('budgetIssued', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(help_text='e.g., pieces, kg, meters', max_length=50)),
                ('quantity_available', models.IntegerField(default=0, help_text='Current stock level')),
                ('reorder_level', models.IntegerField(default=10, help_text='Minimum stock level before procurement is triggered')),
                ('location', models.CharField(blank=True, default='', help_text='Storage location (e.g., Electrical Store, Civil Store)', max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('area', models.CharField(max_length=200)),
                ('requestCreatedBy', models.CharField(max_length=200)),
                ('engineerProcessed', models.IntegerField(default=0)),
                ('iwdAdminApproval', models.IntegerField(default=0)),
                ('directorApproval', models.IntegerField(default=0)),
                ('deanProcessed', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=200)),
                ('issuedWorkOrder', models.IntegerField(default=0)),
                ('workCompleted', models.IntegerField(default=0)),
                ('billGenerated', models.IntegerField(default=0)),
                ('billProcessed', models.IntegerField(default=0)),
                ('billSettled', models.IntegerField(default=0)),
                ('activeProposal', models.IntegerField(null=True)),
                ('creationTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, help_text="Estimated budget from engineer's proposal", max_digits=15, null=True)),
                ('isPriority', models.BooleanField(default=False, help_text='Escalated/urgent request')),
                ('iwdAdminApprovalDeadline', models.DateTimeField(blank=True, help_text='SLA deadline for IWD Admin approval', null=True)),
                ('hodApprovalDeadline', models.DateTimeField(blank=True, help_text='SLA deadline for HOD/Dean approval', null=True)),
                ('directorApprovalDeadline', models.DateTimeField(blank=True, help_text='SLA deadline for Director approval', null=True)),
                ('nextApprover', models.CharField(default='IWD Admin', help_text='Next role in approval chain based on budget', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('estimate_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alloted_time', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('work_issuer', models.CharField(default='', max_length=200)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.requests')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('itemdata', models.FileField(blank=True, null=True, upload_to='iwd/vendors/')),
                ('finalbill', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.CharField(blank=True, max_length=200, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='SLAEscalation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalated_from', models.CharField(help_text='Role that missed the SLA deadline', max_length=100)),
                ('escalated_to', models.CharField(help_text='Role the request is escalated to', max_length=100)),
                ('reason', models.TextField(help_text='Reason for escalation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='iwdModuleV2.requests')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=200)),
                ('proposal_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='iwd/proposals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='iwdModuleV2.requests')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=255)),
                ('description', models.TextField(default=' ')),
                ('unit', models.CharField(default=' ', max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('docs', models.FileField(blank=True, null=True, upload_to='iwd/items/')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='iwdModuleV2.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('issue', 'Issue'), ('receipt', 'Receipt'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for receipt, negative for issue')),
                ('performed_by', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='iwdModuleV2.inventoryitem')),
                ('request', models.ForeignKey(blank=True, help_text='IWD request this transaction is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, to='iwdModuleV2.requests')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 (Poor) to 5 (Excellent)')),
                ('comments', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reopened', models.BooleanField(default=False, help_text='True if this feedback triggered a reopen')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='iwdModuleV2.requests')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='iwd/bills/')),
                ('audit', models.BooleanField(default=False)),
                ('settle', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billtype', models.IntegerField(default=0)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='BillItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.bills')),
            ],
        ),
    ]
