# Generated by Django 3.1.5 on 2025-03-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='iwdAdminApproval',
            field=models.IntegerField(default=0),
        ),
    ]
