# Generated by Django 3.1.5 on 2025-03-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aesdetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='key',
        ),
        migrations.RemoveField(
            model_name='corrigendumtable',
            name='key',
        ),
        migrations.RemoveField(
            model_name='extensionoftimedetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='financialbiddetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='financialcontractordetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='letterofintentdetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='milestones',
            name='key',
        ),
        migrations.RemoveField(
            model_name='nooftechnicalbidtimes',
            name='key',
        ),
        migrations.RemoveField(
            model_name='pageonedetails',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='pagethreedetails',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='pagetwodetails',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='prebiddetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='technicalbidcontractordetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='technicalbiddetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='workorderform',
            name='key',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.DeleteModel(
            name='Addendum',
        ),
        migrations.DeleteModel(
            name='AESDetails',
        ),
        migrations.DeleteModel(
            name='Agreement',
        ),
        migrations.DeleteModel(
            name='CorrigendumTable',
        ),
        migrations.DeleteModel(
            name='ExtensionOfTimeDetails',
        ),
        migrations.DeleteModel(
            name='FinancialBidDetails',
        ),
        migrations.DeleteModel(
            name='FinancialContractorDetails',
        ),
        migrations.DeleteModel(
            name='LetterOfIntentDetails',
        ),
        migrations.DeleteModel(
            name='Milestones',
        ),
        migrations.DeleteModel(
            name='NoOfTechnicalBidTimes',
        ),
        migrations.DeleteModel(
            name='PageOneDetails',
        ),
        migrations.DeleteModel(
            name='PageThreeDetails',
        ),
        migrations.DeleteModel(
            name='PageTwoDetails',
        ),
        migrations.DeleteModel(
            name='PreBidDetails',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='TechnicalBidContractorDetails',
        ),
        migrations.DeleteModel(
            name='TechnicalBidDetails',
        ),
        migrations.DeleteModel(
            name='WorkOrderForm',
        ),
    ]
