# Generated by Django 3.1.5 on 2024-07-04 01:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('budgetIssued', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('requestCreatedBy', models.CharField(max_length=200)),
                ('engineerProcessed', models.IntegerField(default=0)),
                ('directorApproval', models.IntegerField(default=0)),
                ('deanProcessed', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=200)),
                ('issuedWorkOrder', models.IntegerField(default=0)),
                ('workCompleted', models.IntegerField(default=0)),
                ('billGenerated', models.IntegerField(default=0)),
                ('billProcessed', models.IntegerField(default=0)),
                ('billSettled', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('agency', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('deposit', models.IntegerField(default=0)),
                ('alloted_time', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.requests')),
            ],
        ),
        migrations.CreateModel(
            name='UsedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.requests')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.requests')),
            ],
        ),
    ]
