# Generated by Django 3.1.5 on 2021-05-21 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addendum',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='aesdetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='corrigendumtable',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='extensionoftimedetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='financialbiddetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='letterofintentdetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='prebiddetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='technicalbiddetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='workorderform',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.CreateModel(
            name='NoOfTechnicalBidTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True)),
            ],
        ),
    ]
