# Generated by Django 3.1.5 on 2024-03-08 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('requestCreatedBy', models.CharField(max_length=200)),
                ('engineerProcessed', models.IntegerField()),
                ('directorApproval', models.IntegerField()),
                ('deanProcessed', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('work', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('agency', models.CharField(max_length=200)),
                ('bill_processed', models.IntegerField()),
                ('bill_settled', models.IntegerField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True)),
            ],
        ),
    ]
