# Generated by Django 3.1.5 on 2025-04-15 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0002_requests_iwdadminapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='creationTime',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
