# Generated by Django 3.1.5 on 2021-05-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0002_nooftechnicalbidtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addendum',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='aesdetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='corrigendumtable',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='extensionoftimedetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='financialbiddetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='financialcontractordetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.financialbiddetails', unique=True),
        ),
        migrations.AlterField(
            model_name='letterofintentdetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='milestones',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='nooftechnicalbidtimes',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='prebiddetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='technicalbidcontractordetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.technicalbiddetails', unique=True),
        ),
        migrations.AlterField(
            model_name='technicalbiddetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
        migrations.AlterField(
            model_name='workorderform',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects', unique=True),
        ),
    ]
