# Generated by Django 3.1.5 on 2024-08-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0002_bills_budget_inventory_requests_useditems_workorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='UsedItems',
        ),
    ]
