# Generated by Django 3.1.5 on 2026-03-13 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0002_auto_20241020_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=255)),
                ('description', models.TextField(default=' ')),
                ('unit', models.CharField(default=' ', max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('docs', models.FileField(blank=True, null=True, upload_to='iwd/items/')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=200)),
                ('proposal_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='iwd/proposals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('itemdata', models.FileField(blank=True, null=True, upload_to='iwd/vendors/')),
                ('finalbill', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aesdetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='key',
        ),
        migrations.RemoveField(
            model_name='corrigendumtable',
            name='key',
        ),
        migrations.RemoveField(
            model_name='extensionoftimedetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='financialbiddetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='financialcontractordetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='letterofintentdetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='milestones',
            name='key',
        ),
        migrations.RemoveField(
            model_name='nooftechnicalbidtimes',
            name='key',
        ),
        migrations.RemoveField(
            model_name='pageonedetails',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='pagethreedetails',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='pagetwodetails',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='prebiddetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='technicalbidcontractordetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='technicalbiddetails',
            name='key',
        ),
        migrations.RemoveField(
            model_name='workorderform',
            name='key',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='agency',
            new_name='work_issuer',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='deposit',
        ),
        migrations.AddField(
            model_name='bills',
            name='audit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bills',
            name='billtype',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bills',
            name='settle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bills',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='requests',
            name='activeProposal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='creationTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='iwdAdminApproval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workorder',
            name='estimate_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bills',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='iwd/bills/'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Addendum',
        ),
        migrations.DeleteModel(
            name='AESDetails',
        ),
        migrations.DeleteModel(
            name='Agreement',
        ),
        migrations.DeleteModel(
            name='CorrigendumTable',
        ),
        migrations.DeleteModel(
            name='ExtensionOfTimeDetails',
        ),
        migrations.DeleteModel(
            name='FinancialBidDetails',
        ),
        migrations.DeleteModel(
            name='FinancialContractorDetails',
        ),
        migrations.DeleteModel(
            name='LetterOfIntentDetails',
        ),
        migrations.DeleteModel(
            name='Milestones',
        ),
        migrations.DeleteModel(
            name='NoOfTechnicalBidTimes',
        ),
        migrations.DeleteModel(
            name='PageOneDetails',
        ),
        migrations.DeleteModel(
            name='PageThreeDetails',
        ),
        migrations.DeleteModel(
            name='PageTwoDetails',
        ),
        migrations.DeleteModel(
            name='PreBidDetails',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='TechnicalBidContractorDetails',
        ),
        migrations.DeleteModel(
            name='TechnicalBidDetails',
        ),
        migrations.DeleteModel(
            name='WorkOrderForm',
        ),
        migrations.AddField(
            model_name='vendor',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.workorder'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='iwdModuleV2.requests'),
        ),
        migrations.AddField(
            model_name='item',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='iwdModuleV2.proposal'),
        ),
        migrations.AddField(
            model_name='billitems',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.bills'),
        ),
        migrations.AddField(
            model_name='bills',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.vendor'),
        ),
    ]
