# Generated by Django 3.1.5 on 2021-05-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0002_auto_20210521_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aesdetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects'),
        ),
        migrations.AlterField(
            model_name='extensionoftimedetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.projects'),
        ),
    ]
