# Generated by Django 3.1.5 on 2026-03-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0003_auto_20260313_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='creationTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_issuer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
