# Generated by Django 3.1.5 on 2025-04-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0003_requests_creationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='creationTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
