# Generated by Django 3.1.5 on 2021-05-20 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0003_auto_20210519_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialcontractordetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.financialbiddetails'),
        ),
        migrations.AlterField(
            model_name='technicalbidcontractordetails',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.technicalbiddetails'),
        ),
    ]
