# Generated by Django 3.1.5 on 2025-05-03 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0004_auto_20250415_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='deposit',
        ),
        migrations.AddField(
            model_name='bills',
            name='audit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bills',
            name='billtype',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bills',
            name='settle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bills',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workorder',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workorder',
            name='estimate_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workorder',
            name='work_issuer',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bills',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='iwd/bills/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='iwd/items/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='iwd/proposals/'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('itemdata', models.FileField(blank=True, null=True, upload_to='iwd/vendors/')),
                ('finalbill', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='BillItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.bills')),
            ],
        ),
        migrations.AddField(
            model_name='bills',
            name='vendor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='iwdModuleV2.vendor'),
            preserve_default=False,
        ),
    ]
