# Generated by Django 3.1.5 on 2026-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0004_auto_20260313_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='directorApprovalDeadline',
            field=models.DateTimeField(blank=True, help_text='SLA deadline for Director approval', null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Estimated budget from engineer's proposal", max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='hodApprovalDeadline',
            field=models.DateTimeField(blank=True, help_text='SLA deadline for HOD/Dean approval', null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='isPriority',
            field=models.BooleanField(default=False, help_text='Escalated/urgent request'),
        ),
        migrations.AddField(
            model_name='requests',
            name='iwdAdminApprovalDeadline',
            field=models.DateTimeField(blank=True, help_text='SLA deadline for IWD Admin approval', null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='nextApprover',
            field=models.CharField(default='IWD Admin', help_text='Next role in approval chain based on budget', max_length=100),
        ),
    ]
