# Generated by Django 3.1.5 on 2026-04-13 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0005_auto_20260407_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(help_text='e.g., pieces, kg, meters', max_length=50)),
                ('quantity_available', models.IntegerField(default=0, help_text='Current stock level')),
                ('reorder_level', models.IntegerField(default=10, help_text='Minimum stock level before procurement is triggered')),
                ('location', models.CharField(blank=True, default='', help_text='Storage location (e.g., Electrical Store, Civil Store)', max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SLAEscalation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalated_from', models.CharField(help_text='Role that missed the SLA deadline', max_length=100)),
                ('escalated_to', models.CharField(help_text='Role the request is escalated to', max_length=100)),
                ('reason', models.TextField(help_text='Reason for escalation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='iwdModuleV2.requests')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('issue', 'Issue'), ('receipt', 'Receipt'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for receipt, negative for issue')),
                ('performed_by', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='iwdModuleV2.inventoryitem')),
                ('request', models.ForeignKey(blank=True, help_text='IWD request this transaction is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, to='iwdModuleV2.requests')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 (Poor) to 5 (Excellent)')),
                ('comments', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reopened', models.BooleanField(default=False, help_text='True if this feedback triggered a reopen')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='iwdModuleV2.requests')),
            ],
        ),
    ]
