# Generated by Django 3.1.5 on 2025-05-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwdModuleV2', '0005_auto_20250503_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='billtype',
            field=models.IntegerField(default=0),
        ),
    ]
