# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-11 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_feedsprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedsprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='feedsProfile',
        ),
    ]
