# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-11 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_view',
            field=models.IntegerField(default=0),
        ),
    ]
