# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-13 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_profile_profile_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askaquestion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='feeds/files'),
        ),
    ]
