# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-27 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0008_auto_20200213_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askaquestion',
            name='total_dislikes',
        ),
        migrations.AddField(
            model_name='askaquestion',
            name='dislikes',
            field=models.ManyToManyField(blank=True, default=1, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
