# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-21 00:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0012_auto_20200229_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeraquestion',
            name='dislikes',
            field=models.ManyToManyField(blank=True, default=1, related_name='answer_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answeraquestion',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answeraquestion',
            name='likes',
            field=models.ManyToManyField(blank=True, default=1, related_name='answer_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answeraquestion',
            name='total_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answeraquestion',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
