# Generated by Django 3.0.8 on 2020-07-09 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canVote', models.BooleanField()),
                ('canAnswer', models.BooleanField()),
                ('canComment', models.BooleanField()),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feeds.AskaQuestion')),
            ],
        ),
    ]
