# Generated by Django 3.0.8 on 2020-07-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_questionaccesscontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaccesscontrol',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feeds.Roles'),
        ),
    ]
