# Generated by Django 3.0.8 on 2020-07-09 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0018_auto_20200709_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaccesscontrol',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
