# Generated by Django 3.0.8 on 2020-07-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0019_questionaccesscontrol_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
