# Generated by Django 3.1.5 on 2023-03-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_no', models.IntegerField()),
                ('name_of_particulars', models.CharField(max_length=50)),
                ('inventory_no', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=50)),
                ('bill_no', models.IntegerField()),
                ('buy_date', models.DateField()),
                ('issued_date', models.DateField()),
                ('head_of_asset', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('receiver_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ps2_stocks',
            },
        ),
    ]
