# Generated by Django 3.1.5 on 2023-04-04 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ps2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='stock_no',
        ),
        migrations.CreateModel(
            name='StockAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
