# Generated by Django 3.1.5 on 2023-03-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockentry',
            old_name='no_of_quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
