# Generated by Django 3.1.5 on 2023-04-06 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ps2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_no', models.CharField(max_length=50)),
                ('is_current_user', models.BooleanField(default=True)),
                ('remark', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('stock_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ps2.stockentry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ps2_transfer',
            },
        ),
    ]
