# Generated by Django 3.1.5 on 2023-04-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps2', '0002_auto_20230404_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_id', models.IntegerField()),
                ('From_department', models.CharField(max_length=50)),
                ('From_location', models.IntegerField(blank=True, null=True)),
                ('To_department', models.CharField(max_length=50)),
                ('To_location', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateTimeField()),
                ('Remark', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ps2_transfer',
            },
        ),
    ]
