# Generated by Django 3.1.5 on 2024-04-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='grade',
        #     name='semester_id',
        #     field=models.CharField(default='1', max_length=10),
        # ),
    ]
