# Generated by Django 3.1.5 on 2025-04-16 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0007_auto_20250416_0629'),
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('announced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.batch')),
            ],
        ),
    ]
