# Generated by Django 3.1.5 on 2024-04-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_grade_semester_id'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='grade',
        #     name='semester_id',
        #     field=models.CharField(max_length=10),
        # ),
    ]
