# Generated by Django 3.1.5 on 2024-04-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_auto_20240411_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='semester_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
