# Generated by Django 3.1.5 on 2024-04-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0005_auto_20240411_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='course_year',
            field=models.IntegerField(default=2024),
        ),
    ]
