# Generated by Django 3.1.5 on 2023-03-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20230322_1021'),
        ('hostel_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestroombooking',
            name='intender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo'),
        ),
    ]
