# Generated by Django 3.1.5 on 2023-03-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20230323_1431'),
        ('hostel_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_room_id',
            field=models.ManyToManyField(blank=True, to='hostel_management.GuestRoomDetail'),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='intender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_id',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='HallAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.faculty')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall')),
            ],
        ),
    ]
