# Generated by Django 3.1.5 on 2025-03-26 02:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelstudentattendence',
            name='date',
        ),
        migrations.RemoveField(
            model_name='hostelstudentattendence',
            name='present',
        ),
        migrations.RemoveField(
            model_name='hostelstudentattendence',
            name='student_id',
        ),
        migrations.AddField(
            model_name='hostelnoticeboard',
            name='scope',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelstudentattendence',
            name='batch',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelstudentattendence',
            name='file',
            field=models.FileField(default='', upload_to='attendance_records/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelstudentattendence',
            name='month',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelstudentattendence',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestroom',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hall',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HostelAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Month', models.CharField(max_length=10)),
                ('File_Location', models.FileField(upload_to='attendance/')),
                ('batch', models.IntegerField()),
                ('Hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall')),
            ],
        ),
        migrations.CreateModel(
            name='HostelAssignedBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='batch_sheet/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall')),
            ],
        ),
    ]
