# Generated by Django 3.1.5 on 2023-04-04 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0006_auto_20230404_1139'),
        ('hostel_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.faculty')),
            ],
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_phone',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='guestroombooking',
            name='guest_room_id',
        ),
        migrations.AddField(
            model_name='guestroombooking',
            name='guest_room_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='intender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo'),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='nationality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled'), ('CancelRequested', 'Cancel Requested'), ('CheckedIn', 'Checked In'), ('Complete', 'Complete'), ('Forward', 'Forward')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_name',
            field=models.CharField(choices=[('saraswati', 'saraswati'), ('vivekananda', 'vivekananda'), ('aryabhatta', 'aryabhatta'), ('vashishtha', 'vashishtha')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hallroom',
            name='block_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hallroom',
            name='room_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hostelnoticeboard',
            name='head_line',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=255),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='staff_type',
            field=models.CharField(default='Caretaker', max_length=255),
        ),
        migrations.AlterField(
            model_name='workerreport',
            name='remark',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workerreport',
            name='worker_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workerreport',
            name='worker_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='GuestRoomDetail',
        ),
        migrations.AddField(
            model_name='halladmin',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall'),
        ),
    ]
