# Generated by Django 3.1.5 on 2025-03-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0002_hostelassignedbatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelassignedbatch',
            name='year',
        ),
        migrations.AddField(
            model_name='hostelassignedbatch',
            name='session',
            field=models.CharField(default='August 2024 - July 2025', max_length=50),
            preserve_default=False,
        ),
    ]
