# Generated by Django 3.1.5 on 2024-07-04 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
        ('hostel_management', '0002_auto_20240703_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='double_seater',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hall',
            name='single_seater',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hall',
            name='triple_seater',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Single Seater', 'Single Seater'), ('Double Seater', 'Double Seater'), ('Triple Seater', 'Triple Seater')], max_length=20)),
                ('room_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=10)),
                ('available_seats', models.IntegerField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall')),
                ('occupants', models.ManyToManyField(blank=True, to='academic_information.Student')),
            ],
        ),
    ]
