# Generated by Django 3.1.5 on 2024-02-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0002_hostelallotment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='assigned_batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
