# Generated by Django 3.1.5 on 2023-03-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0002_auto_20230323_1431'),
        ('hostel_management', '0002_auto_20230322_1028'),
    ]

    operations = [
    ]
