# Generated by Django 3.1.5 on 2023-03-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0002_auto_20230325_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestroombooking',
            name='guest_room_id',
        ),
        migrations.AddField(
            model_name='guestroombooking',
            name='guest_room_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
