# Generated by Django 3.1.5 on 2023-04-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0002_auto_20230404_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=255)),
                ('vacant', models.BooleanField(default=True)),
                ('occupied_till', models.DateField(blank=True, null=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall')),
            ],
        ),
    ]
