# Generated by Django 3.1.5 on 2024-02-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0002_hostelallottment'),
        ('hostel_management', '0003_hall_assigned_batch'),
    ]

    operations = [
    ]
