# Generated by Django 3.1.5 on 2024-02-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0003_hostelleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
