# Generated by Django 3.1.5 on 2023-03-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0003_auto_20230325_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='GuestRoomDetail',
        ),
    ]
