# Generated by Django 3.1.5 on 2024-02-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0003_hostelfine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelfine',
            name='action',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
