# Generated by Django 3.1.5 on 2023-03-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0004_auto_20230325_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall_name',
            field=models.CharField(choices=[('saraswati', 'saraswati'), ('vivekananda', 'vivekananda'), ('aryabhatta', 'aryabhatta'), ('vashishtha', 'vashishtha')], max_length=255),
        ),
    ]
