# Generated by Django 3.1.5 on 2024-02-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0004_auto_20240218_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelfine',
            name='action',
        ),
        migrations.AddField(
            model_name='hostelfine',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50),
        ),
    ]
