# Generated by Django 3.1.5 on 2024-02-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0004_merge_20240217_1949'),
        ('hostel_management', '0004_hostelcomplaint'),
    ]

    operations = [
    ]
