# Generated by Django 3.1.5 on 2024-02-18 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0005_auto_20240218_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelfine',
            name='hall_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall'),
        ),
    ]
