# Generated by Django 3.1.5 on 2024-02-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0005_hostelcomplaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='status',
        ),
    ]
