# Generated by Django 3.1.5 on 2023-04-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0005_auto_20230329_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_room_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='nationality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled'), ('CancelRequested', 'Cancel Requested'), ('CheckedIn', 'Checked In'), ('Complete', 'Complete'), ('Forward', 'Forward')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hallroom',
            name='block_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hallroom',
            name='room_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hostelnoticeboard',
            name='head_line',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=255),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='staff_type',
            field=models.CharField(default='Caretaker', max_length=255),
        ),
        migrations.AlterField(
            model_name='workerreport',
            name='remark',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workerreport',
            name='worker_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workerreport',
            name='worker_name',
            field=models.CharField(max_length=255),
        ),
    ]
