# Generated by Django 3.1.5 on 2024-02-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0007_auto_20240218_2017'),
        ('hostel_management', '0006_merge_20240218_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=255)),
                ('occupied_till', models.DateField(blank=True, null=True)),
                ('vacant', models.BooleanField(default=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall')),
            ],
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.staff'),
        ),
       
    ]
