# Generated by Django 3.1.5 on 2024-02-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0005_auto_20240217_1949'),
        ('hostel_management', '0002_hostelinventory'),
        ('hostel_management', '0007_hostelleave_status'),
        ('hostel_management', '0005_merge_20240217_2302'),
    ]

    operations = [
    ]
