# Generated by Django 3.1.5 on 2024-02-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0007_hostelleave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('room_num', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=100)),
                ('parent_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
