# Generated by Django 3.1.5 on 2024-02-19 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0007_remove_hostelfine_hall_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelfine',
            old_name='student_id',
            new_name='student',
        ),
        migrations.AddField(
            model_name='hostelfine',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall'),
        ),
    ]
