# Generated by Django 3.1.5 on 2024-02-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0009_auto_20240219_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='room_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
