# Generated by Django 3.1.5 on 2024-02-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0010_auto_20240219_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='batch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='programme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
