# Generated by Django 3.1.5 on 2024-02-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0011_auto_20240219_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='hall_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
