# Generated by Django 3.1.5 on 2024-02-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0008_merge_20240218_2206'),
        ('hostel_management', '0011_auto_20240219_0207'),
    ]

    operations = [
    ]
