# Generated by Django 3.1.5 on 2024-02-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0008_auto_20240219_0450'),
        ('hostel_management', '0013_auto_20240219_1316'),
    ]

    operations = [
    ]
