# Generated by Django 3.1.5 on 2024-02-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0014_merge_20240219_1730'),
        ('hostel_management', '0008_auto_20240219_0221'),
        ('hostel_management', '0012_studentdetails_hall_id'),
        ('hostel_management', '0014_merge_20240220_1814'),
    ]

    operations = [
    ]
