# Generated by Django 3.1.5 on 2024-03-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0016_hosteltransactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='type_of_seater',
            field=models.CharField(choices=[('single', 'Single Seater'), ('double', 'Double Seater'), ('triple', 'Triple Seater')], default='single', max_length=50),
        ),
    ]
