# Generated by Django 3.1.5 on 2024-03-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0018_hostelhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelleave',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
