# Generated by Django 3.1.5 on 2024-03-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0018_hostelhistory'),
        ('hostel_management', '0016_hostelleave_remark'),
    ]

    operations = [
    ]
