# Generated by Django 3.1.5 on 2024-03-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0019_hostelleave_remark'),
        ('hostel_management', '0019_merge_20240315_2153'),
    ]

    operations = [
    ]
