# Generated by Django 3.1.5 on 2021-04-24 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
