# Generated by Django 3.1.5 on 2024-04-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20240411_1647'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='ann_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField()),
                ('email', models.CharField(max_length=200)),
                ('facilites', models.TextField()),
                ('labs', models.TextField()),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='globals.departmentinfo')),
            ],
        ),
    ]
