# Generated by Django 3.1.5 on 2021-05-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20210424_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='upload_announcement',
            field=models.FileField(default=' ', null=True, upload_to='department/upload_announcement'),
        ),
    ]
