# Generated by Django 3.1.5 on 2025-04-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20250217_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='department/facility_pictures/')),
            ],
        ),
    ]
