# Generated by Django 3.1.5 on 2025-03-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20250217_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.AlterField(
            model_name='announcements',
            name='upload_announcement',
            field=models.FileField(default=' ', null=True, upload_to='department/upload_announcement'),
        ),
    ]
