# Generated by Django 3.1.5 on 2024-11-01 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_lab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lab',
        ),
    ]
