# Generated by Django 3.1.5 on 2025-04-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
