# Generated by Django 3.1.5 on 2024-11-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20241007_2302'),
        ('department', '0005_auto_20241101_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='globals.departmentinfo'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
