# Generated by Django 3.1.5 on 2024-11-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_auto_20241103_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='upload_announcement',
            field=models.FileField(default=None, null=True, upload_to='department/upload_announcement'),
        ),
    ]
