# Generated by Django 3.1.5 on 2024-11-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_auto_20241108_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
