# Generated by Django 3.1.5 on 2024-11-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_auto_20241108_1525'),
        ('department', '0010_auto_20241108_1652'),
    ]

    operations = [
    ]
