# Generated by Django 3.1.5 on 2026-03-12 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programme_curriculum', '0032_auto_20260312_2332'),
        ('globals', '0005_moduleaccess_database'),
        ('academic_information', '0002_auto_20260312_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_flag', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'spacs_application',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Excellence'), ('RESEARCH', 'Research'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural'), ('INNOVATION', 'Innovation'), ('LEADERSHIP', 'Leadership'), ('COMMUNITY', 'Community Service')], max_length=20)),
                ('description', models.TextField()),
                ('criteria', models.TextField()),
                ('prize_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('certificate_provided', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_programmes', models.ManyToManyField(blank=True, related_name='awards', to='programme_curriculum.Programme')),
            ],
            options={
                'db_table': 'spacs_general_award',
            },
        ),
        migrations.CreateModel(
            name='Award_and_scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=100, unique=True)),
                ('catalog', models.TextField(help_text='Description and eligibility criteria')),
                ('award_type', models.CharField(choices=[('MCM', 'Merit-cum-Means Scholarship'), ('CONVENER', 'Convener Award'), ('DIRECTOR_GOLD', 'Director Gold Medal'), ('DIRECTOR_SILVER', 'Director Silver Medal'), ('PROFICIENCY', 'Proficiency Medal')], default='MCM', max_length=50)),
            ],
            options={
                'db_table': 'spacs_award_catalog',
            },
        ),
        migrations.CreateModel(
            name='ExtendedScholarshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('MERIT', 'Merit-based'), ('NEED', 'Need-based'), ('CATEGORY', 'Category-based'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural'), ('RESEARCH', 'Research'), ('EXTERNAL', 'External/Government')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frequency', models.CharField(default='Annual', max_length=20)),
                ('eligibility_criteria', models.TextField()),
                ('max_backlogs', models.IntegerField(default=0)),
                ('applicable_categories', models.CharField(blank=True, help_text='Comma-separated: GEN,SC,ST,OBC', max_length=50)),
                ('minimum_cgpa', models.FloatField(blank=True, null=True)),
                ('maximum_income', models.IntegerField(blank=True, help_text='Maximum annual family income for need-based', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_batches', models.ManyToManyField(blank=True, related_name='scholarship_types', to='programme_curriculum.Batch')),
                ('applicable_programmes', models.ManyToManyField(blank=True, related_name='scholarship_types', to='programme_curriculum.Programme')),
            ],
            options={
                'db_table': 'spacs_extended_scholarship_type',
            },
        ),
        migrations.CreateModel(
            name='MeritList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=20)),
                ('programme', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.IntegerField()),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'spacs_merit_list',
                'unique_together': {('batch', 'programme', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='ScholarshipEligibilityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_date', models.DateTimeField(auto_now_add=True)),
                ('is_eligible', models.BooleanField()),
                ('reasons', models.TextField(blank=True)),
                ('cgpa_at_check', models.FloatField(blank=True, null=True)),
                ('backlog_count', models.IntegerField(default=0)),
                ('dues_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.award_and_scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'db_table': 'spacs_eligibility_log',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('batch', models.CharField(help_text='e.g., UG1, UG2, 2021', max_length=20)),
                ('programme', models.CharField(help_text='e.g., B.Tech, M.Tech', max_length=50)),
                ('notif_visible', models.BooleanField(default=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='scholarships.award_and_scholarship')),
            ],
            options={
                'db_table': 'spacs_release',
            },
        ),
        migrations.CreateModel(
            name='Proficiency_dm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondence_address', models.TextField()),
                ('financial_assistance', models.TextField(blank=True, null=True)),
                ('grand_total', models.FloatField(default=0.0)),
                ('nearest_policestation', models.CharField(max_length=100)),
                ('nearest_railwaystation', models.CharField(max_length=100)),
                ('relevant_document', models.FileField(upload_to='scholarships/proficiency_docs/')),
                ('title_of_project', models.CharField(blank=True, max_length=200, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proficiency_details', to='scholarships.application')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'db_table': 'spacs_proficiency_dm',
            },
        ),
        migrations.CreateModel(
            name='Previous_winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.award_and_scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'db_table': 'spacs_previous_winner',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scholarships.application')),
            ],
            options={
                'db_table': 'spacs_notification_log',
            },
        ),
        migrations.CreateModel(
            name='Mcm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('sister_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sister_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('income_father', models.IntegerField(default=0)),
                ('income_mother', models.IntegerField(default=0)),
                ('income_other', models.IntegerField(default=0)),
                ('annual_income', models.IntegerField(default=0, help_text='Calculated total income')),
                ('father_occ', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_occ', models.CharField(blank=True, max_length=100, null=True)),
                ('income_certificate', models.FileField(upload_to='scholarships/income_certs/')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcm_details', to='scholarships.application')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'db_table': 'spacs_mcm',
            },
        ),
        migrations.CreateModel(
            name='Director_silver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondence_address', models.TextField()),
                ('financial_assistance', models.TextField(blank=True, null=True)),
                ('grand_total', models.FloatField(default=0.0)),
                ('nearest_policestation', models.CharField(max_length=100)),
                ('nearest_railwaystation', models.CharField(max_length=100)),
                ('relevant_document', models.FileField(upload_to='scholarships/silver_docs/')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='silver_details', to='scholarships.application')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'db_table': 'spacs_director_silver',
            },
        ),
        migrations.CreateModel(
            name='Director_gold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondence_address', models.TextField()),
                ('financial_assistance', models.TextField(blank=True, null=True)),
                ('grand_total', models.FloatField(default=0.0)),
                ('nearest_policestation', models.CharField(max_length=100)),
                ('nearest_railwaystation', models.CharField(max_length=100)),
                ('relevant_document', models.FileField(upload_to='scholarships/gold_docs/')),
                ('academic_achievements', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold_details', to='scholarships.application')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'db_table': 'spacs_director_gold',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.award_and_scholarship'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to='academic_information.student'),
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Format: 2024-25', max_length=9)),
                ('semester', models.IntegerField()),
                ('category_at_application', models.CharField(blank=True, max_length=10)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='scholarships/documents/')),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=20)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scholarship_applications', to='globals.extrainfo')),
                ('scholarship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.extendedscholarshiptype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_scholarship_applications', to='academic_information.student')),
            ],
            options={
                'db_table': 'spacs_scholarship_application',
                'unique_together': {('student', 'scholarship_type', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='MeritListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('total_credits', models.IntegerField(blank=True, null=True)),
                ('eligible_for_scholarships', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('merit_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scholarships.meritlist')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'db_table': 'spacs_merit_list_entry',
                'ordering': ['rank'],
                'unique_together': {('merit_list', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AwardRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('award_date', models.DateField()),
                ('citation', models.TextField(blank=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='scholarships.award')),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_recipients', to='globals.extrainfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_receipts', to='academic_information.student')),
            ],
            options={
                'db_table': 'spacs_award_recipient',
                'unique_together': {('award', 'student', 'academic_year')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'award')},
        ),
    ]
