# Generated by Django 3.1.5 on 2023-04-11 08:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_auto_20230406_1845'),
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DM_Proficiency_gold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT')], default='INCOMPLETE', max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('brief_description_project', models.TextField(max_length=1000, null=True)),
                ('project_grade', models.TextField(max_length=1000, null=True)),
                ('cross_disciplinary', models.TextField(max_length=1000, null=True)),
                ('project_cross_disciplinary', models.TextField(max_length=1000, null=True)),
                ('project_cross_disciplinary_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('project_publication', models.TextField(max_length=1000, null=True)),
                ('project_type', models.TextField(max_length=1000, null=True)),
                ('patent_ipr_project', models.TextField(max_length=1000, null=True)),
                ('prototype_available', models.TextField(max_length=1000, null=True)),
                ('team_members_name', models.TextField(max_length=1000, null=True)),
                ('team_members_cpi', models.TextField(max_length=1000, null=True)),
                ('project_evaluation_prototype', models.TextField(max_length=1000, null=True)),
                ('project_evaluation_prototype_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('project_utility', models.TextField(max_length=1000, null=True)),
                ('project_utility_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('sports_cultural_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('sports_cultural', models.TextField(max_length=1000, null=True)),
                ('sci', models.TextField(max_length=1000, null=True)),
                ('sci_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('esci', models.TextField(max_length=1000, null=True)),
                ('esci_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('scie', models.TextField(max_length=1000, null=True)),
                ('scie_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('ij', models.TextField(max_length=1000, null=True)),
                ('ij_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('ic', models.TextField(max_length=1000, null=True)),
                ('ic_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('nc', models.TextField(max_length=1000, null=True)),
                ('nc_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('workshop', models.TextField(max_length=1000, null=True)),
                ('workshop_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('award_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.award_and_scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'db_table': 'DM_Proficiency_gold',
            },
        ),
        migrations.CreateModel(
            name='IIITDM_Proficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT')], default='INCOMPLETE', max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('project_objectives', models.TextField(max_length=1000, null=True)),
                ('project_mentor', models.TextField(max_length=1000, null=True)),
                ('project_outcome', models.TextField(max_length=1000, null=True)),
                ('project_publications', models.TextField(max_length=1000, null=True)),
                ('research_Or_Patent_Detail', models.TextField(max_length=1000, null=True)),
                ('project_Beneficial', models.TextField(max_length=1000, null=True)),
                ('improvement_Done', models.TextField(max_length=1000, null=True)),
                ('project_report', models.FileField(blank=True, null=True, upload_to='')),
                ('project_title', models.TextField(max_length=1000, null=True)),
                ('project_abstract', models.TextField(max_length=1000, null=True)),
                ('sci', models.TextField(max_length=1000, null=True)),
                ('sci_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('esci', models.TextField(max_length=1000, null=True)),
                ('esci_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('scie', models.TextField(max_length=1000, null=True)),
                ('scie_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('ij', models.TextField(max_length=1000, null=True)),
                ('ij_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('ic', models.TextField(max_length=1000, null=True)),
                ('ic_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('nc', models.TextField(max_length=1000, null=True)),
                ('nc_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('indian_national_Conference', models.TextField(max_length=1000, null=True)),
                ('indian_national_Conference_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('international_Conference', models.TextField(max_length=1000, null=True)),
                ('international_Conference_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('project_grade', models.TextField(max_length=1000, null=True)),
                ('patent_Status', models.TextField(max_length=1000, null=True)),
                ('interdisciplinary_Criteria', models.TextField(max_length=1000, null=True)),
                ('awards_Recieved_Workshop', models.TextField(max_length=1000, null=True)),
                ('placement_Status', models.TextField(max_length=1000, null=True)),
                ('workshop', models.TextField(max_length=1000, null=True)),
                ('workshop_doc', models.TextField(max_length=1000, null=True)),
                ('prototype', models.TextField(max_length=1000, null=True)),
                ('prototype_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('utility', models.TextField(max_length=1000, null=True)),
                ('utility_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('core_Area', models.TextField(max_length=1000, null=True)),
                ('core_Area_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('technology_Transfer', models.TextField(max_length=1000, null=True)),
                ('technology_Transfer_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('project_write_up', models.TextField(max_length=1000, null=True)),
                ('award_id', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='scholarships.award_and_scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'db_table': 'IIITDM_Proficiency',
            },
        ),
        migrations.RemoveField(
            model_name='director_gold',
            name='academic_achievements',
        ),
        migrations.RemoveField(
            model_name='director_gold',
            name='correspondence_address',
        ),
        migrations.RemoveField(
            model_name='director_gold',
            name='cultural_inside',
        ),
        migrations.RemoveField(
            model_name='director_gold',
            name='cultural_outside',
        ),
        migrations.RemoveField(
            model_name='director_gold',
            name='games_inside',
        ),
        migrations.RemoveField(
            model_name='director_gold',
            name='games_outside',
        ),
        migrations.RemoveField(
            model_name='director_gold',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='director_gold',
            name='justification',
        ),
        migrations.RemoveField(
            model_name='director_gold',
            name='nearest_policestation',
        ),
        migrations.RemoveField(
            model_name='director_gold',
            name='nearest_railwaystation',
        ),
        migrations.RemoveField(
            model_name='director_gold',
            name='other_activities',
        ),
        migrations.RemoveField(
            model_name='director_gold',
            name='relevant_document',
        ),
        migrations.RemoveField(
            model_name='director_gold',
            name='science_inside',
        ),
        migrations.RemoveField(
            model_name='director_gold',
            name='science_outside',
        ),
        migrations.RemoveField(
            model_name='director_silver',
            name='award_type',
        ),
        migrations.RemoveField(
            model_name='director_silver',
            name='correspondence_address',
        ),
        migrations.RemoveField(
            model_name='director_silver',
            name='financial_assistance',
        ),
        migrations.RemoveField(
            model_name='director_silver',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='director_silver',
            name='inside_achievements',
        ),
        migrations.RemoveField(
            model_name='director_silver',
            name='justification',
        ),
        migrations.RemoveField(
            model_name='director_silver',
            name='nearest_policestation',
        ),
        migrations.RemoveField(
            model_name='director_silver',
            name='nearest_railwaystation',
        ),
        migrations.RemoveField(
            model_name='director_silver',
            name='outside_achievements',
        ),
        migrations.RemoveField(
            model_name='director_silver',
            name='relevant_document',
        ),
        migrations.AddField(
            model_name='director_gold',
            name='academic',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='academic_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='blood_donation',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='corporate_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='counselling_activities_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='cultural',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='cultural_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='disciplinary_action',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='financial_assistance_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='games',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='games_doc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='gymkhana_activities_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='hall_activities_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='ic',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='ic_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='ij',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='ij_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='institute_activities_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='jagriti',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='nc',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='nc_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='novelty',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='other_extra_curricular_activities',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='sci',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='sci_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='scie',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='scie_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='science',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='science_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='social_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='warning_letter',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='workshop',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_gold',
            name='workshop_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_club_co_coordinator',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_club_co_coordinator_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_club_coordinator',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_club_coordinator_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_event_member',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_event_member_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_interIIIT_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_interIIIT_certificates_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_interIIIT_team_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_interIIIT_team_certificates_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_intercollege_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_intercollege_certificates_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_intercollege_team_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_intercollege_team_certificates_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='cultural_intercollege_team_event',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='culturalfest_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='culturalfest_certificates_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='sports_club_co_coordinator',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='sports_club_co_coordinator_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='sports_club_coordinator',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='sports_club_coordinator_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='sports_event_member',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='sports_event_member_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='sports_interIIIT_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='sports_interIIIT_team_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='sports_intercollege_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='sports_intercollege_team_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='sports_other_accomplishment',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='sports_other_accomplishment_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='sportsfest_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='sportsfest_team_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Proficiency_dm',
        ),
    ]
