# Generated by Django 3.1.5 on 2025-04-12 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director_gold',
            name='relevant_document',
        ),
        migrations.RemoveField(
            model_name='director_silver',
            name='relevant_document',
        ),
        migrations.RemoveField(
            model_name='proficiency_dm',
            name='relevant_document',
        ),
        migrations.AddField(
            model_name='director_gold',
            name='Marksheet',
            field=models.FileField(default='', upload_to='scholarships/director_gold/marksheet/'),
        ),
        migrations.AddField(
            model_name='director_silver',
            name='Marksheet',
            field=models.FileField(default='', upload_to='scholarships/director_silver/marksheet/'),
        ),
        migrations.AddField(
            model_name='mcm',
            name='Aadhar_card',
            field=models.FileField(default='', upload_to='scholarships/mcm/aadhar_card/'),
        ),
        migrations.AddField(
            model_name='mcm',
            name='Affidavit',
            field=models.FileField(default='', upload_to='scholarships/mcm/affidavit/'),
        ),
        migrations.AddField(
            model_name='mcm',
            name='Bank_details',
            field=models.FileField(default='', upload_to='scholarships/mcm/bank_details/'),
        ),
        migrations.AddField(
            model_name='mcm',
            name='Fee_Receipt',
            field=models.FileField(default='', upload_to='scholarships/mcm/fee_receipt/'),
        ),
        migrations.AddField(
            model_name='mcm',
            name='Marksheet',
            field=models.FileField(default='', upload_to='scholarships/mcm/marksheet/'),
        ),
        migrations.AddField(
            model_name='proficiency_dm',
            name='Marksheet',
            field=models.FileField(default='', upload_to='scholarships/proficiency_dm/marksheet/'),
        ),
        migrations.AlterField(
            model_name='director_gold',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='director_silver',
            name='award_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='scholarships.award_and_scholarship'),
        ),
        migrations.AlterField(
            model_name='director_silver',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='forms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='income_certificate',
            field=models.FileField(default='', upload_to='scholarships/mcm/income_certificate/'),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='previous_winner',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='award_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='scholarships.award_and_scholarship'),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='cse_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='design_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='ece_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='mech_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='roll_no1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='roll_no2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='roll_no3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='roll_no4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='roll_no5',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], default='INCOMPLETE', max_length=20),
        ),
    ]
