# Generated by Django 3.1.5 on 2026-03-27 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_auto_20260312_2332'),
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='McmApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('student_full_name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('programme', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('jee_uceed_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_income', models.CharField(max_length=100)),
                ('postal_address', models.TextField()),
                ('father_income_certificate_link', models.URLField(blank=True, max_length=500, null=True)),
                ('mother_income_certificate_link', models.URLField(blank=True, max_length=500, null=True)),
                ('caste_certificate_link', models.URLField(blank=True, max_length=500, null=True)),
                ('jee_uceed_scorecard_link', models.URLField(blank=True, max_length=500, null=True)),
                ('undertaking_form_link', models.URLField(blank=True, max_length=500, null=True)),
                ('questionnaire_cum_application_link', models.URLField(blank=True, max_length=500, null=True)),
                ('form_ab_link', models.URLField(blank=True, max_length=500, null=True)),
                ('form_d_link', models.URLField(blank=True, max_length=500, null=True)),
                ('declaration_yes', models.CharField(default='Yes', max_length=10)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcm_latest_applications', to='academic_information.student')),
            ],
            options={
                'db_table': 'mcm_applications',
            },
        ),
    ]
