# Generated by Django 3.1.5 on 2024-11-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director_gold',
            name='relevant_document',
        ),
        migrations.RemoveField(
            model_name='director_silver',
            name='relevant_document',
        ),
        migrations.RemoveField(
            model_name='proficiency_dm',
            name='relevant_document',
        ),
        migrations.AddField(
            model_name='director_gold',
            name='Marksheet',
            field=models.FileField(default='NA', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director_silver',
            name='Marksheet',
            field=models.FileField(default='NA', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcm',
            name='Aadhar_card',
            field=models.FileField(default='NA', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcm',
            name='Affidavit',
            field=models.FileField(default='NA', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcm',
            name='Bank_details',
            field=models.FileField(default='NA', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcm',
            name='Fee_Receipt',
            field=models.FileField(default='NA', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcm',
            name='marksheet',
            field=models.FileField(default='NA', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proficiency_dm',
            name='Marksheet',
            field=models.FileField(default='NA', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcm',
            name='income_certificate',
            field=models.FileField(default='NA', upload_to=''),
            preserve_default=False,
        ),
    ]
