# Generated by Django 3.1.5 on 2024-11-16 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_auto_20241115_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcm',
            old_name='marksheet',
            new_name='Marksheet',
        ),
    ]
