# Generated by Django 3.1.5 on 2025-03-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_auto_20250313_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director_gold',
            name='Marksheet',
            field=models.FileField(default='', upload_to='scholarships/director_gold/marksheet/'),
        ),
        migrations.AlterField(
            model_name='director_silver',
            name='Marksheet',
            field=models.FileField(default='', upload_to='scholarships/director_silver/marksheet/'),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='Aadhar_card',
            field=models.FileField(default='', upload_to='scholarships/mcm/aadhar_card/'),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='Affidavit',
            field=models.FileField(default='', upload_to='scholarships/mcm/affidavit/'),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='Bank_details',
            field=models.FileField(default='', upload_to='scholarships/mcm/bank_details/'),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='Fee_Receipt',
            field=models.FileField(default='', upload_to='scholarships/mcm/fee_receipt/'),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='Marksheet',
            field=models.FileField(default='', upload_to='scholarships/mcm/marksheet/'),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='income_certificate',
            field=models.FileField(default='', upload_to='scholarships/mcm/income_certificate/'),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='Marksheet',
            field=models.FileField(default='', upload_to='scholarships/proficiency_dm/marksheet/'),
        ),
    ]
