# Generated by Django 3.1.5 on 2024-11-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_auto_20241116_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director_gold',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('UNDER_REVIEW', 'Under Review')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='director_silver',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('UNDER_REVIEW', 'Under Review')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('UNDER_REVIEW', 'Under Review')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('UNDER_REVIEW', 'Under Review')], default='INCOMPLETE', max_length=20),
        ),
    ]
