# Generated by Django 3.1.5 on 2026-03-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_mcmapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcmapplication',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FORWARDED_TO_CONVENOR', 'Forwarded to Convenor'), ('CORRECTION_REQUIRED', 'Correction Required')], default='SUBMITTED', max_length=50),
        ),
    ]
