# Generated by Django 3.1.5 on 2024-11-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0002_auto_20241016_1905'),
        ('online_cms', '0002_auto_20241017_0040'),
        ('online_cms', '0002_auto_20241012_1459'),
    ]

    operations = [
    ]
