# Generated by Django 3.1.5 on 2023-04-08 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_student_hall_id'),
        ('scholarships', '0002_auto_20230404_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='IIITDM_Proficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT')], default='INCOMPLETE', max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('project_objectives', models.TextField(max_length=1000, null=True)),
                ('project_mentor', models.TextField(max_length=1000, null=True)),
                ('project_outcome', models.TextField(max_length=1000, null=True)),
                ('project_publications', models.TextField(max_length=1000, null=True)),
                ('research_Or_Patent_Detail', models.TextField(max_length=1000, null=True)),
                ('research_Or_Patent_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('project_Beneficial', models.TextField(max_length=1000, null=True)),
                ('improvement_Done', models.TextField(max_length=1000, null=True)),
                ('project_report', models.FileField(blank=True, null=True, upload_to='')),
                ('project_title', models.TextField(max_length=1000, null=True)),
                ('project_abstract', models.TextField(max_length=1000, null=True)),
                ('sci', models.TextField(max_length=1000, null=True)),
                ('sci_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('esci', models.TextField(max_length=1000, null=True)),
                ('esci_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('scie', models.TextField(max_length=1000, null=True)),
                ('scie_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('ij', models.TextField(max_length=1000, null=True)),
                ('ij_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('ic', models.TextField(max_length=1000, null=True)),
                ('ic_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('nc', models.TextField(max_length=1000, null=True)),
                ('nc_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('indian_national_Conference', models.TextField(max_length=1000, null=True)),
                ('indian_national_Conference_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('international_Conference', models.TextField(max_length=1000, null=True)),
                ('international_Conference_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('project_grade', models.TextField(max_length=1000, null=True)),
                ('patent_Status', models.TextField(max_length=1000, null=True)),
                ('interdisciplinary_Criteria', models.TextField(max_length=1000, null=True)),
                ('awards_Recieved_Workshop', models.TextField(max_length=1000, null=True)),
                ('placement_Status', models.TextField(max_length=1000, null=True)),
                ('workshop', models.TextField(max_length=1000, null=True)),
                ('workshop_doc', models.TextField(max_length=1000, null=True)),
                ('prototype', models.TextField(max_length=1000, null=True)),
                ('prototype_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('utility', models.TextField(max_length=1000, null=True)),
                ('utility_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('core_Area', models.TextField(max_length=1000, null=True)),
                ('core_Area_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('technology_Transfer', models.TextField(max_length=1000, null=True)),
                ('technology_Transfer_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('project_write_up', models.TextField(max_length=1000, null=True)),
                ('award_id', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='scholarships.award_and_scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
            options={
                'db_table': 'IIITDM_Proficiency',
            },
        ),
    ]
