# Generated by Django 3.0.6 on 2020-05-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_auto_20200121_2305'),
        ('scholarships', '0003_merge_20200521_2351'),
    ]

    operations = [
    ]
