# Generated by Django 3.1.5 on 2024-11-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_auto_20241116_0306'),
        ('scholarships', '0003_auto_20241117_2324'),
    ]

    operations = [
    ]
