# Generated by Django 3.1.5 on 2026-03-31 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_auto_20260312_2332'),
        ('scholarships', '0003_auto_20260328_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleParentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('student_full_name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('programme', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=20)),
                ('postal_address', models.TextField()),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('current_cpi', models.DecimalField(decimal_places=2, max_digits=4)),
                ('caste_certificate', models.FileField(upload_to='scholarships/single_parent/caste_certificates/')),
                ('undertaking_form', models.FileField(upload_to='scholarships/single_parent/undertakings/')),
                ('death_certificate', models.FileField(upload_to='scholarships/single_parent/death_certificates/')),
                ('affidavit_no_earning_member', models.FileField(upload_to='scholarships/single_parent/affidavits/')),
                ('declaration_yes', models.CharField(default='Yes', max_length=10)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FORWARDED_TO_CONVENOR', 'Forwarded to Convenor'), ('CORRECTION_REQUIRED', 'Correction Required')], default='SUBMITTED', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_parent_applications', to='academic_information.student')),
            ],
            options={
                'db_table': 'single_parent_application',
            },
        ),
    ]
