# Generated by Django 3.1.5 on 2024-11-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_auto_20241116_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='director_gold',
            name='nearest_railwaystations',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='director_gold',
            name='nearest_railwaystation',
            field=models.TextField(default='station', max_length=30),
        ),
    ]
