# Generated by Django 3.1.5 on 2023-04-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_iiitdm_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iiitdm_proficiency',
            name='research_Or_Patent_doc',
        ),
    ]
