# Generated by Django 3.1.5 on 2025-03-14 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_auto_20250313_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiency_dm',
            name='award_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='scholarships.award_and_scholarship'),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='cse_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='design_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='ece_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='mech_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='roll_no1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='roll_no2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='roll_no3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='roll_no4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='roll_no5',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
