# Generated by Django 3.1.5 on 2024-11-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0003_merge_20241110_1253'),
        ('online_cms', '0004_merge_20241115_1509'),
    ]

    operations = [
    ]
