# Generated by Django 3.1.5 on 2026-03-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_singleparentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcmapplication',
            name='current_cpi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
