# Generated by Django 3.0.6 on 2020-05-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_merge_20200522_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director_gold',
            old_name='coorporate',
            new_name='corporate',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='invite_covocation_accept_flag',
            new_name='invite_convocation_accept_flag',
        ),
    ]
