# Generated by Django 3.1.5 on 2026-03-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_mcmapplication_current_cpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleparentapplication',
            name='affidavit_no_earning_member',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='singleparentapplication',
            name='caste_certificate',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='singleparentapplication',
            name='death_certificate',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='singleparentapplication',
            name='undertaking_form',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
