# Generated by Django 3.0.6 on 2020-06-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_auto_20200524_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='award_form_visible',
        ),
        migrations.AlterField(
            model_name='release',
            name='award',
            field=models.CharField(default='', max_length=50),
        ),
    ]
