# Generated by Django 3.1.5 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_auto_20260331_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcmapplication',
            name='current_spi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='mcmapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REVERTED', 'Reverted'), ('REJECTED', 'Rejected'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('FORWARDED_TO_CONVENOR', 'Forwarded to Convenor'), ('CORRECTION_REQUIRED', 'Correction Required')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='singleparentapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REVERTED', 'Reverted'), ('REJECTED', 'Rejected'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('FORWARDED_TO_CONVENOR', 'Forwarded to Convenor'), ('CORRECTION_REQUIRED', 'Correction Required')], default='PENDING', max_length=50),
        ),
        migrations.CreateModel(
            name='MeritListRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=50)),
                ('cpi', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'merit_list',
            },
        ),
    ]
