# Generated by Django 3.1.5 on 2024-02-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_merge_20240219_1730'),
        ('scholarships', '0006_merge_20240220_1814'),
    ]

    operations = [
    ]
