# Generated by Django 3.0.6 on 2020-06-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_auto_20200607_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='director_silver',
            name='award_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proficiency_dm',
            name='award_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
