# Generated by Django 3.1.5 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_mcm_spi_and_merit_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcmapplication',
            name='revert_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singleparentapplication',
            name='revert_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
