# Generated by Django 3.0.7 on 2020-07-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_auto_20200612_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director_silver',
            name='correspondence_address',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='director_silver',
            name='nearest_policestation',
            field=models.TextField(default='station', max_length=30),
        ),
        migrations.AlterField(
            model_name='director_silver',
            name='nearest_railwaystation',
            field=models.TextField(default='station', max_length=30),
        ),
    ]
