# Generated by Django 3.1.5 on 2024-11-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_auto_20241118_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcm',
            old_name='Marksheet',
            new_name='marksheet',
        ),
    ]
