# Generated by Django 3.0.7 on 2020-06-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_auto_20200613_1945'),
        ('scholarships', '0008_auto_20200613_1305'),
    ]

    operations = [
    ]
