# Generated by Django 3.0.7 on 2020-07-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_auto_20200705_1726'),
        ('scholarships', '0009_merge_20200615_0425'),
    ]

    operations = [
    ]
