# Generated by Django 3.1.5 on 2021-03-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_auto_20200705_1726'),
        ('scholarships', '0009_merge_20200615_0425'),
    ]

    operations = [
    ]
