# Generated by Django 3.1.5 on 2026-03-31

from django.db import migrations


LEGACY_STATUS_MAP = {
    'submitted': 'pending',
    'under_review': 'verified',
    'forwarded_to_convenor': 'verified',
    'correction_required': 'reverted',
    'pending': 'pending',
    'reverted': 'reverted',
    'verified': 'verified',
    'approved': 'approved',
    'rejected': 'rejected',
}

ALLOWED = {'pending', 'reverted', 'verified', 'approved', 'rejected'}


def normalize_status(value):
    text = (value or '').strip().lower()
    if not text:
        return 'pending'
    mapped = LEGACY_STATUS_MAP.get(text, text)
    return mapped if mapped in ALLOWED else 'pending'


def forwards(apps, schema_editor):
    for model_name in ['McmApplication', 'SingleParentApplication']:
        Model = apps.get_model('scholarships', model_name)
        for row in Model.objects.all().only('id', 'status', 'revert_reason'):
            normalized = normalize_status(row.status)
            updated_fields = []

            if row.status != normalized:
                row.status = normalized
                updated_fields.append('status')

            if normalized != 'reverted' and row.revert_reason:
                row.revert_reason = None
                updated_fields.append('revert_reason')

            if updated_fields:
                row.save(update_fields=updated_fields)


def noop_reverse(apps, schema_editor):
    # One-way normalization migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0009_status_lowercase_and_updated_at'),
    ]

    operations = [
        migrations.RunPython(forwards, noop_reverse),
    ]
