# Generated by Django 3.1.5 on 2021-02-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0010_merge_20210228_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_winner',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
