from django.urls import path

from .views import (
    ActiveBookingsApiView,
    AddInventoryApiView,
    BillGenerationApiView,
    BillBetweenDatesApiView,
    BookingReportsApiView,
    BookingDetailApiView,
    CancelBookingApiView,
    ApproveCancelBookingRequestApiView,
    RejectCancelBookingRequestApiView,
    CancelBookingRequestApiView,
    CancelRequestedBookingsApiView,
    CheckInApiView,
    CheckOutApiView,
    CompletedBookingsApiView,
    ConfirmBookingApiView,
    DetectNoShowsApiView,
    DetectOverstaysApiView,
    DetectDueCheckoutsApiView,  # BR-VH-010: Due checkout alerts
    EditRoomStatusApiView,
    ForwardBookingApiView,
    PendingBookingsApiView,
    RequestBookingApiView,
    RecordMealApiView,
    GetMealRecordsApiView,  # UC-VH-010: Get meal records
    RejectBookingApiView,
    RoomAvailabilityApiView,
    SettleBillApiView,
    UpdateBookingApiView,
    UpdateVisitorInfoApiView,
    UpdateInventoryApiView,
    InventoryListApiView,
    InventoryReportsApiView,
    VisitorHostelApiHealthView,
    # UC-VH-011: Inventory threshold & replenishment endpoints
    InventoryThresholdCheckApiView,
    ReplenishmentRequestApiView,
    ApproveReplenishmentApiView,
    RejectReplenishmentApiView,
    UpdateInventoryQuantityApiView,
    MarkReplenishmentReceivedApiView,
    # BR-VH-010: Check-in/Check-out Alerts endpoints
    DetectNoShowAlertsApiView,
    DetectDueCheckoutAlertsApiView,
    GetPendingAlertsApiView,
    AcknowledgeAlertApiView,
    ResolveAlertApiView,
)

app_name = "visitorhostel_api"

urlpatterns = [
    path("health/", VisitorHostelApiHealthView.as_view(), name="health"),
    path("bookings/pending/", PendingBookingsApiView.as_view(), name="pending_bookings"),
    path("bookings/active/", ActiveBookingsApiView.as_view(), name="active_bookings"),
    path("bookings/completed/", CompletedBookingsApiView.as_view(), name="completed_bookings"),
    path("bookings/<int:booking_id>/", BookingDetailApiView.as_view(), name="booking_detail"),
    path("bookings/request/", RequestBookingApiView.as_view(), name="request_booking"),
    path("bookings/confirm/", ConfirmBookingApiView.as_view(), name="confirm_booking"),
    path("bookings/cancel/", CancelBookingApiView.as_view(), name="cancel_booking"),
    path("bookings/cancel-request/", CancelBookingRequestApiView.as_view(), name="cancel_booking_request"),
    path("bookings/cancel-requests/", CancelRequestedBookingsApiView.as_view(), name="cancel_requested_bookings"),
    path("bookings/cancel-approve/", ApproveCancelBookingRequestApiView.as_view(), name="approve_cancel_booking_request"),
    path("bookings/cancel-reject/", RejectCancelBookingRequestApiView.as_view(), name="reject_cancel_booking_request"),
    path("bookings/reject/", RejectBookingApiView.as_view(), name="reject_booking"),
    path("bookings/forward/", ForwardBookingApiView.as_view(), name="forward_booking"),
    path("bookings/checkin/", CheckInApiView.as_view(), name="check_in"),
    path("bookings/checkout/", CheckOutApiView.as_view(), name="check_out"),
    path("bookings/settle-bill/", SettleBillApiView.as_view(), name="settle_bill"),
    path("bookings/detect-no-shows/", DetectNoShowsApiView.as_view(), name="detect_no_shows"),
    path("bookings/detect-overstays/", DetectOverstaysApiView.as_view(), name="detect_overstays"),
    path("bookings/detect-due-checkouts/", DetectDueCheckoutsApiView.as_view(), name="detect_due_checkouts"),
    path("bookings/update/", UpdateBookingApiView.as_view(), name="update_booking"),
    path("bookings/update-visitor-info/", UpdateVisitorInfoApiView.as_view(), name="update_visitor_info"),
    path("meals/record/", RecordMealApiView.as_view(), name="record_meal"),
    path("meals/records/<int:booking_id>/", GetMealRecordsApiView.as_view(), name="get_meal_records"),
    path("rooms/availability/", RoomAvailabilityApiView.as_view(), name="room_availability"),
    path("rooms/status/", EditRoomStatusApiView.as_view(), name="edit_room_status"),
    path("inventory/add/", AddInventoryApiView.as_view(), name="add_to_inventory"),
    path("inventory/list/", InventoryListApiView.as_view(), name="inventory_list"),
    path("inventory/update/", UpdateInventoryApiView.as_view(), name="update_inventory"),
    # UC-VH-011: Inventory threshold & replenishment URLs
    path("inventory/threshold-check/", InventoryThresholdCheckApiView.as_view(), name="inventory_threshold_check"),
    path("inventory/replenishment-request/", ReplenishmentRequestApiView.as_view(), name="replenishment_request"),
    path("inventory/approve-replenishment/", ApproveReplenishmentApiView.as_view(), name="approve_replenishment"),
    path("inventory/reject-replenishment/", RejectReplenishmentApiView.as_view(), name="reject_replenishment"),
    path("inventory/update-quantity/", UpdateInventoryQuantityApiView.as_view(), name="update_inventory_quantity"),
    path("inventory/mark-received/", MarkReplenishmentReceivedApiView.as_view(), name="mark_replenishment_received"),
    path("reports/bills/", BillBetweenDatesApiView.as_view(), name="bill_between_dates"),
    path("reports/bookings/", BookingReportsApiView.as_view(), name="booking_reports"),
    path("reports/inventory/", InventoryReportsApiView.as_view(), name="inventory_reports"),
    # BR-VH-010: Check-in/Check-out Alerts endpoints
    path("alerts/detect-no-shows/", DetectNoShowAlertsApiView.as_view(), name="detect_no_show_alerts"),
    path("alerts/detect-due-checkouts/", DetectDueCheckoutAlertsApiView.as_view(), name="detect_due_checkout_alerts"),
    path("alerts/pending/", GetPendingAlertsApiView.as_view(), name="get_pending_alerts"),
    path("alerts/acknowledge/", AcknowledgeAlertApiView.as_view(), name="acknowledge_alert"),
    path("alerts/resolve/", ResolveAlertApiView.as_view(), name="resolve_alert"),
    path("bills/generate/", BillGenerationApiView.as_view(), name="bill_generation"),
]
