name: Security check - Bandit

on: [push, pull_request]  

jobs:
  build:
    runs-on: ubuntu-22.04 
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest] 
    name: Python ${{ matrix.os }}  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Security check - Bandit  
      run: |
        bandit -r -f json --exclude **/FusionIIIT/Fusion/settings/**,**/FusionIIIT/Fusion/settings/**,**/FusionIIIT/applications/academic_information/**,**/FusionIIIT/applications/academic_procedures/**,**/FusionIIIT/applications/feeds/**,**/FusionIIIT/applications/globals/**,**/FusionIIIT/applications/health_center/**,**/FusionIIIT/applications/hr2/**,**/FusionIIIT/applications/leave/**,**/FusionIIIT/applications/library/**,**/FusionIIIT/applications/online_cms/**,**/FusionIIIT/applications/online_cms/**,**/FusionIIIT/applications/scholarships/**,**/FusionIIIT/applications/visitor_hostel/**,**/FusionIIIT/applications/establishment/** .
    - name: Security check report artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Security report 
        path: output/security_report.json