name: Security check - Bandit

on: [push, pull_request]  

jobs:
  build:
    runs-on: ubuntu-22.04 
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest] 
    name: Python ${{ matrix.os }}  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Security check - Bandit  
      run: |
        bandit -r -f json --exclude 
        ./FusionIIIT/Fusion/settings/common.py, 
        ./FusionIIIT/Fusion/settings/development.py .

    - name: Security check report artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Security report 
        path: output/security_report.json