name: "mypy check"

on: [push, pull_request] 

jobs:

  static-type-check:
    runs-on: ubuntu-22.04  

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3  
      with:
        python-version: '3.8.15'  

    - run: pip install mypy 

    - name: Get Python changed files 
      id: changed-py-files
      uses: tj-actions/changed-files@v23
      with:
        files: |
          *.py
          **/*.py

    - name: Run if any of the listed files above is changed 
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: mypy ${{ steps.changed-py-files.outputs.all_changed_files }} --ignore-missing-imports
