name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Get Python changed files  # Identifies changed Python files
      id: changed-py-files
      uses: tj-actions/changed-files@v23
      with:
        files: |
          *.py
          **/*.py
          
    - name: Analysing the code with pylint
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: |
        pylint ${{ steps.changed-py-files.outputs.all_changed_files }}
