# Generated by Django 3.1.5 on 2024-07-16 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programme_curriculum', '0001_initial'),
        ('globals', '0001_initial'),
        ('academic_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('submit_date', models.DateTimeField()),
                ('assignment_name', models.CharField(max_length=100)),
                ('assignment_url', models.CharField(max_length=100, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(max_length=2000)),
                ('commenter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prac_quiz_name', models.CharField(max_length=20)),
                ('negative_marks', models.FloatField(default=0)),
                ('number_of_question', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1000)),
                ('total_score', models.IntegerField(default=0)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('options1', models.CharField(max_length=100, null=True)),
                ('options2', models.CharField(max_length=100, null=True)),
                ('options3', models.CharField(max_length=100, null=True)),
                ('options4', models.CharField(max_length=100, null=True)),
                ('options5', models.CharField(max_length=100, null=True)),
                ('answer', models.IntegerField()),
                ('image', models.TextField(max_length=1000, null=True)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=20)),
                ('end_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('d_day', models.CharField(max_length=2)),
                ('d_hour', models.CharField(max_length=2)),
                ('d_minute', models.CharField(max_length=2)),
                ('negative_marks', models.FloatField(default=0)),
                ('number_of_question', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1000)),
                ('rules', models.TextField(max_length=2000)),
                ('total_score', models.IntegerField(default=0)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_cms.question')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_cms.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.TextField(max_length=200)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('upload_url', models.TextField(max_length=200)),
                ('score', models.IntegerField(null=True)),
                ('feedback', models.CharField(max_length=100, null=True)),
                ('assign_name', models.CharField(max_length=100)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_cms.assignment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_cms.quizquestion')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_cms.quiz')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2016)),
                ('roll_no', models.TextField(max_length=2000)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grade', models.TextField(max_length=2000)),
                ('batch', models.IntegerField(default=2021)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_cms.quiz')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_cms.questionbank'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_cms.topics'),
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('options1', models.CharField(max_length=100, null=True)),
                ('options2', models.CharField(max_length=100, null=True)),
                ('options3', models.CharField(max_length=100, null=True)),
                ('options4', models.CharField(max_length=100, null=True)),
                ('options5', models.CharField(max_length=100, null=True)),
                ('answer', models.IntegerField()),
                ('image', models.TextField(max_length=1000, null=True)),
                ('prac_quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_cms.practice')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='GradingScheme_grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('O_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('O_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('A_plus_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('A_plus_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('A_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('A_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('B_plus_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('B_plus_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('B_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('B_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('C_plus_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('C_plus_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('C_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('C_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('D_plus_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('D_plus_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('D_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('D_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('F_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('F_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_evaluation', models.TextField(default=None, max_length=255)),
                ('weightage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_ques', to='online_cms.forum')),
                ('forum_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reply', to='online_cms.forum')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=100)),
                ('video_name', models.CharField(max_length=40)),
                ('video_url', models.CharField(max_length=100, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=100)),
                ('document_name', models.CharField(max_length=40)),
                ('document_url', models.CharField(max_length=100, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
                ('module_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_cms.modules')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=40)),
                ('file_url', models.CharField(max_length=100, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.courseinstructor')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
    ]
