# Generated by Django 3.1.5 on 2024-10-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
        ('online_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradingscheme',
            name='type_of_evaluation',
            field=models.CharField(max_length=100),
        ),
    ]
