# Generated by Django 3.1.5 on 2023-04-13 13:53

import applications.online_cms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_auto_20230406_1845'),
        ('online_cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('submit_date', models.DateTimeField()),
                ('assignment_name', models.CharField(max_length=100)),
                ('doc', models.FileField(blank=True, null=True, upload_to=applications.online_cms.models.assignment_file_name)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('document_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('doc', models.FileField(blank=True, null=True, upload_to=applications.online_cms.models.content_file_name)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.course')),
            ],
        ),
        
        migrations.AlterField(
            model_name='coursedocuments',
            name='document_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        
    ]
