# Generated by Django 3.1.5 on 2024-10-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_grades',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='student_grades',
            name='remarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student_grades',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradingscheme',
            name='type_of_evaluation',
            field=models.CharField(max_length=100),
        ),
    ]
