# Generated by Django 3.0.6 on 2020-06-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseVideo',
        ),
    ]
