# Generated by Django 3.1.5 on 2024-02-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
        ('online_cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('assignment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('midsem', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('endsem', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('projects', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.course')),
            ],
        ),
    ]
