# Generated by Django 3.1.5 on 2023-04-13 13:56

import applications.online_cms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_auto_20230406_1845'),
        ('online_cms', '0002_auto_20230413_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssignment1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('course_code', models.CharField(max_length=100)),
                ('doc', models.FileField(blank=True, null=True, upload_to=applications.online_cms.models.assignment_submit_name)),
                ('score', models.IntegerField(null=True)),
                ('feedback', models.CharField(max_length=100, null=True)),
                ('assign_name', models.CharField(max_length=100)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_cms.courseassignment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentAssignment',
        ),
    ]
