# Generated by Django 3.1.5 on 2025-04-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0002_auto_20241023_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_grades',
            name='academic_year',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='student_grades',
            name='semester_type',
            field=models.CharField(choices=[('Odd Semester', 'Odd Semester'), ('Even Semester', 'Even Semester'), ('Summer Semester', 'Summer Semester')], max_length=20, null=True),
        ),
    ]
