# Generated by Django 3.1.5 on 2025-02-10 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
        ('online_cms', '0002_auto_20250128_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='no_of_attendance',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('evaluation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_cms.gradingscheme')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
    ]
