# Generated by Django 3.0.6 on 2020-06-02 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0005_auto_20200522_1851'),
        ('online_cms', '0002_delete_coursevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=100)),
                ('video_name', models.CharField(max_length=40)),
                ('video_url', models.CharField(max_length=100, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.Course')),
            ],
        ),
    ]
