# Generated by Django 3.1.5 on 2025-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0002_auto_20241012_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_grades',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='student_grades',
            name='reSubmit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student_grades',
            name='remarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student_grades',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
