# Generated by Django 3.1.5 on 2024-04-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0003_auto_20240422_1241'),
        ('academic_information', '0001_initial'),
        ('online_cms', '0002_student_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AlterField(
            model_name='coursedocuments',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AlterField(
            model_name='student_grades',
            name='batch',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='student_grades',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.AlterField(
            model_name='student_grades',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='topics',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course'),
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='GradingScheme_grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('O_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('O_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('A_plus_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('A_plus_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('A_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('A_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('B_plus_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('B_plus_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('B_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('B_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('C_plus_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('C_plus_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('C_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('C_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('D_plus_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('D_plus_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('D_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('D_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('F_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('F_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_evaluation', models.TextField(default=None, max_length=255)),
                ('weightage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=40)),
                ('file_url', models.CharField(max_length=100, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme_curriculum.courseinstructor')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student')),
            ],
        ),
        migrations.AddField(
            model_name='coursedocuments',
            name='module_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_cms.modules'),
        ),
    ]
