# Generated by Django 3.1.5 on 2026-03-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0003_alter_coursedocuments_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='announced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='announced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='announcement',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
