# Generated by Django 3.1.5 on 2024-03-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0003_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedocuments',
            name='module_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_cms.modules'),
        ),
    ]
