# Generated by Django 3.1.5 on 2025-04-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0003_auto_20250402_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedocuments',
            name='document_url',
            field=models.FileField(default='course_documents/default.pdf', upload_to='course_documents/'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='upload_url',
            field=models.FileField(upload_to='assignments/'),
        ),
    ]
