# Generated by Django 3.1.5 on 2025-04-09 21:47

from django.db import migrations

def populate_academic_year_and_semester_type(apps, schema_editor):
    Student_grades = apps.get_model('online_cms', 'Student_grades')

    for obj in Student_grades.objects.filter():
        sem_no = obj.semester
        working_year = obj.year

        # session logic
        if sem_no % 2 == 1:
            academic_year = f"{working_year}-{str(working_year + 1)[-2:]}"
        else:
            academic_year = f"{working_year - 1}-{str(working_year)[-2:]}"

        # semester_type logic
        if sem_no == 0:
            semester_type = "Summer Semester"
        elif sem_no % 2 == 0:
            semester_type = "Even Semester"
        else:
            semester_type = "Odd Semester"

        obj.academic_year = academic_year
        obj.semester_type = semester_type
        obj.save(update_fields=['academic_year', 'semester_type'])

class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0003_auto_20250409_2146'),
    ]

    operations = [
        migrations.RunPython(populate_academic_year_and_semester_type),
    ]
