# Generated by Django 3.1.5 on 2023-03-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0004_auto_20230313_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment1',
            name='course_code',
            field=models.CharField(default='CS416e', max_length=100),
            preserve_default=False,
        ),
    ]
