# Generated by Django 3.1.5 on 2024-03-10 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
        ('online_cms', '0004_coursedocuments_module_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='course_id',
            field=models.ForeignKey(default=405, on_delete=django.db.models.deletion.CASCADE, to='academic_information.course'),
        ),
    ]
