# Generated by Django 3.1.5 on 2026-03-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0004_auto_20260326_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
