# Generated by Django 3.1.5 on 2026-07-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme_curriculum', '0033_auto_20260704_1109'),
        ('online_cms', '0004_populate_academic_year_and_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_grades',
            name='course_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme_curriculum.courseinstructor'),
        ),
    ]
