# Generated by Django 3.1.5 on 2023-04-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0005_studentassignment1_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedocuments',
            name='document_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
