# Generated by Django 3.1.5 on 2024-11-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0005_merge_20241116_0303'),
        ('online_cms', '0005_merge_20241116_0233'),
    ]

    operations = [
    ]
