# Generated by Django 3.1.5 on 2024-04-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
        ('online_cms', '0005_modules_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingscheme',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='gradingscheme',
            name='endsem',
        ),
        migrations.RemoveField(
            model_name='gradingscheme',
            name='midsem',
        ),
        migrations.RemoveField(
            model_name='gradingscheme',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='gradingscheme',
            name='quiz',
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='type_of_evaluation',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='weightage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='GradingScheme_grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('O_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('O_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('A_plus_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('A_plus_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('A_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('A_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('B_plus_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('B_plus_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('B_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('B_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('C_plus_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('C_plus_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('C_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('C_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('D_plus_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('D_plus_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('D_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('D_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('F_Lower', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('F_Upper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.course')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=40)),
                ('file_url', models.CharField(max_length=100, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.course')),
            ],
        ),
    ]
