# Generated by Django 3.1.5 on 2024-11-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0006_merge_20241118_1545'),
        ('online_cms', '0006_merge_20241118_1914'),
    ]

    operations = [
    ]
