# Generated by Django 3.1.5 on 2024-11-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0002_auto_20241116_1949'),
        ('online_cms', '0007_merge_20241118_2045'),
    ]

    operations = [
    ]
