# Generated by Django 3.1.5 on 2024-04-12 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
        ('online_cms', '0007_student_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_grades',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='student_grades',
            name='student_id',
            field=models.ForeignKey(default='21BCS068', on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AlterField(
            model_name='student_grades',
            name='batch',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='student_grades',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
